### ISSUE TITLE
Provide a way to check if the provided JSON is a valid form schema

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#10]
__Is your feature request related to a problem? Please describe__

In Camunda Cockpit, we want to render a preview of the deployed form in the deployment view. As the schema is just a `.json` file, we need a way to differentiate between camunda forms and 'regular' JSON.

__Describe the solution you'd like__
When importing an invalid form, throw an error.

This way, we can react to errors with try-catch blocks:

```
try {
  const form = createForm({
    container,
    schema: questionableJson,
    data
  });
} catch (e) {
  // Hide the Container
}
```

__Describe alternatives you've considered__
I see 2 alternatives which both use validation before invoking `createForm`
- Add a utility function to check if a JSON is a valid schema
- Have a key in the schema which describes its, such as the `display: "form"` from formsIO.

__Additional context__
Cockpit Deployment view with Form preview:
![localhost_8080_camunda_app_cockpit_default_ (11)](https://user-images.githubusercontent.com/21984219/108202789-ef71bc80-7121-11eb-9183-fcd0f123660b.png)

**Comment by MaxTru** [comment]
**Discussed alternative in cross-team alignment:**
rendering library shall return something whether the form can be/was rendered (e.g., by throwing an error or returnin an err object)

**Comment by nikku** [comment]
With the next version of the library we're shipping your suggestion: The viewer creation will fail hard with an exception _if_ the form schema cannot be recognized. A more or less descriptive error message is being displayed.

Cf. https://github.com/bpmn-io/form-js/pull/27/commits/4d3889a0bcd19d4e144bbac117ab11ab4ce025ba.

**Comment by nikku** [comment]
We'll further improve this behavior in the future and/or split form instantiation and import.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/form-js/issues/27 for the moment.
