### ISSUE TITLE
Version 0.2.1 has missing dependency

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#100]
__Describe the Bug__

After installing `@bpmn-io/form-js@0.2.1` our project wouldn't start because the module `min-dom` is missing

__Steps to Reproduce__

You can check a reproduction in this [Codesandbox](https://codesandbox.io/s/affectionate-smoke-9v1n9?file=/src/App.js)

__Expected Behavior__

The library should have all necessary modules out of the box

**Comment by philippfromme** [comment]
Not sure what's happening there. `min-dom` is a dependency of `diagram-js`. This might be an issue with the [rollup configuration](https://github.com/bpmn-io/form-js/blob/master/packages/form-js-editor/rollup.config.js#L18). @nikku Any thoughts on this?

Thanks for reporting!

**Comment by nikku** [comment]
Fixed via `v0.2.2`.
