### ISSUE TITLE
[Implement] Custom HTML component [WIP]

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#1001]
** Product epic : https://github.com/camunda/product-hub/issues/1913 **

## Summary
...

#### Questions
- [ ] What will our interface look like?
- [ ] Do we have a requirement to use an iframe?
- [ ] Do we want any kind of injection?

#### Prototyping
- [ ] Render arbitrary code inside a frame

#### Implementation
- [ ] Component
	- [ ] Component proper
	- [ ] Properties panel configuration
	- [ ] Properties panel data entry component (popout editor) to be worked out. 
- [ ] Evaluate security risks
- [ ] To define: data interface?
- [ ] To define: iframe or not?

...

**Comment by marcosgvieira** [comment]
@Skaiir can you please update this task - what are the iterations we want to achieve?

**Comment by Skaiir** [comment]
@marcosgvieira At this point we're only looking to build the interactive HTML component anymore. Tracking it [here](https://github.com/bpmn-io/form-js/issues/1049), so I'm gonna close this issue.
