### ISSUE TITLE
Validation out of sync with value changes

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#1009]
### Describe the Bug

On Tasklist when using `form-js` if a user edits an input and tabs out of the input some times a validation error is shown out of sync with input value

### Steps to Reproduce

1. Go to Camunda Tasklist
2. Open a task and then another task with has a form with a required input
3. Fill the input which has a required value
4. Tab out
5. A validation error is shown even if the input is filled

### Expected Behavior
No validation should be shown

### Extra info

https://github.com/bpmn-io/form-js/assets/1022916/86840fb7-a953-45f6-b72b-2e3b73c72801

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/1022
