### ISSUE TITLE
Anchor Tags Can Lead to Page Reload

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#101]
__Describe the Bug__

Anchor tags with an empty or relative `href` lead to a page reload.

![WXWAQ5Wf4h](https://user-images.githubusercontent.com/7633572/122735191-17635f00-d27f-11eb-85eb-a6d83c9f8d02.gif)

__Steps to Reproduce__

1. Add `<a href>Click</a>` or `<a href="foo">Click</a>` to a text form field
2. Click link in form
3. Page reloads

__Expected Behavior__

Page doesn't reload. One way to avoid this issue would be adding `target="_blank"` to all anchor tags by default.

__Environment__

- Library version: 0.2.0

**Comment by nikku** [comment]
Proposal enforce links opening as `target="_blank" rel="noopener"` for all but local anchors (`#xyz`).

**Comment by andreasgeier** [comment]
I agree that we should open links externally: in a viewer scenario a new tab would be opened. In the editor we would call the standard browser of the system to open the link.

In the viewer, anchor links should not show that behavior but jump to the reference _within_ a page. Editor scenario tbd

**Comment by philippfromme** [comment]
This issue is fixed in `v0.24.0` of `form-js`. Therefore, I'll close this issue. A follow-up issue regarding the potential enhancement can be found here: https://github.com/bpmn-io/form-js/issues/116.

@andreasgeier Links within the document work as expected.

![NJ6hq8jt0m](https://user-images.githubusercontent.com/7633572/123631151-b3a8db00-d816-11eb-919e-be29290530c8.gif)
