### ISSUE TITLE
Potentially Harmful JavaScript Not Removed If It Contains Line Break

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#102]
__Describe the Bug__

Using

```markdown
[foo](j
avascript:alert`foo`)
```

instead of

```markdown
[foo](javascript:alert`foo`)
```

will lead to not removing the potentially harmful JavaScript not being removed.

![ZnkPD58x7l](https://user-images.githubusercontent.com/7633572/122740986-cd7d7780-d284-11eb-9adf-93a23ea35037.gif)

__Steps to Reproduce__

1. Add the following markdown to a text form field

```markdown
[foo](j
avascript:alert`foo`)
```

2. Click the link in the form
3. Alert is shown

__Expected Behavior__

No JavaScript is executed.

__Environment__

- Library version: 0.2.0

**Comment by nikku** [comment]
Fixed via `v0.2.2`.
