### ISSUE TITLE
Provide API to easily extract all input data properties relevant to a form schema

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#103]
__Is your feature request related to a problem? Please describe__

On Tasklist we only fetch the necessary variables used as initial values for the form based on the editable form field names.
Currently we're parsing the schema ourselves but as the number of components in `form-js` grows this will become unmaintainable.

__Describe the solution you'd like__

Provide a function where we can extract the editable field names from a form schema:

```js
import { getEditableFieldNames } from '@bpmn-io/form-js';

const FORM_SCHEMA = ` ... `; // a schema with a checkbox, textarea, a reset and submit buttons

console.log(getEditableFieldNames(FORM_SCHEMA)); // logs [ 'checkboxFieldName', 'textareaFieldName' ]

```

__Describe alternatives you've considered__

Another option is to add the prop `editableFieldNames` on form instance, I like this one a bit less because we would have to wait until the form is rendered to access the names:
```js
import { createForm } from '@bpmn-io/form-js';

const FORM_SCHEMA = ` ... `; // a schema with a checkbox, textarea, a reset and submit buttons
const form = await createForm({
  schema: FORM_SCHEMA,
  data,
  container: document.querySelector('#form')
});

console.log(form.editableFieldNames); // logs [ 'checkboxFieldName', 'textareaFieldName' ]
```

**Comment by philippfromme** [comment]
So what you're asking for is a way of getting information about the data that will be submitted by a form?

**Comment by vsgoulart** [comment]
> So what you're asking for is a way of getting information about the data that will be submitted by a form?

Yes, exactly. I want to get the name of all the fields that could be edited have their own value

**Comment by philippfromme** [comment]
For now parsing the schema manually is the only option to get all the `keys` without instantiating and importing a form. We might offer a utility in the future but I'm not sure when.
