### ISSUE TITLE
HTML component documentation page is not working

### ISSUE THREAD

**Issue by esraagamal6** [bpmn-io/form-js#1041]
### Describe the Bug

"Learn more" button for HTML component navigates the user to not found page

### Steps to Reproduce

1. Open form Editor
2. Add HTML component
3. From the HTML properties press "Learn more" button

### Expected Behavior
User is navigated to the docs

### Actual Behavior
404 page not found

**Comment by vsgoulart** [comment]
Already fixed by https://github.com/bpmn-io/form-js/pull/1039

It will be included on the next release
