### ISSUE TITLE
Bug: Links in HTML component always open in same view

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#1054]
### Describe the Bug

Links in the HTML component always open in the same view, even when `target="_blank"` is present.

### Steps to Reproduce

1. Add HTML view and add link with `target="_blank"`
2. Deploy form to Tasklist (or test in forms playground)
3. Clicking the link opens it in the same tab

### Expected Behavior

Links should **always** open in a new tab

### Environment

- form-js 1.7

**Comment by Skaiir** [comment]
I'm fixing this directly in web modeler, as we don't really want to make assumptions within form-js about how those links should redirect. It's up to the implementer I reckon to choose. 

https://github.com/camunda/web-modeler/pull/8211

**Comment by christian-konrad** [comment]
@Skaiir makes sense, but also take care of Tasklist here, and it should not sanitize `target="_blank"` I believe

**Comment by Skaiir** [comment]
This has been updated in web modeler and merged. It still needs updating in tasklist.

**Comment by marcosgvieira** [comment]
@Skaiir can we move this one, was it updated on tasklist?

**Comment by Skaiir** [comment]
Let's move it back to the backlog for now.

**Comment by Skaiir** [comment]
Actually we ended up fixing this in tasklist as well with the new release, so this issue may now be closed.
