### ISSUE TITLE
Expressions for default values

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#1062]
### Is your feature request related to a problem? Please describe.

Doing calculations in form-js can be cumbersome, since there is no way to store intermediate results.

Example: take calculations of subtotal and total values into consideration. A fairly low-complex use case, but already hard to manage.
I have to repeat the same expression multiple times. I also want to have a condition to evaluate if the value is displayable or not (e.g. if it's null since one subtotal is null, show a placeholder in the UI). Alternatively, filter null values out of the array before running further aggregations. However, that's not maintanable.

<img width="1033" alt="Bildschirmfoto 2024-02-21 um 10 50 29" src="https://github.com/bpmn-io/form-js/assets/56470362/8cbe347e-8e1f-41e9-b83c-32a0b1d2162f">

### Describe the solution you'd like

Be able to set an expression as a default value to fields. By setting them read-only at the same time (or even hidden - not yet possible), I can calculate subtotals on the fly, and reuse these values in other expressions.

### Describe alternatives you've considered

Using state management patterns such as observables and transformers to calculate intermediate values (or any function result value) in a separate panel.

**Comment by Skaiir** [comment]
I think we've had this chat before, but using default values for precomputing values is kind of a workaround. This goes into the whole using hidden fields for state and configuration that kinda ain't great. Also what if you need this value to update in real time, now default isn't enough anymore, you can't configure your way out of it. 

I know I'm sounding like a broken clock but, data panel :eyes:

**Comment by christian-konrad** [comment]
Closing in favor of https://github.com/camunda/product-hub/issues/2134 

fyi @Skaiir
