### ISSUE TITLE
Expression fields for data processing and output / Hidden fields

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#1073]
### Is your feature request related to a problem? Please describe.

Sometimes, we want to produce some additional data alongside that produced by our regular fields. We also may want to produce some generic data which can be used as intermediate information to simplify further feel expressions down the line.

### Describe the solution you'd like

While the ideal solution for this would be to have some powerful data handling capabilities, a quick and easy way to fix this at least for the time being is to solve this via a hidden field approach.

### Describe alternatives you've considered

The aforementioned data panel, but this would be very costly to implement. 

### Additional context

Initial discussions: https://github.com/camunda/camunda-modeler/issues/4123

**Comment by esraagamal6** [comment]
@Skaiir Tested OK
