### ISSUE TITLE
Consider replacing `showdown`

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#1083]
### What should we do?

`showdown` has a possible [CVE](https://github.com/advisories/GHSA-rmmh-p597-ppvv) we need to investigate and possibly replace it
A possible alternative is [`marked`](https://www.npmjs.com/package/marked)

### Why should we do it?
To have no vulnerabilities

**Comment by Skaiir** [comment]
I feel like we actually replaced marked by showdown. Or maybe it was another framework, but anyways does marked actually support GFM?

**Comment by nikku** [comment]
The replacment train keeps on rolling :slightly_smiling_face:
