### ISSUE TITLE
Code blocks in text view print white spaces as html entities

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#1093]
### Describe the Bug

Markdown code blocks in the text view component print white spaces as html entities. This happens since the update from an allow-list to an HTML sanitizer.

<img width="944" alt="image" src="https://github.com/bpmn-io/form-js/assets/56470362/bfba8d6d-d1ab-4389-98c2-d8fe82622340">

### Expected Behavior

Do not print HTML entities in markdown code blocks.

### Environment

- form-js in Web Modeler as of March 13 2024

**Comment by Skaiir** [comment]
@christian-konrad Can you paste a sample in here? I assume it's something to do with where you're copying from.

**Comment by christian-konrad** [comment]
@Skaiir I see. I copied it from a text annotation of bpmn.io. That seems to be an edge case. Let's close here

<img width="228" alt="Bildschirmfoto 2024-03-18 um 09 34 40" src="https://github.com/bpmn-io/form-js/assets/56470362/443e3c33-a418-47a5-aea9-3053406ecd1c">
