### ISSUE TITLE
Required date field shows "Field is required." on form exhibition

### ISSUE THREAD

**Issue by wesleimarinho** [bpmn-io/form-js#1099]
### Describe the Bug

When displaying a form that contains a required date field for user input, the date field displays a validation message "Field is required.", whereas the other fields do not.

### Steps to Reproduce

1 - Create a form with two fields: one of type text and the other of type date, both required.
2 - Display the form for user input.

### Expected Behavior

Both fields should show no validation message upon the initial display of the form.

### Environment

- Host Chrome 122
- OS: Windows 11
- Library version: @bpmn-io/form-js@1.7.1

**Comment by Skaiir** [comment]
fixed via https://github.com/bpmn-io/form-js/pull/1121
