### ISSUE TITLE
Typescript can't find a declaration file for "@bpmn-io/form-js" module

### ISSUE THREAD

**Issue by Rastuharem** [bpmn-io/form-js#1105]
### Describe the Bug

Importing something from "@bpmn-io/form-js" throws the following error by TypeScript:

```
Could not find a declaration file for module '@bpmn-io/form-js-viewer'. '<system path>/formjs-template/node_modules/@bpmn-io/form-js-viewer/dist/index.es.js' implicitly has an 'any' type.
  There are types at '<system path>/formjs-template/node_modules/@bpmn-io/form-js-viewer/dist/types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@bpmn-io/form-js-viewer' library may need to update its package.json or typings.ts(7016)
```

### Steps to Reproduce

1. Create vanilla Vite + TS project (I was using npm create-vite package)

```
npm create vite formjs-template
cd formjs-template
npm i
npm i @bpmn-io/form-js
```

2. Create new `formjs.ts` and type the following code:

```
import { Form } from "@bpmn-io/form-js-viewer";

const form = new Form({});
```

4. The following error should appear

<img width="745" alt="image" src="https://github.com/bpmn-io/form-js/assets/95254106/cd0b79fd-34b8-4108-9639-7594f1d19540">

### Expected Behavior

Form class loads without errors and has defined type.

### Environment

- Node: v20.11.1
- OS: Windows 11
- Library version: 1.7.3

**Comment by Rastuharem** [comment]
It seems to relate to 4.7 TS update:
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing

Modifying "@bpmn-io/form-js" package.json fixed described error:

```
{
  "name": "@bpmn-io/form-js",
  "version": "1.7.3",
  "description": "View and edit forms - powered by bpmn.io",
  "exports": {
    ".": {
      "types": "./dist/types/index.d.ts", // added types here
      "import": "./dist/index.es.js",
      "require": "./dist/index.cjs"
    },
...
```

**Comment by Skaiir** [comment]
This is kind of an oddity of our configuration, but very nicely spotted. I've been going through this write-up here https://stackoverflow.com/a/72530967, which seems to describe a similar situation. Anyways, I checked the common solution here and it seems to work well. Will send over a fix in a bit. 

Thanks @Rastuharem for the report.

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/1122
