### ISSUE TITLE
When selecting a component in Form definition canvas the content area automatically jumps to the top

### ISSUE THREAD

**Issue by volodymyr-melnykc** [bpmn-io/form-js#1106]
### Describe the Bug

The content area automatically jumps to the top when selecting a component on the Form definition canvas.
It’s happening when the Form Preview is also open, though it doesn’t when it’s closed.

### Steps to Reproduce

1. Open the form editor.
2. Add many components on the canvas to make the view scrollable.
3. Have the Form Preview closed/collapsed.
4. Select (with the mouse) form components placed in the middle of the canvas.
5. The component gets selected and the content area doesn't scroll (correct).
6. Open/expand the Form Preview.
7. Select (with the mouse) form components placed in the middle of the canvas.
8. The component gets selected, but the content area automatically scrolls to have the selected component at the top (incorrect).

See the video recording:

https://github.com/bpmn-io/form-js/assets/143816833/f3c22a92-8fef-4845-a7dc-c37d9d1b0872

### Expected Behavior

- When selecting a component the content area shouldn't automatically scroll.

### Environment

- Host (Browser/Node version): Chromium Engine Version 122.0.6261.129
- OS: MacOS Sonoma
- Library version: 8.4

**Comment by Skaiir** [comment]
Fixed via https://github.com/bpmn-io/form-js/pull/1108
