### ISSUE TITLE
 Built in feel expressions for lists like "concatenate" and "append" evaluates to nothing

### ISSUE THREAD

**Issue by sindremb** [bpmn-io/form-js#1135]
### Describe the Bug

Using some built in feel expressions for lists like "concatenate" and "append" evaluates to nothing when used in form components with package `@bpmn-io/form-js-viewer@1.8.3` 

Other built in list functions like "count" seems to work as expected.

### Steps to Reproduce

Create a form viewer instance for a schema using the concatenate function in an expression something like this:

```js

import { Form} from '@bpmn-io/form-js-viewer';

const schema = {
  components: [
    {
      text: '\nHere we try to insert count of concatenated lists: {{count(concatenate([1, 2, 3], [4, 5]))}}\nHere we try to insert count of single list: {{count([1, 2, 3])}}',
      label: 'Text view',
      type: 'text',
      layout: {
        row: 'Row_1',
        columns: null
      },
      id: 'Field_1'
    }
  ],
  type: 'default',
  id: 'concatenate-test-form',
  schemaVersion: 15
};

const form = new Form({
  container: document.getElementById('my-container')
});

form.importSchema(schema);

```

Observe rendered output failing to handle the concatenation correctly as follows:

```
Here we try to insert count of concatenated lists:
Here we try to insert count of single list: 3
```

Note that this is a highly simplified case to demonstrate the failing "concatenate" function. Our actual case is related to using concatenate inside a data source expression in a table component for a "show more/less" toggle feature, but this simplified case demonstrates the same issue with the built in function.

### Expected Behavior

Should be able to concatenate and count the list correctly with the following output

```
Here we try to insert count of concatenated lists: 5
Here we try to insert count of single list: 3
```

### Environment

- Host: Firefox 125.0b9
- OS: Windows 11
- Library version: 1.8.3

### Other info

It could be the case that we are using this form viewer library incorrectly, but the above sample reflects how we have used it based on the available documentation. We do have the exact same form working as expected inside the Camunda Tasklist v8.4.4, but not when trying to implement a custom task list using this library, so I would assume there is some work around, configuration, or specific versions, where this will work as expected.

**Comment by Skaiir** [comment]
Hi there @sindremb, firstly thanks for the detailed bug report. 

I've tried your expression on the [FEEL playground](https://nikku.github.io/feel-playground) which should be using the same evaluation engine, working very well. Maybe we're behind on versions of the eval engine, or it could be unrelated. I'll investigate very shortly.

**Comment by Skaiir** [comment]
@sindremb Can't replicate. Do you have `concatenate` as an input variable by any chance?

**Comment by sindremb** [comment]
@Skaiir Thank you for your response. I am using the exact same code as in the sample above, just inside a larger (fairly standard) react application. It looks to be an issue triggered by our setup.

I have done some more digging, and observe this strange behaviour also when using the `feelin` library directly. If I for instance try to run this code somewhere inside our react application (tested inside `index.tsx` entry point for the app)

```
import { evaluate } from 'feelin'; // v3.0.1

console.log(evaluate('concatenate([1, 2, 3], [4, 5])'));
```

It outputs `null` in the react application, but the exact same snippet outputs `[1, 2, 3, 4, 5]` if run independently inside the same project and node modules (tested by placing above code in a temp `testing.js` in the react apps root and running `node testing.js`). If i switch to `evaluate('count([1, 2, 3])')` it behaves the same in both contexts.

I am really confused by this behaviour, having the FEEL library being in a state where it only partly works? Something with how the react application bundles packages?

I assume I should close this issue then? If you happen to have any tips for where to dig further in our setup, it is very much appreciated :)

**Comment by Skaiir** [comment]
@sindremb We can keep the issue open for now. Because although it's triggered by your setup our libraries should not be setup dependent. I will try and create a minimal reproducible example and I'll follow up on this.

**Comment by nikku** [comment]
@sindremb Two suggestions: You could debug what is going on in your application, and see where it goes awry. feelin looks for [functions to be available](https://github.com/nikku/feelin/blob/main/src/interpreter.ts#L552) (and implemented) and you could track if that exists in your case.

**Comment by sindremb** [comment]
@nikku Ok, so I've done a bit more digging, and it seems to be that the `feelin` package breaks when bundled by webpack.

I've traced the concatenate function to evaluate to null when the library has been processed by webpack [due to the parameter validation in the FunctionWrapper](https://github.com/nikku/feelin/blob/4ea768e438aeba58cc042aa26b8b7267acd3ff40/src/types.ts#L291) not finding the expected `...args` parameter in the function being wrapped.

This parameter name is missing here due to the `parseParameterNames(fn)` function [relying on fn.toString()](https://github.com/nikku/feelin/blob/4ea768e438aeba58cc042aa26b8b7267acd3ff40/src/utils.ts#L12) to extract the parameter names.

When not bundled by webpack. fn.toString() in this case outputs

```
function (...args) {
        const convertedArgs = checkArgs(args);
        if (!convertedArgs) {
            return null;
        }
        return fnDefinition(...convertedArgs);
    }
```

And we can see that the `...args` parameter name can be extracted from this.

When bundled by webpack, we get a similar, but different result from toString()

```
function () {
    for (var _len18 = arguments.length, args = new Array(_len18), _key18 = 0; _key18 < _len18; _key18++) {
      args[_key18] = arguments[_key18];
    }
    const convertedArgs = checkArgs(args);
    if (!convertedArgs) {
      return null;
    }
    return fnDefinition(...convertedArgs);
  }
```

And here we have lost the expected `...args` parameter from the output.

I guess this is due to the webpack setup from create-react-app transpiles to an older JS spec for wider browser support, and this could potentially be fixed by changing the target. However, it would be nice if the library would support a common default setup like this without breaking.

**Comment by sindremb** [comment]
Ah, ok then, so you have it tracked already then.

Some added info, if I relax my browserlist support for dev from

```
  // [...]
  "browserslist": {
    // [...]
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  // [...]
```

To (skipping safari)

```
  // [...]
  "browserslist": {
    // [...]
    "development": [
      "last 1 chrome version",
      "last 1 firefox version"
    ]
  },
  // [...]
```

It seems to work again. Since we are currently just making an internal tool (for now), it might be feasible for us to just limit browser support.

But it would still be good to know if there are any plans to resolve the linked issue in the near future?

**Comment by nikku** [comment]
> But it would still be good to know if there are any plans to resolve the linked issue in the near future?

No immediate plans. As we're talking about rest parameters let's look at their [support in modern browsers](https://caniuse.com/rest-parameters). Given that browsers without `...` support are dying I see little incentive to invest.

**Comment by sindremb** [comment]
@nikku seems reasonable. I'll make a note of handling compatible targeting in our setup as a workaround.

**Comment by nikku** [comment]
Thanks for taking your time to dig into this issue and discuss. :slightly_smiling_face:
