### ISSUE TITLE
Error while loading tag list component.

### ISSUE THREAD

**Issue by jay67nie** [bpmn-io/form-js#1168]
### Describe the Bug

When I put a taglist in a form and display it using the form.js package, I get an error that prevents other forms from loading as well

### Images

![image](https://github.com/bpmn-io/form-js/assets/109383033/5110a2ca-ae69-413c-9ea7-1c2b88e2e142)

![image](https://github.com/bpmn-io/form-js/assets/109383033/c4a164d9-a9ff-42ac-9705-b190a4e177c4)
![image](https://github.com/bpmn-io/form-js/assets/109383033/28bcbafa-fe0e-4495-9039-36a4f19e1631)

### Expected Behavior

The form should load normally despite the taglist being there.
This used to work in earlier versions (1.4) but now it doesn't.

### Environment

- Host (Browser/Node version), if applicable: Chrome 124
- OS: Windows 11
- Library version: 1.8.5

**Comment by jay67nie** [comment]
How far with this?

**Comment by Skaiir** [comment]
@jay67nie Working on trying to replicate, can you send me the smallest form you can cause the error with, and show me how you load it exactly?

**Comment by jay67nie** [comment]
I realized that I was passing the values into "defaultValue" key instead of "values" key, which was wrong. I am closing the comment now.
