### ISSUE TITLE
Getting an error when trying to delete a group inside the Dynamic list

### ISSUE THREAD

**Issue by volodymyr-melnykc** [bpmn-io/form-js#1173]
### Steps to Reproduce

1. Add a dynamic list to a form.
2. Place a group inside of the dynamic list.
3. Try to delete the dynamic list or group, which isn't possible and produces an error in the browser console.

![image](https://github.com/bpmn-io/form-js/assets/143816833/1b3efe61-ddc8-4386-9677-2fe1698fd315)

### Expected Behavior

- The dynamic list or group can be deleted.

### Environment

- Host: Chromium Engine Version 124.0.6367.79
- OS: MacOS 14.1.2 
- Library version: 8.5

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/1194
