### ISSUE TITLE
Sample Form Viewer code is missing type attribute on form. 

### ISSUE THREAD

**Issue by temecom** [bpmn-io/form-js#1175]
### Describe the Bug
When following the sample code at : https://github.com/bpmn-io/form-js/tree/develop/packages/form-js-viewer a runtime error is thrown: form field of type undefined not supported. 
### Steps to Reproduce

1. When Following the instructions in the page above 
2. And Running the code 
4. Then Browser error is thrown

### Expected Behavior

The form is rendered

### Environment
OS: WSL on Windows 11
Node Version : 20
TypeScript (Angular)  

### Fix 
The sample schema should include the 'default' type: 
schema {
    type: 'default',
    components: [
      {
        key: 'creditor',
        id: 'abcdef', 
        label: 'Creditor',
        type: 'textfield',
        validate: {
          required: true,
        },
      },
    ],
  };

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/1257
