### ISSUE TITLE
Button text does not evaluate the Feel expression

### ISSUE THREAD

**Issue by jjettenCamunda** [bpmn-io/form-js#1181]
### Describe the Bug

When using a dynamic value for the field label of a button the expression is printed on the button instead of the result of the evaluation.

### Steps to Reproduce

1. Create a new form in the form editor
2. Add a button form element
3. make the field label dynamic
4. add a feel expression to the field
5. View the value of the on the button in the preview

<img width="916" alt="image" src="https://github.com/bpmn-io/form-js/assets/97948434/78024603-874b-4ceb-a66b-890627d6db5a">

### Expected Behavior

The result of the evaluation of the Feel expression becomes the button text.

### Environment

- Host (Browser/Node version), if applicable: Firefox 126.0
- OS: MacOs 14.4.1
- Library version: Current web modeler version as of 21/05/2024

**Comment by Skaiir** [comment]
Closes via #1192
