### ISSUE TITLE
Elements disappear while after drag n drop on the editor

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#1184]
### Describe the Bug

In some cases while embedding the `form-js` editor in a React application modeled elements disappear after drag n drop

### Steps to Reproduce

1. Use `form-js` inside a React app like in [here](https://codesandbox.io/p/devbox/62yfz5?embed=1&file=%2Fsrc%2Fstyles.css&migrateFrom=66fr8k)
2. Add some elements
3. Drag n drop elements around
4. Dropped elements disappear

### Expected Behavior

Elements should not disappear

### Extra information

[Link to the forum thread](https://forum.bpmn.io/t/integrate-form-editor-in-react-js-typescript/10993/3)

**Comment by esraagamal6** [comment]
Duplicated in https://github.com/bpmn-io/form-js/issues/1216
