### ISSUE TITLE
Labels are added to the schema for unlabeled fields

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#1196]
### Describe the Bug

Labels are automatically generated for fields which do not use them. See:

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/2889146e-fe6f-4093-97a6-fae5a1e91715)

The main issue stems from the fact that we do not have a property which makes fields labeled or unlabeled, or rather we have no differentiator between labels used in the editor/palette and labels used in the field itself.

### Steps to Reproduce

1. add a text view using the editor playground
2. inspect the schema
3. label is present

### Expected Behavior

3. no label should be present

### Environment

All in latest

**Comment by sanjogbhalla16** [comment]
Hi @Skaiir , its my first time and would like to work on this , if the issue is still open.

**Comment by Skaiir** [comment]
Hey there @sanjogbhalla16, timing is unfortunate but I'm in the middle of doing something that is fixing this anyways. So I'll take this issue. Maybe there's something else you could check out :)

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/1300
