### ISSUE TITLE
Reset does not work on Number fields if no default is provided

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#122]
__Describe the Bug__

When opening a form with number fields and no default values, the reset button does not work.

![recording (17)](https://user-images.githubusercontent.com/21984219/124623754-8692a300-de7c-11eb-937a-76bbf388d5e3.gif)

__Steps to Reproduce__

1. Open the Codesandbox: https://codesandbox.io/s/pedantic-dijkstra-w5isz?file=/src/index.js
2. Fill in the "Amount" field (e.g. 123)
3. Click the "Reset" button

--> Amount field is not cleared

__Expected Behavior__

The Amount field is cleared

__Environment__

- Library version: 0.2.4

**Comment by philippfromme** [comment]
Thanks for reporting this. Will look into it!
