### ISSUE TITLE
Be Able to Statically Validate a Form

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#146]
__Is your feature request related to a problem? Please describe__

There is no way of validating a form without importing it into a form viewer or editor. We've had the same issue with element templates before introducing a JSON schema to validate against.

__Describe the solution you'd like__

Either introduce a JSON schema or find an alternative solution.

__Describe alternatives you've considered__

None.

__Additional context__

This is an issue for the Cawemo team as they are not able to statically validate forms before deploying them.

**Comment by nikku** [comment]
Could you elaborate on this use case? Why would you like to validate using a JSON schema? In case of errors, what would be the follow up? How would errors be introduced into a form in the first place.

**Comment by nikku** [comment]
We'd need further input why static validation is required.

Under the assumption that editor output is always valid (and import validates) I do not see an immediate use-case for this.
