### ISSUE TITLE
Resetting form does not work for select elements

### ISSUE THREAD

**Issue by huygur** [bpmn-io/form-js#155]
__Describe the Bug__

When we fill some text areas and then reset the form by calling form.reset() function, it clears the changed text areas. This function does not have any affect on select elements.

__Steps to Reproduce__

here is an example from codesandbox: https://codesandbox.io/s/cranky-http-f33y2

1. fill text area and select something from select element
2. click 'reset form' 
3. text area is cleared, select element is still filled

__Expected Behavior__

select element is cleared too

__Environment__

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by nikku** [comment]
Thanks for reporting this one!
