### ISSUE TITLE
Typings for `Form#on` and `FormEditor#on` are incorrect

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#159]
__Describe the Bug__

We current expose type definitions for `Form#on` and `FormEditor#on` that require users to use a third `priority=number` argument. We should fix our type definitions to allow both forms, two arg and three argument invocations to the list:

```
form.on('change', function(event) { });
form.on('change', 500, function(event) { });
```

__Expected Behavior__

As a user I'd like to use the simple form of registering for events. That form is referenced and documented, too.

__Environment__

- Host (Browser/Node version), if applicable: any
- OS: Windows
- Library version: v0.4.1

---

Reported via Camunda Cloud Devs.

**Comment by barmac** [comment]
Related to https://github.com/microsoft/TypeScript/issues/25590

**Comment by dfulgham** [comment]
Sorry if this is not a good way of handling this, but would something like this take care of this issue?

Add the following typedef's
```
/**
 * @typedef { (type:FormEvent,priorityOrHandler:number,handler:Function) => void } OnEventWithPriority;
 * @typedef { (type:FormEvent,priorityOrHandler:Function) => void } OnEventWithOutPriority;
 * @typedef { OnEventWithPriority & OnEventWithOutPriority} OnEventType
 * /
```

then create a private definition (#onEvent) for the on method and assign (this.on = #onEvent) in the constructor.  This will result in the overload being typed correctly in Typescript and in the IDE

```
...

/**
   *  private OnEvent function definition
   * 
   */
  #onEvent = (type,priorityOrHandler,handler) => {
    if (typeof priorityOrHandler !== 'number' && typeof handler === 'undefined') {
      handler = priorityOrHandler;
      priorityOrHandler = 0;
    }
    this.get('eventBus').on(type, priorityOrHandler, handler);
  }

  /**
   * @constructor
   * @param {FormOptions} options
   */
  constructor(options = {}) {

    /**
     * @type {OnEventType}
    */
    this.on = this.#onEvent;

...
}
```

**Comment by dfulgham** [comment]
in my PR its not accepting the #onEvent private class method, I could just change it to _onEvent ?  I have the same version of all libraries and it compiles and tests fine on my local machine, but the testing environment on CI is failing on the # character.

**Comment by nikku** [comment]
This would fix it, indeed.

Please change `#` to `_`. We try to avoid using the latest of JS but stick to certain evergreen patterns (`_` for private) instead.
