### ISSUE TITLE
Allow subscriptions on change events

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#16]
__Is your feature request related to a problem? Please describe__
External UI elements should also reflect the current state of the Form, such as dirty or invalid.

In our case, we have a "save" button which stores the current form content in the local storage. This button should only be enabled when the form was modified.
The "Complete" button should be disabled when the input is invalid.

![image](https://user-images.githubusercontent.com/21984219/109144899-12bfeb80-7762-11eb-8530-507603feb8bb.png)

__Describe the solution you'd like__
Emit an event when `FormCore#changed` is triggered that can be subscribed to with `form.on('changed', evt =>{})`.

If the event also contains the form validation/errors, we could also disable the submit button for invalid forms.

__Describe alternatives you've considered__
- Have events for 'dirty' or 'invalid'. I don't think this fits in the current design, as a submit is always possible, e.g. never 'invalid'.

- Do nothing, external buttons are always enabled and check the validity using the programmatic submit once pressed. This is how we currently implement it and it works fine.

__Additional context__
This is a nice to have

**Comment by andreasgeier** [comment]
IMHO, enabling a submit button only in case if the form is valid and complete, is a bad user experience. To enable a submit button, a user would have no clear indicator of which mandatory field is missing, for example. In long and complex forms this could cause an annoying and time-consuming search for an issue.

It is better to enable the submit at any time so a user could click on it and trigger validation of the form. Then all issues would be visible via validation styles and warning messages (if provided).

Having said this, I can imagine that some customers would like to have this behavior. The mentioned alternative to having events for dirty and invalid would solve that.

**Comment by marstamm** [comment]
I agree that this would be the case for required fields on a fresh form. But as soon as I have an invalid field with the visible error description, I would expect the submit button to be disabled.

As I understand it, there is no error present before the validation happens, so the submit button would still be enabled on a fresh form and would get disabled after the first submit/invalid change.

**Comment by andreasgeier** [comment]
> I agree that this would be the case for required fields on a fresh form. But as soon as I have an invalid field with the visible error description, I would expect the submit button to be disabled.

But then the logic wouldn't be consistent. The button would be enabled at the start, then disabled when a user action triggers a validation rule, and then enabled again when this is fixed...? But the form in its entirety would still be invalid because of other mandatory fields...? Or, if it is not enabled again after the fix, there would be confusion: why, I just fixed this field!?

I see a point that just in the very moment of a triggered validation a disabled button could be expected, but for simplicity and consistent logic, I would still prefer the always-enabled button as a default solution. – Perfect candidate for A/B test 😄

**Comment by nikku** [comment]
Our take on this is as @andreasgeier described: Pressing the submit is always possible, however it won't do anything if fields are invalid. This is reflected in the current way the toolkit is being built. If you submit, validation _will_ be triggered on all form fields and relevant errors will be shown.

I'd ask myself the question: What is the added value of disabling the submit button from the UX point of view? Errors are clearly indicated on the form elements. That should be enough for users to understand that things are not O.K. to submit, right?

One situation exists from my point of view where the submit button _shall_ be disabled: Depending on how long submission takes and whether your backing action is idempotent or not you may sometimes prevent double submission. This is when the button could be disabled. 

There exists a generic, low level `changed` event that you may hook into if you would overrule our defined default behavior in combinations with external buttons. That is your choice. 

We'll make that low level `changed` event available with the next library release, cf. https://github.com/bpmn-io/form-js/pull/18.

**Comment by marstamm** [comment]
Thank you for the detailed feedback. It makes sense to me for the submit button, we'll probably keep the default behavior :+1:

The changed event is still great, so we can keep the save button consistent with our other forms.

**Comment by nikku** [comment]
Thanks for your feedback again. We had the feature, but did not test or document yet. 

You triggered a nice little improvement. :medal_sports:

**Comment by nikku** [comment]
[Documented](https://github.com/bpmn-io/form-js/tree/master/packages/form-js-viewer#events) and released with `v0.0.6`.
