### ISSUE TITLE
Support Date Picker Type Components(form element) in form-js

### ISSUE THREAD

**Issue by nimeshmora** [bpmn-io/form-js#160]
Problem:
We develop custom application and need to generate user forms using form-js. Problem is we need Date Picker type elements to be included in our forms. But this type is not supported in form-js.

Solution:
Simple type like "Date" to define Date/Time Type elements in the form.

No workarounds or alternatives.

**Comment by nikku** [comment]
Thanks for reporting. We add that to our wishlist.

**Comment by pinussilvestrus** [comment]
We track the progress on the datetime picker in this issue: https://github.com/bpmn-io/form-js/issues/340
