### ISSUE TITLE
Show no hover state during dragging

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#162]
__Is your feature request related to a problem? Please describe__

When dragging a field we show a hover state over other elements:

https://user-images.githubusercontent.com/938244/131629926-4ccad486-7bc9-41c7-ac33-582df7c83add.mov

__Describe the solution you'd like__

Do not show the hover state when moving fields.

__Describe alternatives you've considered__

None.

__Additional context__

Related to https://github.com/camunda/camunda-modeler-design/issues/17.

**Comment by AyoubBoulahtar** [comment]
Is this still up for grabs ?

**Comment by Palaksharma23** [comment]
I would love to contribute to this issue .
Can you please assign me this issue

**Comment by nikku** [comment]
Up for grabs, first come, first serve :slightly_smiling_face:

**Comment by Skaiir** [comment]
Since this is now going against our design direction, and the new hover state is a lot more subtle, I think we can close this, feel free to reopen if you disagree.
