### ISSUE TITLE
Add custom component inside FORM ELEMENTS LIBRARY

### ISSUE THREAD

**Issue by VictorAITERA** [bpmn-io/form-js#165]
**Feature**

I want to code my own widget and integrate it inside the left panel (FORM ELEMENTS LIBRARY) of form-js.

**Description**

When I create a FormEditor, I want to be able to integrate my own custom widget like this :
`
new FormEditor({
            container: '#form-editor',
            customWidgets: [{...}, {...}]
            });
`
After that, we can see our own custom widget inside left panel and drag and drop it like your widgets.

This feature is very usefull for me because I need to display very specific widget for science porpose.

Thanks a lot !

**Comment by pinussilvestrus** [comment]
Hi, thanks for reaching out! Can you maybe update your issue description to follow [our issue templates](https://github.com/bpmn-io/form-js/issues/new/choose)? This way we get more information about what you actually need - and might be able to help you.

Thanks!

**Comment by VictorAITERA** [comment]
I updated it :) Hope you will understand what I'm asking

**Comment by nikku** [comment]
Thanks again for opening this issue and providing additional details regaring your use-case. Do you use form-js standalone or as part of a Camunda installation?

**Comment by nikku** [comment]
Closing this issue for the moment.

We are not there yet but may be able to deliver custom elements in the future.
