### ISSUE TITLE
Form Fields "Number" and "Select" do not submit empty values

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#169]
__Describe the Bug__

Same as #54, but only Select and Number fields are affected.

When the content of an pre-filled `Number` or `Select` is deleted, the submit event does not contain the form field in the data Object.

![recording (20)](https://user-images.githubusercontent.com/21984219/132711835-d7d4970a-de8a-410c-bcc3-12fcd1413db4.gif)

__Steps to Reproduce__

1. Open the Code-Sandbox: https://codesandbox.io/s/thirsty-dream-vh43x?file=/src/index.js
2. remove all pre-filled content
3. click submit

The submit only contains `field_0`.

__Expected Behavior__

All fields are dirty and I receive the changed value (`null` or `undefined`).

__Environment__

- Host (Browser/Node version), if applicable: Chrome
- OS: Linux
- Library version: 0.4.2

----

Related to [CAM-13333](https://jira.camunda.com/browse/CAM-13333)

**Comment by nikku** [comment]
To better understand your desired solution: You'd be fine with `null` as a value for _not set_?

**Comment by nikku** [comment]
For number `""` would be semantically incorrect.

**Comment by marstamm** [comment]
Yes, we are fine with `null` or `undefined`. The main problem is that the id of the field is not part of the keys in the results array.

**Comment by nikku** [comment]
> The main problem is that the id of the field is not part of the keys in the results array.

Could you elaborate on what you mean by that?

**Comment by marstamm** [comment]
We need a way to know which variables to update. In the example, `field_0`, `field_1` and `field_2`.

If they are not present in the result Objects, we have to assume that the Form does not reference them.

**Comment by marstamm** [comment]
So `null` as a value is fine, as we mainly missing the field key right now

**Comment by nikku** [comment]
That makes sense. Thank you for following up on.

**Comment by nikku** [comment]
Results of a sync with @philippfromme and @marstamm:

* A reasonable default behavior is to return `null` for fields that do not have an _empty_ default value (radio, select, number)
* Fields with an _empty_ default value (string, checkbox) return that value
* Disabled fields are not meant to be submitted by a user, hence these are not part of the submission output
* We shall always return a data view that is complete with regards to all fields: If form fields with keys `a`, `b` and `c` are editable to a users each of the keys must be present in the submission output, regardless of whether the field got touched or not.

I'll attempt to update https://github.com/bpmn-io/form-js/pull/177 to match that behavior.
