### ISSUE TITLE
BPMN.IO logo covers form fields

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#17]
__Describe the Bug__

In cases where the form has no empty space on the bottom right corner the logo might cover fields

<img src="https://user-images.githubusercontent.com/1022916/109154745-042c0100-776f-11eb-9941-f26d4dab2d29.png" width="600">

__Steps to Reproduce__

Create a form schema with only 1 column, 1 or more fields and no submit/reset buttons

__Expected Behavior__

The logo should never cover any field or button

__Environment__

- Host: Firefox 86
- OS: Arch
- Library version: 0.0.5

**Comment by nikku** [comment]
We are open for suggestions where the logo could be placed better.

As a workaround for you you could consider to give the form extra space on the bottom.

**Comment by vsgoulart** [comment]
> We are open for suggestions where the logo could be placed better.

An option is to allow it to cover the fields, but show the logo to the user on the modeller so the user could model the form around the logo

> As a workaround for you you could consider to give the form extra space on the bottom.

Yeah, I did that but I'm not sure if it's a good solution on the long run because you might change the rendered HTML structure and class names, no? Or you think this is unlikely to happen after the first stable release?
