### ISSUE TITLE
Improve editor element selection and keyboard navigation

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#173]
__Is your feature request related to a problem? Please describe__

The form editor at this stage is not keyboard aware: While there is a visual selection that selection does not confirm to the actual (browser) selection. Tabbing with the keyboard focuses embedded links rather than the actual form fields.

__Describe the solution you'd like__

Improve accessibility by better integrating with native browser focus handling.

* [ ] Selection on the canvas confirms with the keyboard selection
* [ ] Navigation between form elements is possible via tabbing

__Describe alternatives you've considered__

Ignore this topic.

__Additional context__

This screencapture shows the current state of keyboard navigation:

![capture bOICWW_optimized](https://user-images.githubusercontent.com/58601/133254651-c72be077-cbd5-47cd-b463-3d32bcc39b0e.gif)

**Comment by 2manoj1** [comment]
Are form-js support keyboard - On Select remove form component by pressing delete key?

**Comment by pinussilvestrus** [comment]
We improved a lot via https://github.com/bpmn-io/form-js/pull/634 (navigation and selection via keyboard). Let's close this one and wait for feedback.
