### ISSUE TITLE
Disable editing of a form field

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/form-js#181]
__Is your feature request related to a problem? Please describe__

As a form designer I would like to show some form fields without editing.

__Describe the solution you'd like__

Make a form field readonly or disabled. As is seems to be supported by the library (according to this closed issue: https://github.com/bpmn-io/form-js/issues/6), I want to have a checkbox in the UI for this.

__Describe alternatives you've considered__

nothing

__Additional context__

**Comment by nikku** [comment]
Good point. Thanks for opening this issue.

**Comment by ingorichtsmeier** [comment]
Do you see a chance to get it in Camunda 7.16 Release?

**Comment by AyoubBoulahtar** [comment]
Is this still open ?
