### ISSUE TITLE
Add support for DaisyUI

### ISSUE THREAD

**Issue by Rednas83** [bpmn-io/form-js#184]
__Is your feature request related to a problem? Please describe__

I am loving the editor but I think  there should be much more input types then the current 7 types.

__Describe the solution you'd like__

Perhaps integrate a library like https://daisyui.com/ to add more types?

__Describe alternatives you've considered__

Is it possible to extend the library with custom/personal types?

__Additional context__

None

**Comment by philippfromme** [comment]
First of all, we have issue templates for a reason. Please use them next time you create an issue: https://github.com/bpmn-io/form-js/issues/new?assignees=&labels=enhancement&template=FEATURE_REQUEST.md

You can easily change the appearance of forms and the form editor using CSS. Supporting third-party UI libraries is currently out of scope. I don't see this happening anytime soon.

**Comment by Rednas83** [comment]
@philippfromme I updated the issue according to the template.

**Comment by philippfromme** [comment]
We are not going to integrate a third-party component library. What is possible but not documented at the moment is adding your own custom form fields. Please bear us, we're going to document this soon and add an example.
