### ISSUE TITLE
Checkbox should submit "false" if it is required and not changed

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#190]
__Describe the Bug__

When I have a Schema that has a checkbox as required and I want to submit it with a "false", I get an error "Field is required.". I have to select and unselect it to submit.

![recording (33)](https://user-images.githubusercontent.com/21984219/138466268-5d16795c-adb2-4e24-b2b5-1d48e3484c13.gif)

__Steps to Reproduce__

1. open https://codesandbox.io/s/young-shadow-m4c44?file=/src/index.js
2. Click submit
3. an error is shown

__Expected Behavior__

A required Checkbox is always valid and submits its value.

__Alternatives__
A Checkbox always submits its value, no matter if it is required or not
This is similar to the discussion around https://github.com/bpmn-io/form-js/issues/169#issuecomment-921655453, which would solve this issue as well

__Environment__

- Host (Browser/Node version), if applicable: Chrome 94
- OS: Linux
- Library version: 0.5.1

---

Related to [SUPPORT-12033](https://jira.camunda.com/browse/SUPPORT-12033)

Related to https://github.com/bpmn-io/form-js/issues/169.

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/form-js/pull/210.
