### ISSUE TITLE
Be able to specify a default value for form controls

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#191]
__Is your feature request related to a problem? Please describe__

In some cases users would want to specify default values for a form in the form schema so that the value automatically ends up in the submission result. This is not the case at the moment and be unexpected for users (cf. https://github.com/bpmn-io/form-js/issues/190).

__Describe the solution you'd like__

* [x] As a user I am able to specify default values for input fields via the editor
* [x] The default value is serialized as `defaultValue` in a form item definition
* [x] In the absence of input data provided to the form default values are used to pre-fill the form
* [x] On submission default values are submitted like dirty fields

__Describe alternatives you've considered__

Keep things as is. If a user requires a default value for an input she must input that one via data into the form.

__Additional context__

Related to https://github.com/bpmn-io/form-js/issues/190

**Comment by Fredxingxing** [comment]
idea 1:
in editor,when check the "Required" checkbox, we can add an input behind it, which we can provide default values to pre-fill form,but users can edit it.
![image](https://user-images.githubusercontent.com/33107804/139810205-4285a86c-a154-4087-a0fa-603d9ede2cec.png)

idea 2:
or we can add it default value just in default data, something like this [{
  type:'checkbox',
  key:'sex',
  defaultValue:false, // check just use false
  validate: {
        "required": true
  }
},{
  type:'input',
  key:'name',
  defaultValue:'name', // when is input,just use key value to pre-fill
  validate: {
        "required": true
  }
},]

**Comment by nikku** [comment]
@Fredxingxing I like your suggestions. We'll consider them once we tackle this issue.

**Comment by Fredxingxing** [comment]
> @Fredxingxing I like your suggestions. We'll consider them once we tackle this issue.

is there any task which fresh man can contrubute ?  🙋‍♂️

**Comment by nikku** [comment]
You could go ahead and contribute it.

**Comment by Fredxingxing** [comment]
> You could go ahead and contribute it.

got it 👌

**Comment by nikku** [comment]
Some more things in the back of my head to be validated on :+1: 

We should clearly distinguish required and defaultValue. We should allow users to specify a default value for all fields. 

:five: We need to find a strategy to deal with null data being put into the form. Is null treated as value being present ? Likely not.

We should ultimately set defaultValue=false for checkboxes to prevent bugs like https://github.com/bpmn-io/form-js/issues/190.

We should make sure that users are still able to remove a value, even though a default value is present. Does that conflict with :five:?

**Comment by philippfromme** [comment]
> We should ultimately set defaultValue=false for checkboxes to prevent bugs like #190.

This bug will be fixed by https://github.com/bpmn-io/form-js/pull/210. If there is a boolean form field (that is not disabled) data will always be submitted. A boolean form field can never be empty.

**Comment by nikku** [comment]
> I'd assume that when importing a form if there is no value for a form field the default value will be used.

Exactly. If `author` is `Jon Doe` and not `author` data is required, `Jon Doe` appears as an input (and is being submitted).

**Comment by philippfromme** [comment]
So a field can have `defaultValue` or `validate: { required: true }` or both. 👍🏻 No clashes.
