### ISSUE TITLE
Build a form with Text Area(s)

### ISSUE THREAD

**Issue by ingorichtsmeier** [bpmn-io/form-js#194]
__Is your feature request related to a problem? Please describe__

As a form modeler I would like to add a text area to enter a larger text that didn't fit into a single line.

__Describe the solution you'd like__

Add a Text Area to the pallette that can be dropped on the canvas. It should contain a number of rows to control the height of the text area.

__Describe alternatives you've considered__

Reuse the Text Field and just add a configuration for a number of lines.

__Additional context__

Eventually it should contain the features of this element: https://docs.camunda.org/manual/7.16/reference/forms/embedded-forms/controls/textarea/

**Comment by nikku** [comment]
Thanks for opening this issue. Makes sense.

Moving it to our backlog for the time being!

**Comment by pinussilvestrus** [comment]
This is closed via https://github.com/bpmn-io/form-js/issues/283.
