### ISSUE TITLE
Support scalable (1.000 items +) multi-select component

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/form-js#198]
__Is your feature request related to a problem? Please describe__

As a form design I can model a component which can have `n` options, where the later form-user is able to select `m` (`0<=m<=n`) entries. 
The component is able to scope with significant options (e.g., 1.000 items)

__Describe the solution you'd like__

Consider:
* Get options either via
  * Form Data (requires https://github.com/bpmn-io/form-js/issues/197)
  * External source / dynamically added via custom JS (see https://github.com/bpmn-io/form-js/issues/199)
* Scale as performance
* Scale as UX 
  * allow to view the 1.000items +
  * allow to filter
  * allow to type-ahead

__Describe alternatives you've considered__

n/a

__Additional context__

Raised as part of SUPPORT-12025 interaction

**Comment by nikku** [comment]
How are the `n` options represented? Encoded in the form definition? Fetched via a remote source?

**Comment by MaxTru** [comment]
> How are the `n` options represented? Encoded in the form definition? Fetched via a remote source? Fet into the diagram as a variable?

Via Form Data. So indeed this issue here would require https://github.com/bpmn-io/form-js/issues/197 first. I update the issue description.

**Comment by nikku** [comment]
Makes sense. Moving to `backlog`.

**Comment by Skaiir** [comment]
WIP Tag List can be found here: https://github.com/bpmn-io/form-js/commit/cc31772677ea39c6f6504133a11fb254263c378a

Definitely am looking forward to some input on multiple aspects.

To test, using the playground should be easiest, this can be done via `npm run start:playground`
The tag list is the 3rd checkbox in the toolbar (we don't have an icon yet).

The second checkbox is the check list (or multi checkbox), feel free to have a look there as well if you'd like.

Firstly, issues I'm aware of:
- Up and down key nav doesn't support holding, I feel like this is a pretty trivial implementation but I've been wrong before so sorry not in this preview
- Up and down keys affect the cursor inside of the input box
- If the input state doesn't match any of the available values, it's still passed to the output state, the behavior we would want here isn't defined really.
- Accessibility needs to be checked and handled properly, this will be a later consideration.

Some things I'm still deliberating on:
- Do we need more feedback on the delete buttons for tags (currently there is none)
- Should pressing backspace when the filter is empty delete the latest tag?
- Do we need a "clear all" button

Particular areas of interest with regards to feedback:
- Interaction between keyboard and mouse selection. I've tried to make this as good as humanly possible. Please have a play around with moving the mouse, and selecting values via keyboard simultaneously. Pressing up and down keys while the mouse is over the dropdown, scrolling without moving the mouse, ect.. ect.. I think I have handled every possible case here. 
- General look and feel

**Comment by marstamm** [comment]
Some feedback from my side about the prototype:


On Linux, the "remove" Icon is not rendered:
![image](https://user-images.githubusercontent.com/21984219/166903585-07377fd4-31bd-4e77-becb-a7b432a03f09.png)

Generally, I like the mouse and keyboard interaction. When I type to search for an entry and select it using "return", I would expect the input to be cleared so I can start searching for the next one directly:
![Recording 2022-05-05 at 12 04 13](https://user-images.githubusercontent.com/21984219/166903520-38d402ad-07ad-421f-9a85-c48a7bc937a0.gif)

**Comment by pinussilvestrus** [comment]
**Some first feedback from my side**

Overall: great stuff and a good base to iterate over 👏 

* After I selected an option, the input value should be erased
* I'd expect that pressing ESC immediately closes the search results
* I see there is a closing and opening animation. Personally, it creates a bit too much noise visually. Do we have this in any other component?
* All options are displayed on focus. I don't know whether I would expect that, but only displaying options when there is something typed
* Keyboard navigation:
  * already works smoothly ❤️ 
  * holding the up/down key does not work to navigate faster
  * the start and end of the list are blocking, e.g. when pressing "up" on the top, it does not go to the bottom (what I'd expect)
  * for reference here is the navigation behavior we have in the Camunda Modeler for overlay lists
 
![Kapture 2022-05-05 at 12 12 39](https://user-images.githubusercontent.com/9433996/166903767-fa6df805-dd0a-40ce-8bcf-983725b6f4ba.gif)
 
> Should pressing backspace when the filter is empty delete the latest tag? 

I'd say yes! As I immediately stumbled over this and was expecting exactly this

> Do we need a "clear all" button

If removing via backspace works, I'd not need it.

**Comment by MaxTru** [comment]
In general I subscribe to @pinussilvestrus and @marstamm feedback.

* High level UX pattern is nice and good! I would not change.
* On my Arch linux system the `x` do render
* You state that we don't have an icon for the palette yet - I propose to create an issue for design to deliver this and request that explicitly. Otherwise we might run into a state where we have to wait for this. We can request this via our next planning next Tuesday.
* I would remove the animation (as @pinussilvestrus suggested). Also notice that for me the animation shows a scroll bar for some short period of time.
* Backspace should remove the last value. (+1 to @pinussilvestrus comment, this would also remove the need for `remove all`)
* IMO the value dropdown should hover over the following elements, and not push them down (e.g., same as normal dropdown select)

**Comment by pinussilvestrus** [comment]
> Accessibility needs to be checked and handled properly, this will be a later consideration.

I did a quick automatic a11y check via [`axe`](https://github.com/dequelabs/axe-core) (a tool we already use in other projects, e.g. `properties-panel`). I find [this tool pretty helpful](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd) to make quick tests.

* It reports that the select box in the closed state is not scrollable ([`region`](https://dequeuniversity.com/rules/axe/4.4/region?application=AxeChrome)) - which makes sense? However, that might be a hint that there is something missing (e.g., the list is not completely hidden for screen readers)
* It has a ["missing landmark (role)"](https://dequeuniversity.com/rules/axe/4.4/region?application=AxeChrome) violation, but that's a general issue for all `.fjs-form-field` wrappers. 

Not in the scope of this issue, but maybe something we should consider: adding similar unit tests as we have in the properties panel (e.g. [ToggleSwitch](https://github.com/bpmn-io/properties-panel/blob/main/test/spec/components/ToggleSwitch.spec.js#L257)).

**Comment by andreasgeier** [comment]
> Do we need more feedback on the delete buttons for tags (currently there is none)

Yes, we should add a hover state

> Should pressing backspace when the filter is empty delete the latest tag

Yes. Also, it should be possible to long press to delete all entries

> Do we need a "clear all" button

I'd prefer backspace as basic option. A button would be an advancement and could be added now, later, or never.

> On Linux, the "remove" Icon is not rendered

Same on latest Mac OS, latest Chrome

> When I type to search for an entry and select it using "return", I would expect the input to be cleared so I can start searching for the next one directly

+1

> I'd expect that pressing ESC immediately closes the search results

I understand that expectation. It would work like a html select component. But when we close the dropdown on ESC (while taglist still has focus/is active), we have to reopen it on typing or clicking. Without a visible dropdown list, the component is useless. I'd see this as nice-to-have but not as important.

> I see there is a closing and opening animation. Personally, it creates a bit too much noise visually. Do we have this in any other component?

All of our user interfaces almost never use animations. I would remove it.

> All options are displayed on focus. I don't know whether I would expect that, but only displaying options when there is something typed

I suggested this behavior. Otherwise, it wouldn't be possible to see all available entries, particularly for shorter lists. See example from Console below: how annyoing it would be if you can't see the available roles! 

> holding the up/down key does not work to navigate faster

+1, related to backspace (my second comment in this list)

> the value dropdown should hover over the following elements, and not push them down (e.g., same as normal dropdown select)

+1

Plus,

It is confusing that selected entries are added to the collection in the same order as they appear in the list. I'd expect that they are placed at the cursor/search string position (at the end of the list). With many items already selected, I sometimes overlooked the add action because the selected item was added in the first line while my cursor (and search entry) was in line 3.

We should add a "no result found" and a "all items selected" state for the dropdown.

We should remove the search string on focus out. Currently, it remains in the field next to the tags and might be confused as valid input. 

<br>

#### Examples from console taglist

hover effect for close button:

![Screen Shot 2022-05-05 at 14 17 29](https://user-images.githubusercontent.com/938244/166921230-83575c3e-3b8a-45f9-abfe-4208bdc0440c.png)

clear all button:

![Screen Shot 2022-05-05 at 14 16 16](https://user-images.githubusercontent.com/938244/166921045-1377b99f-b2c2-4f31-996d-ee8bc80b7995.png)

**Comment by nikku** [comment]
:+1: on @andreasgeier comment. Should not be too hard to accomplish.

**Comment by andreasgeier** [comment]
@Skaiir I saw the discussion around the remove icon on Slack. I assume you could reuse the close tab icon, it should have the right size.

**Comment by andreasgeier** [comment]
@MaxTru 

> You state that we don't have an icon for the palette yet - I propose to create an issue for design to deliver this and request that explicitly.

I put that on my to-do list already. Is my impression correct that we do not only need an icon for a taglist component but also we'll have a checkbox group component in addition to a (single) checkbox? So I'd need to deliver two icons.

**Comment by MaxTru** [comment]
> @MaxTru
> 
> > You state that we don't have an icon for the palette yet - I propose to create an issue for design to deliver this and request that explicitly.
> 
> I put that on my to-do list already. Is my impression correct that we do not only need an icon for a taglist component but also we'll have a checkbox group component in addition to a (single) checkbox? So I'd need to deliver two icons.

Super - thanks. 

Yes - it is "taglist" and "multi-select checkbox" (in addition to the existing single select checkbox) (=> as you said :-) )

**Comment by Skaiir** [comment]
Commit: https://github.com/bpmn-io/form-js/commit/d3da59eebf60cb811c0e425b0563c3758d3860a0
Branch: https://github.com/bpmn-io/form-js/tree/taglist-prototype

**Comment by Skaiir** [comment]
@MaxTru Regarding the navigation, this would be doable but this does add complexity in the React code, and also raises a few UX questions that I don't yet have the answers to. In any case yes it's something I'm keeping in mind, but for now being able to cancel just the last entry should be enough for users to correct any mistakes. If they really need to remove one item specifically, the mouse still offers that option. 

Regarding the PR, I still need to write tests for this, I also would like to have a quick session with Andi for last minute adjustments, in case those end up being functional. I'll PR checklists right now, and if I'm fast I should be able to have a PR for this mid day.

**Comment by nikku** [comment]
@Skaiir consider creating a draft PR for features you work on.

Works well in our process (and allows do easily document how to try out things, too).

I.e. in your case the following allows everyone to try out the changes easily.

```
npx @bpmn-io/sr -c 'npm run start:playground' bpmn-io/form-js#taglist-prototype
```

----

What is missing (no in depth code review, just another UX review):

* icons for taglist and checklist
* search shall be case-insensitive (I cannot search for `value 5` when `Value 5` is a labeled item

What you could consider: 

* Dimm down tag colors / reduce prominence of `x` (cf. screens posted above). Would be great if @andreasgeier could provide some feedback here / help polish up our colors.

**Comment by andreasgeier** [comment]
> Would be great if @andreasgeier could provide some feedback here / help finalize the UI.

This is already planned for Monday after spring cleaning. Will also provide the icon until then.

**Comment by andreasgeier** [comment]
> search shall be case-insensitive (I cannot search for value 5 when Value 5 is a labeled item

When I look at the recording it is already case insensitive. The problem seems to be the space character, I guess?

**Comment by pinussilvestrus** [comment]
> @Skaiir consider creating a _draft PR_ for features you work on. This is something we shall do as early as possible, and document how to try things out there / discuss the feature there (in terms of focus). Also, this works well in our process.

I'd like to second this. Are you also aiming for a (draft) PR for the ["simple" multi select](https://github.com/bpmn-io/form-js/issues/196)? It would help us a lot to focus and give detailed feedback on particular items 👍

**Comment by Skaiir** [comment]
@pinussilvestrus There's a 'draft' PR for it now. Although it can be treated like a full on PR, I've just kept it in draft as we're lacking the icon and hence it's not a merge-able implementation.
