### ISSUE TITLE
Be Able to Add Custom Properties (Key/Value) through Properties Panel

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/form-js#199]
__Is your feature request related to a problem? Please describe__

Allow to add custom properties (key/value) via propertiesPanel.

__Describe the solution you'd like__

**What**
In the form-js editor, in the properties panel allow to add custom properties (key value). 
Persist these custom properties in the resulting `form.json`.

**Example for form.json**
```
{
  "schemaVersion": 2,
  "components": [
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field_0ybooxt",
      "key": "field1",
      "customProperties": 
        {
           "key1": "value1",
           "key2": "value2"
        }
    },
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field_09h5omo",
      "key": "field2"
    }
  ],
  "type": "default",
  "id": "Form_0aj08qi"
}
```

**Why**
These additionalProperties can be used by custom tasklist implementations to customize the form.
For example the customer has a use-case, where he/she populates a dropDown based on an external API. To know which custom API to call, the additionalProperties are used.

__Describe alternatives you've considered__

Workaround exists: add properties via JSON tab. Customer reported that: `this is not a suitable solution for business users, also prone to errors`

__Additional context__

See https://jira.camunda.com/browse/SUPPORT-11774

**Comment by Fredxingxing** [comment]
### idea:

add a custom panel like this 

![image](https://user-images.githubusercontent.com/33107804/140852737-58fca405-03b9-44d0-b0f9-8f6f3c47bca2.png)

this allow user to add arrays of keys and values.

#### in code, we need a new components like CustomValuesPanel, in it we maintain a array and on items change, use editform(field,key,value) to set or change value in the form json.

### Q1:   i think custom values need unique id like this
```
{
      "values": [
        {
          "id":1, // or something just let react diff work
          "label": "Value",
          "value": "value"
        }
      ],
      "label": "Radio",
      "type": "radio",
      "id": "Field_1gipxhe",
      "key": "field_0uckw7t"
    }
```

### Q2 : is there any api support from editform to delete obj's key?

**Comment by MaxTru** [comment]
Hi @Fredxingxing ,
thanks for your inputs.

Regarding:
> Q1: i think custom values need unique id or key like this
>```
>{
>      "values": [
>        {
>          "id":1, // or something just let react diff work
>          "label": "Value",
>          "value": "value"
>        }
>      ],
>      "label": "Radio",
>      "type": "radio",
>      "id": "Field_1gipxhe",
>      "key": "field_0uckw7t"
>    }
>```

How does this relate to this issue? From my understanding, this is not related. So to have a conversation about it, could you please create a seperate issue?

> Q2 : is there any api support from editform to delete obj's key?
Could you please elaborate more on the use case? Does this relate to the custom properties discussed as part of this issue?

**Comment by Fredxingxing** [comment]
Hello @MaxTru ,
Q1: I just mean use [keys](https://reactjs.org/docs/lists-and-keys.html#keys) to list ,cause user may enter some data like this: 
```
"values": [
       {
         "label": "onwer",
         "value": "1"
       },
      {
         "label": "onwer",
         "value": "2"
       }
     ],
// or 
"values": [
       {
         "label": "user",
         "value": "1"
       },
      {
         "label": "onwer",
         "value": "1"
       }
     ],
```
so i suggest to use some id or key is better.

Q2: when user clear values in 'values' ,  is it form.data.json just like this?
```
{
     "values":  undefined,
     "label": "Radio",
     "type": "radio",
     "id": "Field_1gipxhe",
     "key": "field_0uckw7t"
}
```

so, key 'values' still remain in the data, i mean is there have some API like editeForm.delete to wipe the key and value out.

**Comment by nikku** [comment]
To map it into our BPMN world this would mirror what we got as generic extension properties in the BPMN properties panel, correct? 

![capture chyxSR_optimized](https://user-images.githubusercontent.com/58601/143249791-b29963a1-03fe-4b27-983d-12a85ded2221.gif)

---

I think it makes sense to consider such generic extension point. Especially once we think along the lines of creating custom components. These would do more things than what we do right now, based on meta-data we cannot anticipate.

**Comment by smbea** [comment]
Since we already have this concept of generic extension properties in the BPMN properties panel, we can reuse the design concept (which is similar to the one sketched) for these custom properties (cc @andreasgeier)

**Comment by andreasgeier** [comment]
We don’t have the old structure of extension properties anywhere in the Form properties panel and although it is an intermediate solution (assuming it will be replaced with the new panel soon) I would not introduce new patterns. 

I would suggest using the existing list group that is used for select and radio:

![Screen Shot 2022-02-10 at 11 25 05](https://user-images.githubusercontent.com/938244/153388144-ef8a34a5-1222-424c-8a73-247dc86cdd3f.png)

**Comment by MaxTru** [comment]
Could we please agree how the custom properties will be persisted in the JSON?

@nikku or @philippfromme would appreciate your input

For example:
```
{
  "schemaVersion": 2,
  "components": [
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field_0ybooxt",
      "key": "field1",
      "customProperties": 
        {
           "key1": "value1",
           "key2": "value2"
        }
    },
    {
      "label": "Text Field",
      "type": "textfield",
      "id": "Field_09h5omo",
      "key": "field2"
    }
  ],
  "type": "default",
  "id": "Form_0aj08qi"
}
```

**Comment by philippfromme** [comment]
I'd simply call it `properties`:

```json
{
  "schemaVersion": 2,
  "components": [
    {
      "label": "Name",
      "type": "textfield",
      "id": "Field_1",
      "key": "name",
      "properties": {
        "foo": "bar"
      }
    }
  ],
  "type": "default",
  "id": "Form_1"
}
```

What do you think?

**Comment by smbea** [comment]
Seems good to me. Does this mean we also label the group in the panel as "Properties"?

**Comment by nikku** [comment]
I'd not call it `VAlues` for sure.

Settle down on something that clearly states what it does.

If it is "attaching custom properties  to a form field", call it "Properties" or "Custom Properties" or "Extension Properties".

**Comment by nikku** [comment]
Custom implies _optional_ to me which is something important.

Adding the new section shall not negatively impact users using the panel (i.e. suggest that entering something is mandatory).

**Comment by smbea** [comment]
The structure  of `Values` is an array of objects, which allows duplicates:

```json
"values": [
  {
    "label": "somevalue",
    "value": "1"
  },
  {
    "label": "somevalue",
    "value": "2"
  }
]
```

And the placeholder values are added like so:

https://user-images.githubusercontent.com/25825387/153872676-27f18b5d-019a-46f6-ac82-91e72a307602.mov

With the proposed JSON schema of `properties: {"key":"value"}`, we can't have duplicate custom properties keys. For this to make sense, I believe it requires **input validation for the key field**. We would also need another way of adding the placeholder values - if we click twice in 'add' without changing the key, we will try to add a duplicate key (which will fail). One way around this is having a counter and adding "Key 1", "Key 2",...

Any opinions? @MaxTru @philippfromme @nikku
