### ISSUE TITLE
Support nested lists

### ISSUE THREAD

**Issue by tmetzke** [bpmn-io/form-js#204]
__Is your feature request related to a problem? Please describe__

I would like to use nested lists in the markdown of a static text element.

In basic markdown, I would write something like

```
1. First item
2. Second item
3. Third item
    1. Indented item
    2. Indented item
4. Fourth item
```

By doing so, the indented items will be interpreted as code blocks.

__Describe the solution you'd like__

I would like the indented items to be interpreted as such instead of being interpreted as code blocks.

__Describe alternatives you've considered__

* I tried using 2 spaces and 3 spaces instead of 4 spaces, that does not work as well.
* I can use HTML in the static text which is a functioning workaround.

__Additional context__

I attached an example form with [form_1.zip](https://github.com/bpmn-io/form-js/files/7735752/form_1.zip)

**Comment by MaxTru** [comment]
I encountered this issue as well. Moving to backlog. cc @philippfromme

**Comment by MaxTru** [comment]
* Reason is a missing feature in snarkdown: https://github.com/developit/snarkdown/issues/104
* Workaround available (but hacky):
```
- hey
- there
- delilah<ul>
- what's
- it 
- like
</ul>
- in <ul>
- new
- york
- city
</ul>
```

**Comment by Skaiir** [comment]
Closing as this was fixed with the migration to GitHub flavored markdown.
