### ISSUE TITLE
Support markdown tables in text

### ISSUE THREAD

**Issue by korthout** [bpmn-io/form-js#205]
__Is your feature request related to a problem? Please describe__

Support markdown tables in text. 🥇 

__Describe the solution you'd like__

I want to be able to add a markdown table, like this: 👍 

```md
| a | b |
|---|---|
| 1 | 2 |
```

__Describe alternatives you've considered__

I tried using html, it did not work 😢 

__Additional context__

Tables are great in tasks 💯

**Comment by nikku** [comment]
Could you please share what you tried? This may be a case of "we won't support markdown here". But I'd assume tables should work.

**Comment by korthout** [comment]
I don't have the real example anymore, but I wanted to display a table in the text block of a task in Tasklist. This was because the task isn't a straightforward 'do this', but what needs to be done depends on the situation. You could consider that this is bad modeling, and the process should orchestrate that, but often modeling is an iterative process and we start with a simple process containing some complicated large tasks that can later be replaced by more fine grained and automated tasks. 

To help you out with a failing example:
```
{
  "schemaVersion": 2,
  "components": [
    {
      "text": "# Text\n\n| a | b |\n|---|---|\n| 1 | 2 |",
      "type": "text",
      "id": "Field_1ibtpz1"
    }
  ],
  "type": "default",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "1.2",
  "id": "Form_0acbhin"
}
```

**Comment by nikku** [comment]
Thanks. We'll look into it and investigate missing HTML table support, too.

One of both shall be supported, I believe.

**Comment by Skaiir** [comment]
We've switched over to GHM, which should have enabled these but I notice they are being filtered out. My guess is that it's broken due to the HTML sanitizer. Will investigate.

**Comment by Skaiir** [comment]
This should be fixed in the referencing commit, expect it in the next version of form-js (we'll probably do a release some time this week to include a bunch of cleanups) @korthout
