### ISSUE TITLE
Weird behaviour of Checkboxes in Forms 

### ISSUE THREAD

**Issue by Hafflgav** [bpmn-io/form-js#206]
__Describe the Bug__

When adding a checkbox to a form you can define a name mapping to the process variable. When submitting a task without checking the box it occurs that the process variable is non existent - therefore the condition in the gateway fails. 
This issue was discovered from multiple students of the HU Berlin and was their "biggest" problem throughout the evaluation of Camunda Cloud. 

__Steps to Reproduce__

1. Create a form with a checkbox 
2. Add a variable mapping to the checkbox 
3. Attach the form to a user task within a process and a conditional event based on the output of the user task  
4. Execute the process without checking the checkbox 
5. Error occurs 

__Expected Behavior__

I would expect that an unchecked checkbox equals "false" or "null". The presence of a variable / or not doesn't seem intuitive to me. 

__Environment__

- Host Chrome version 96.0.4664.110
- OS: macOS Monterey

**Comment by MaxTru** [comment]
Thanks for reporting.

This indeed is a big blocker.

However, this was also already reported via https://github.com/bpmn-io/form-js/issues/190.

We plan to fix this within this quarter by implementing https://github.com/bpmn-io/form-js/issues/191.

Hence I am closing this issue as duplicate. Please feel free to re-open in case I missed something.
