### ISSUE TITLE
Select Box Value looses Focus 

### ISSUE THREAD

**Issue by Hafflgav** [bpmn-io/form-js#207]
__Describe the Bug__
When setting a value of a Select Box in a Camunda Cloud Form the "Value" field looses focus way to quickly. 
When not typing it stops focussing within a second. 

__Steps to Reproduce__
1. Add a Select Box to the Form 
2. Try to add a "Value -> Value" 
3. See how quickly the input looses focus

See attached video:
[](https://user-images.githubusercontent.com/30292227/148750627-bd6458b6-b6cc-4fb3-bc50-6b078ccbcf7e.mov)

https://user-images.githubusercontent.com/30292227/148751316-57537ced-91b3-4282-b8a4-b0f8d0a1bafa.mov

__Expected Behavior__
This Field doesn't loose focus at all.  

__Environment__
- Host Chrome 96.0.4664.110
- OS: macOS Monterey

**Comment by MaxTru** [comment]
I can reproduce. Moving this to backlog and marking for spring cleaning

**Comment by philippfromme** [comment]
Closed by https://github.com/bpmn-io/form-js/pull/211.
