### ISSUE TITLE
Scrolling changes Values in Number Boxes 

### ISSUE THREAD

**Issue by Hafflgav** [bpmn-io/form-js#208]
__Is your feature request related to a problem? Please describe__
After a group of students from HU Berlin tried out Camunda Cloud they noticed an inconvenience in regards to the number boxes. It happened quite often to them that they added a number manually and while scrolling down manipulated that value without knowing. 

__Describe the solution you'd like__
It would be awesome if that you couldn't change a value in the number box by scrolling 

__Additional context__
See attached video below

https://user-images.githubusercontent.com/30292227/148754179-03c4b8f8-6486-48bd-b425-3fb9b00d2410.mov

**Comment by andreasgeier** [comment]
This is unexpected behavior and not standard behavior of form-js, see the recording below. 

Numbers can be changed by keyboard arrows up/down, by clicking on the arrows of the input field, but it shouldn't react on scrolling (trackpad, mouse wheel).

https://user-images.githubusercontent.com/938244/149107460-93022227-6a53-4b75-8597-ae2e6034590e.mov

**Comment by andreasgeier** [comment]
I can reproduce the behavior in Cloud Tasklist. So I assume it is the behavior of the number input component of the tasklist app.

@MaxTru pls take over to ensure the bug is handled there.

**Comment by MaxTru** [comment]
This bug originates in taskList.

Please follow along https://github.com/camunda-cloud/tasklist/issues/1565.

Closing

**Comment by Hafflgav** [comment]
Awesome! Thanks for linking it to Tasklist :)
