### ISSUE TITLE
Buttons Should Not Have `key` Property

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#212]
__Describe the Bug__

Buttons have a `key` property that isn't used.

```json
{
  "key": "submit",
  "label": "Submit",
  "type": "button"
},
{
  "action": "reset",
  "key": "submit",
  "label": "Submit",
  "type": "button"
}
```

We currently have to work around this to avoid submitting data for buttons: https://github.com/bpmn-io/form-js/pull/210/files#diff-9f0268e4ce241c1b7c182fce6fff8d93a27c9a5db106c4366eb99def13de44bbR82

I think we should remove the `key` property unless we plan to use it to reference buttons e.g. for conditional rendering.

**Comment by nikku** [comment]
Regarding `key` we should keep in mind that submitting with multiple out comes is an actual thing. So which button I submit with (thus potentially adding a value) is a use-case I can imagine.

=> Save vs. Cancel button.

**Comment by philippfromme** [comment]
Not sure how this would work as the submission doesn't include any information about the button that was used to submit. 🤔

**Comment by nikku** [comment]
Consider reading [MDN docs on button naming and value](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) for further context. Submitting a form via a particular button may submit a value with the form, indicating which button was used to submit.

**Comment by philippfromme** [comment]
🤯

**Comment by philippfromme** [comment]
So using an HTML form a button `<button name="type" value="cancel" />` attribute would show up as `type=cancel` when submitting the form.

In that case, we'd have to treat buttons differently by not setting their value as we would for a text field for example but instead adding their value to the submitted data only.

I'd imagine it something like this:

```javascript
const data = {
  name: 'John Doe'
};

const schema = {
  "components": [
    {
      "key": "name",
      "type": "textfield"
    }.
    {
      "action": "submit",
      "label": "Cancel",
      "key": "cancel",
      "type": "button"
    },
    {
      "action": "submit",
      "label": "Submit",
      "key": "submit",
      "type": "button"
    }
  ],
  "type": "default"
}

const form = await createForm({
  container,
  data,
  schema
});

// user clicks "Cancel" ➡️ { name: "John Doe", cancel: "submit" }

// user clicks "Submit" ➡️ { name: "John Doe", submit: "submit" }
``` 

If the user decides to use buttons with a `key` property they'd have to make sure not to reuse these in the form.

**Comment by MaxTru** [comment]
@philippfromme and @nikku could you please either update (i.e. specify what is needed and move to backlog/ready) or close this issue?

**Comment by philippfromme** [comment]
I'll going to close this issue. I've created a follow-up issue: https://github.com/bpmn-io/form-js/issues/223. Since this is a low-priority issue I've added it to the backlog.
