### ISSUE TITLE
Adding a build and run section to the README to clarify building on Windows environments

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#214]
__Is your feature request related to a problem? Please describe__

CMD and PowerShell are, for some Windows developer, the main cli they use. However in the current state form-js cannot be built in either of these environments due to the "generate-types" script which cannot be executed there. There is no particular documentation which explains this and while it isn't a complicated workaround, it's a very early debugging experience for anybody just starting on this repo. 

__Describe the solution you'd like__

Adding a build and run section to the README, which would have a window specific subsection pointing people to use git bash, or hack the generate-types script if they really want to keep using cmd/powershell.

__Describe alternatives you've considered__

Creating an alternative script for execution on cmd/powershell

Uncertain if that's possible within npm but modifying generate-types so that it conditionally executes differently on cmd and powershell, the actual working alternative looks something like this (tested locally):

`"generate-types": "tsc --allowJs --skipLibCheck --declaration --emitDeclarationOnly --outDir dist\\types src\\index.js && copy src\\*.d.ts dist\\types",`

**Comment by nikku** [comment]
What is the issue on Windows specifically? Any error? If so, please share it.

Generally speaking, please use `decent POSIX compatible shell X` is something I'd prefer over we support all these special shells with (bigger) workarounds.

As an example, we document that boldly in the [Camunda Modeler build instructions](https://github.com/camunda/camunda-modeler#building-the-application).

**Comment by Skaiir** [comment]
Hey @nikku , so the error specifically is this:

```
[...]
@bpmn-io/form-js-viewer: 'cp' is not recognized as an internal or external command,
@bpmn-io/form-js-viewer: operable program or batch file.
@bpmn-io/form-js-viewer: npm ERR! code ELIFECYCLE
@bpmn-io/form-js-viewer: npm ERR! errno 1
@bpmn-io/form-js-viewer: npm ERR! @bpmn-io/form-js-viewer@0.5.1 generate-types: `tsc --allowJs --skipLibCheck --declaration --emitDeclarationOnly --outDir dist/types src/index.js && cp src/*.d.ts dist/types`
@bpmn-io/form-js-viewer: npm ERR! Exit status 1
@bpmn-io/form-js-viewer: npm ERR!
@bpmn-io/form-js-viewer: npm ERR! Failed at the @bpmn-io/form-js-viewer@0.5.1 generate-types script.
@bpmn-io/form-js-viewer: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@bpmn-io/form-js-viewer: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
@bpmn-io/form-js-viewer: npm ERR! A complete log of this run can be found in:
@bpmn-io/form-js-viewer: npm ERR!     C:\Users\Valentin Serra\AppData\Roaming\npm-cache\_logs\2022-01-17T07_56_15_796Z-debug.log
@bpmn-io/form-js-viewer: ERROR: "generate-types" exited with 1.
@bpmn-io/form-js-viewer: npm ERR! code ELIFECYCLE
@bpmn-io/form-js-viewer: npm ERR! errno 1
@bpmn-io/form-js-viewer: npm ERR! @bpmn-io/form-js-viewer@0.5.1 build: `run-p bundle generate-types`
@bpmn-io/form-js-viewer: npm ERR! Exit status 1
@bpmn-io/form-js-viewer: npm ERR!
@bpmn-io/form-js-viewer: npm ERR! Failed at the @bpmn-io/form-js-viewer@0.5.1 build script.
@bpmn-io/form-js-viewer: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
@bpmn-io/form-js-viewer: npm WARN Local package.json exists, but node_modules missing, did you mean to install?
@bpmn-io/form-js-viewer: npm ERR! A complete log of this run can be found in:
@bpmn-io/form-js-viewer: npm ERR!     C:\Users\Valentin Serra\AppData\Roaming\npm-cache\_logs\2022-01-17T07_56_15_834Z-debug.log
lerna ERR! npm run build exited 1 in '@bpmn-io/form-js-viewer'
[...]
```

The first line is the issue, basically cp isn't a command, also the paths are POSIX which causes trouble for non POSIX shells (which isn't in the error right now but will show up if you fix it). I agree that it is probably better to simply have documentation covering this instead of supporting every minor cli, much like how it is done in the camunda-modeler build instructions.

**Comment by nikku** [comment]
We should simply use a node wrapper around `cp` and we are good. Tagging this as spring cleaning.

If you want to follow up, you may check out other projects (camunda-modeler, dmn-js, bpmn-js, ...) if you find out how we copy in a cross-platform manner.
