### ISSUE TITLE
Preview Actual Instance of Form in Editor

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#215]
# Context

We currently show the preview (highlighted in red) in [a quite hacky way](https://github.com/bpmn-io/form-js/blob/master/packages/form-js-editor/src/render/components/FormEditor.js#L303). Things like showing the default value in the preview aren't possible without showing an actual instance of the viewer and importing the schema.

<img width="616" alt="brave_qm1xPxMDZf" src="https://user-images.githubusercontent.com/7633572/149760365-2ebb863e-22ab-43f3-b5c2-75292ac27115.png">

---

Related to https://github.com/bpmn-io/form-js/pull/213

**Comment by Skaiir** [comment]
I don't think this one is relevant anymore, @nikku feel free to reopen.
