### ISSUE TITLE
Release form-js v0.6.0

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#216]
__What should we do?__

Release form-js v0.6.0 which includes fixes required by the Camunda Platform team.

* [x] release form-js v0.6.0
* [x] https://github.com/bpmn-io/bpmn.io/issues/113
* [x] align with Camunda Platform team regarding
  * [x] the decision whether to release a Camunda Platform 7.16 patch or include form-js v0.6.0 only in Camunda Platform 7.17
  * [x] the question whether all issues are fixed

**Comment by philippfromme** [comment]
@marstamm form-js v0.6.0 is out and ready to be integrated: https://www.npmjs.com/package/@bpmn-io/form-js/v/0.6.0

**Comment by marstamm** [comment]
> the decision whether to release a Camunda Platform 7.16 patch or include form-js v0.6.0 only in Camunda Platform 7.17

We included it in a 7.16 patch release to fix a bug for a customer.

> the question whether all issues are fixed

All good from our side, but we can't say if it was the lastbug:tm: :wink:

**Comment by philippfromme** [comment]
🎉
