### ISSUE TITLE
Update demo.bpmn.io/form to v0.6.0

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#218]
__What should we do?__

Automatic update of demo.bpmn.io/form to v0.6.0 failed: https://github.com/bpmn-io/form-js/runs/4845807470?check_suite_focus=true

We should

* update manually
* investigate the failure

**Comment by nikku** [comment]
It seems like it actually worked. https://github.com/bpmn-io/bpmn-io-demo is updated and works on `master`.

I just found one rather inconvenient bug while integration testing: https://github.com/bpmn-io/form-js/issues/219

**Comment by nikku** [comment]
Created a bug regarding the update example post release steps: https://github.com/bpmn-io/form-js/issues/220.

**Comment by philippfromme** [comment]
Sorry, the I actually meant the example. 😓 Closing this.
