### ISSUE TITLE
`exporter` not being accounted for

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#219]
__Describe the Bug__

The `FormEditor` allows me to pass an exporter that should be serialized with every saved from.

However, due to the way [the export works](https://github.com/bpmn-io/form-js/blob/36ed8d250c0de3cf356a24efec3e8a9bbd7f08fc/packages/form-js-editor/src/FormEditor.js#L329) `exporter` is always overriden if it already exists on the diagram. 

__Steps to Reproduce__

1. Open an existing form on https://demo.bpmn.io/form/s/start
2. Export form
3. __See exporter shows 0.1.0 (pre-existing) rather than the new version (>= 0.5)__

__Expected Behavior__

Exporter is always set to the current form toolkits injected `exporter` property.

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: 0.5, 0.6

**Comment by nikku** [comment]
Can we patch release this?

**Comment by marstamm** [comment]
Will take care of the release
