### ISSUE TITLE
Support for legacy app in ES5 ?

### ISSUE THREAD

**Issue by keuss** [bpmn-io/form-js#233]
We need to use form-js library with Camuna BPM. Our app (legacy) in currently un AngularJS v1.8.2 **but in ES5 way**.

How can we use form-js ? Do you provide an ES5 dist bundle of the library ?

Thanks !

**Comment by nikku** [comment]
You can transpile form-js to ES5 using the appropriate build chains yourself, i.e. include it as part of your [babel configuration](https://babeljs.io/).
