### ISSUE TITLE
Garbage data is sent when submitting the forms generated by Camunda Cloud web modeler

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#234]
__Describe the Bug__

Forms created by the Camunda Cloud web modeler are seemly valid but when the forms are submitted garbage data is sent together with correct form values on the submit event.
It looks like this error was introduced by #210, I tested with versions before v0.6.0 and this didn't happen.
This also doesn't happen with schemas generated by the desktop version of the Camunda Modeler.

__Steps to Reproduce__

[CodeSandbox with reproduction](https://codesandbox.io/s/goofy-rumple-nj71h4?file=/src/index.js) (The schema was generated with the web modeler)

1. Click on the submit button
2. The data returned by the submit is:
```js
{
  "undefined": {
    "undefined": {},
    "field_17p2tpy": ""
  },
  "field_17p2tpy": ""
}
```

__Expected Behavior__

Only the object below should be sent:
```js
{
  "field_17p2tpy": ""
}
```

__Environment__

- Library version: v0.6.0 and above

**Comment by philippfromme** [comment]
Can you elaborate on how the schema was created? It contains internal properties (e.g. `_parent`) that aren't exported when calling `formEditor.saveSchema`. Importing the schema and exporting it using the form editor fixes the schema: https://codesandbox.io/s/form-js-issue-1rg1dp I suspect that you might be using the `changed` event to get the latest schema when working with the editor. Unfortunately the `schema` in that event is not the exported schema which is not documented. If you're relying on the `changed` event you could do

```js
formEditor.on('changed', () => {
});
```

**Comment by vsgoulart** [comment]
Hi @philippfromme, the schema was created using the web modeler inside Camunda Cloud. To create it yourself you can go to https://modeler.cloud.camunda.io

**Comment by MaxTru** [comment]
> Hi @philippfromme, the schema was created using the web modeler inside Camunda Cloud. To create it yourself you can go to https://modeler.cloud.camunda.io

This would for me mean that the issue is the schema creation in the web modeler and not in form-js right? Do we already have an issue for that in the web modeler repo?

**Comment by vsgoulart** [comment]
> > Hi @philippfromme, the schema was created using the web modeler inside Camunda Cloud. To create it yourself you can go to https://modeler.cloud.camunda.io
> 
> This would for me mean that the issue is the schema creation in the web modeler and not in form-js right? Do we already have an issue for that in the web modeler repo? Can we close this issue here?

@MaxTru Yes, I believe the main culprit, in this case, is the web modeler. Philip is talking to the team and I think they are working on a fix (I'm not sure if they already have an issue for that).

But from your side, I guess it would be nice to have some validation of the provided schema in order to avoid issues like this. So I leave it to you if this is something that the team wants to support or not.

**Comment by MaxTru** [comment]
Thanks @vsgoulart ! Makes sense. I will convert this to a feature request then.

**Comment by philippfromme** [comment]
As suspected this issue occurs when the latest schema is retrieved through the `changed` event instead of `saveSchema`. This is an anti-pattern and will never be supported. The fix would be removing `schema` from the `changed` event. In order to do that we'd have to find an alternative way of updating the state: https://github.com/bpmn-io/form-js/blob/master/packages/form-js-editor/src/FormEditor.js#L296

**Comment by philippfromme** [comment]
I've created a [follow-up issue](https://github.com/bpmn-io/form-js/issues/236) and communicated with the affected team how to fix this issue by not accessing internal state.
