### ISSUE TITLE
Formjs Viewer: Error in production build - onSubmit and onChange

### ISSUE THREAD

**Issue by manoj-mukherjee-maersk** [bpmn-io/form-js#240]
__Describe the Bug__

Getting below error on running the project in production build. It's working fine in dev build.

### Uncaught Error: No provider for "e"! (Resolving: validator -> e)
    at l (334.94231739ff87ca26.js:1:27430)
    at Object.get (334.94231739ff87ca26.js:1:27228)
    at s (334.94231739ff87ca26.js:1:27763)
    at 334.94231739ff87ca26.js:1:28016
    at Array.map (<anonymous>)
    at a (334.94231739ff87ca26.js:1:27979)
    at Array.u (334.94231739ff87ca26.js:1:28046)
    at kn.s [as get] (334.94231739ff87ca26.js:1:27731)
    at kn._update (334.94231739ff87ca26.js:1:47645)
    at Object.onChange (334.94231739ff87ca26.js:1:43819)

__Steps to Reproduce__

1. Create Nextjs project (typescript) -> ```yarn create next-app --typescript ```
2. add "@bpmn-io/form-js": "^0.7.0" -> ```yarn add @bpmn-io/form-js```
3. Create a FormViewer components 
```ts
//components/formViewer.tsx
import { Form } from "@bpmn-io/form-js";
import { useEffect } from "react";

import "@bpmn-io/form-js/dist/assets/form-js.css";

const FormViewer = () => {
  useEffect(() => {
    const data = {
      creditor: "John Doe Company",
      amount: 456,
      invoiceNumber: "C-123",
      approved: true,
      approvedBy: "John Doe",
    };

    const form = new Form({
      container: document.querySelector("#task-form-js-viewer"),
    });

    //@ts-ignore
    form.on("submit", () => {
      console.log("called");
    });

    const schema = {
      components: [
        {
          key: "creditor",
          label: "Creditor",
          type: "textfield",
          validate: {
            required: true,
          },
        },
        {
          key: "amount",
          label: "Amount",
          type: "number",
          validate: {
            required: true,
          },
        },
        {
          description: "An invoice number in the format: C-123.",
          key: "invoiceNumber",
          label: "Invoice Number",
          type: "textfield",
          validate: {
            pattern: "^C-[0-9]+$",
          },
        },
        {
          key: "approved",
          label: "Approved",
          type: "checkbox",
        },
        {
          key: "approvedBy",
          label: "Approved By",
          type: "textfield",
        },
        {
          key: "submit",
          label: "Submit",
          type: "button",
        },
        {
          action: "reset",
          key: "reset",
          label: "Reset",
          type: "button",
        },
      ],
      type: "default",
    };

    form
      .importSchema(schema, data)
      .catch((error) => console.error("cannot import form schema", error));
  }, []);
  return <div id="task-form-js-viewer" />;
};

export default FormViewer;

```

4. Pages/index.tsx
```ts
import type { NextPage } from "next";
import dynamic from "next/dynamic";

// dynamic static components
const FormViewerC = dynamic(() => import("../components/formViewer"), {
  ssr: false,
});

const Home: NextPage = () => {
  return (
    <div>
      <FormViewerC />
    </div>
  );
};

export default Home;

```
5. 
```sh
yarn build
yarn start
```
8. fill the form and open console and submit the form you will get the error.

__Expected Behavior__

In production build no error and onSubmit should work.

__Environment__

- Host (Browser/Node version) MS Edge Version 99.0.1150.46 (Official build) (arm64), Chrome
- OS: [e.g. Windows 7] Mac OS 12.2.1
- Library version: Tried 0.6.1, 0.7.0

<img width="1440" alt="Screenshot 2022-03-22 at 4 42 19 PM" src="https://user-images.githubusercontent.com/88817537/159470504-f0157e18-7abf-475c-98f4-3099b3b61e1a.png">

**Comment by manoj-mukherjee-maersk** [comment]
Example repo -> https://github.com/2manoj1/bpnmformjs
clone it.
For Reproduce 
- yarn install
- yarn build
- yarn start

**Comment by barmac** [comment]
Hi,

Thanks for reporting this issue. It seems that the build tool (Terser) used by Next.js transforms [the Validator](https://github.com/bpmn-io/form-js/blob/master/packages/form-js-viewer/src/core/Validator.js) to a function below:

```
> f.toString()
'function f(e){var t=l.call(e);return"[object Function]"===t||"[object AsyncFunction]"===t||"[object GeneratorFunction]"===t||"[object AsyncGeneratorFunction]"===t||"[object Proxy]"===t}'
```

Then, the didi dependency injection kicks in and tries to provide the cryptic "e" module which does not exist. I don't quite get it why the class is transformed this way, but can see a potential solution to the issue. We could try out if adding a line below fixes the problem:

```javascript
Validator.$inject = []
```

We are happy to accept external contributions so if you want to provide a PR, I will happily review it.

**Comment by manoj-mukherjee-maersk** [comment]
Hi @barmac, I dont much idea and knowledge on form-js lib. Can you give some workaround or quick fix for production issue.

**Comment by barmac** [comment]
I think you could try to play with the configuration, but can't give you a ready-to-use solution as I lack knowledge on Next.js. Check out this: https://stackoverflow.com/questions/42300147/how-to-disable-in-webpack-to-rename-of-function-names-typescript-javascript

**Comment by manoj-mukherjee-maersk** [comment]
Latest nextjs doest use Terser. swcMinify by default. https://nextjs.org/docs/upgrading#swc-replacing-terser-for-minification

**Comment by manoj-mukherjee-maersk** [comment]
I debug and found strict: undefined coming. 

<img width="1439" alt="Screenshot 2022-03-23 at 3 43 46 PM" src="https://user-images.githubusercontent.com/88817537/159676578-3d76c733-8078-43af-b33f-979236298b5e.png">

**Comment by manoj-mukherjee-maersk** [comment]
Its added to swc known issue. https://github.com/swc-project/swc/issues/2934
Ref: https://github.com/vercel/next.js/discussions/30237#discussioncomment-2420601

**Comment by kdy1** [comment]
Not sure if this is an issue of swc, considering that it fails even with `swcMinify: true`

**Comment by barmac** [comment]
The solution to the issue is in https://github.com/bpmn-io/form-js/issues/240#issuecomment-1075526031 It's not an swc issue but a problem with how dependency injection form-js works.

**Comment by manoj-mukherjee-maersk** [comment]
@barmac When this fix available so I will test?

**Comment by manoj-mukherjee-maersk** [comment]
@barmac not able test this. Its showing close issue but not get any releases.

**Comment by barmac** [comment]
Indeed, this will be possible when we release the library. This should happen rather soon.

**Comment by barmac** [comment]
Happening pretty soon: https://github.com/bpmn-io/form-js/pull/243

**Comment by manoj-mukherjee-maersk** [comment]
Its fixed. Thank you 😊.

**Comment by Ken-Scofield** [comment]
marker

**Comment by Ken-Scofield** [comment]
I got the same problem in webpack, `optimization.minimize = true` , it's caused by terser plugin? @barmac ,Please help me !

**Comment by Ken-Scofield** [comment]
> I got the same problem in webpack, `optimization.minimize = true` , it's caused by terser plugin? @barmac ,Please help me !

form-js 1.8.6

**Comment by Ken-Scofield** [comment]
> I got the same problem in webpack, `optimization.minimize = true` , it's caused by terser plugin? @barmac ,Please help me !

 And error echo: `Error: No provider for "e"! (Resolving: fileUploadField -> e)` fileUploadField is my custom field

**Comment by barmac** [comment]
Please read this part carefully: https://github.com/bpmn-io/form-js/issues/240#issuecomment-1075526031

You need to add proper `$inject` field for minimized code to work.

**Comment by Ken-Scofield** [comment]
> You need to add proper `$inject` field for minimized code to work.

`FileUploadPropertiesProvider.$inject = ['propertiesPanel']` already in custom properties panel.

**Comment by Ken-Scofield** [comment]
I followed the example [https://github.com/bpmn-io/form-js-examples/blob/master/custom-components/app/extension/render/index.js](url) . At last, I've figured it out that missing $inject in custom fields render class like this `FileUploadFields.$inject = ['formFields']` in render `index.js`

**Comment by Ken-Scofield** [comment]
I followed the example [https://github.com/bpmn-io/form-js-examples/blob/master/custom-components/app/extension/render/index.js](https://github.com/bpmn-io/form-js-examples/blob/master/custom-components/app/extension/render/index.js) , At last, I've figured it out that missing $inject in custom field render class, like this `FileUploadFields.$inject = ['formFields']` in render `index.js`
