### ISSUE TITLE
Label `Maps to a process variable` not meaningful outside Camunda context

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/form-js#241]
__Is your feature request related to a problem? Please describe__

Currently the form-js properties panel always shows the following description for `Key`:
![Screenshot_20220329_113305](https://user-images.githubusercontent.com/42800119/160581341-8e3f43fa-fa21-4a00-8943-576096b03522.png)

However, this description might not make sense outside the Camunda context.

__Describe the solution you'd like__

Consider to make this description configurable to also support non-Camunda use-cases.

__Describe alternatives you've considered__

Keep as is

__Additional context__

Raised during Weekly by @christian-konrad

**Comment by nikku** [comment]
We should simply change this to `Maps to an input variable`.

**Comment by Skaiir** [comment]
I think the best option here would be something like `Binds to a form variable`, maps doesn't describe the two way relationship as well. @christian-konrad what's your opinion on this?

**Comment by christian-konrad** [comment]
@Skaiir I like your suggestion, since it potentially affects both input and output. This would introduce the term "form variable" for the first time btw., so we should coin that term in the documentation

**Comment by nikku** [comment]
Let's adopt this then, and consider how documentation could be updated.
