### ISSUE TITLE
Be able to bind inputs to readonly text

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#247]
__Is your feature request related to a problem? Please describe__

As a user I want to bind form input to readonly text, potentially formatted using Markdown.

__Describe the solution you'd like__

I can model a field to bind a single variable to a readonly text representation.

We shall consider how we deal with these special _readonly_ variables; shall we still include them in the result? What SAFE properties do we want to guarantee? Cf. [blog post](https://bpmn.io/blog/posts/2022-form-js-default-values-improved-submit.html).

__Describe alternatives you've considered__

Re-use the existing text component to allow variable binding. This would allow to mix and match a number of variables.

__Additional context__

Originally captured in [this conversation](https://camunda.slack.com/archives/C034N0E5YCX/p1650414431837809).

----

Requested via SUPPORT-12403

Related to https://github.com/bpmn-io/form-js/issues/200

**Comment by nikku** [comment]
https://github.com/bpmn-io/form-js/pull/302 proposes adding [Mustache](https://github.com/janl/mustache.js) for string templating.

Two aspects to consider here: What shall be our separators (PR proposes `{{ }}`) but also language to establish dynamic bindings (shall be feel? ``hello {{ user.name }}``). Mustache itself is a quasi standard, simpler than FEEl, and more powerful in many (templating related) aspects.

**Comment by jonathanlukas** [comment]
A discussion with @nikku had the following outcomes:

* a user can be confused when using Camunda products with FEEL and then having one special place where another language is used
* the requirements for templating might at some point be various, but the decision to use FEEL for templates would open the possibility to use FEEL inside templates as well
* #302 gives us a good idea on how templates in forms can look like
* before a pull request can be merged, we will have to define the initial feature scope
* it is very likely that the main effort to implement this feature will happen in FEEL (and the engines being used)
* a test case is very helpful to show the way a feature is implemented. This test-case is end-to-end (text that should be displayed containing the templates -> rendered html). Util-function tests can help identify problems and proof a functionality, so they should exist as well.

@nikku If I forgot something, please git me (on slack)

**Comment by pinussilvestrus** [comment]
We will start adding FEEL support via https://github.com/bpmn-io/form-js/issues/436. Note that's not a decision against Mustache or any other vendor by now. We still aim to support this some day, maybe.

**Comment by Skaiir** [comment]
Closed as this is now handled via feelers.
