### ISSUE TITLE
Migrate to common bpmn-io properties panel

### ISSUE THREAD

**Issue by MaxTru** [bpmn-io/form-js#249]
__Is your feature request related to a problem? Please describe__

The form-js properties panel is custom, hence it differs technically and from UI to the "common" bpmn-io properties panel.

__Describe the solution you'd like__

Migrate to https://github.com/bpmn-io/properties-panel for the properties panel

* [x] Decide about integration strategy
  * [x] Integrate [properties panel framework](https://github.com/bpmn-io/properties-panel) as component, or
  * [x] Provide properties panel as form-js extension
* [x] Add [header provider](https://github.com/bpmn-io/properties-panel/blob/main/src/components/Header.js)
* [x] Migrate groups
  * [x] general
    * [x] id: text  
    * [x] label: text  
    * [x] description: text  
    * [x] key: text  
    * [x] defaultValue: select or number or text  
    * [x] action: select  
    * [x] columns: number  
    * [x] text: textArea  
    * [x] disabled: checkbox  
  * [x] values
    * [x] add as list group (can be group + nested list in the future) 
    * [x] label: text
    * [x] value: text
  * [x] validation
    * [x] required: checkbox  
    * [x] minLength: number  
    * [x] maxLength: number  
    * [x] pattern: text  
  * [x] custom properties
    * [x] add as list group
    * [x] key: text
    * [x] value: text
* [x] Migrate tests 
* [x] Migrate labels to sentence case (to be in line with bpmn- and dmn- propPanel)
* [x] Provide placeholders (although not supported by now), cf. https://github.com/bpmn-io/properties-panel/pull/152
* [x] Consider: override variables inside Camunda Modeler to provide a higher contrast
  * `--color-properties-container-background`
  * `--color-properties-input-background` 

__Describe alternatives you've considered__

Keep existing infrastructure.

__Additional context__

* Analog to solutions for
  * bpmn: https://github.com/bpmn-io/bpmn-js-properties-panel
  * dmn: https://github.com/bpmn-io/dmn-js-properties-panel

**Comment by MaxTru** [comment]
@christian-konrad could you please evaluate how important that would be from PM perspective?

@smbea since you already did dmn-js and (I think) also considered the form-js migration, could you give a rough t-shirt size for this / how much effort would it be?

**Comment by smbea** [comment]
I didn't actually get to the point of looking into form-js. But I would guess around 2 weeks. Depending on who is doing it - might have a bit more experience with the form-js prop panel and might be quicker.

**Comment by christian-konrad** [comment]
@MaxTru we should also update the I18n of the properties panel then. In bpmn/dmn, we use sentence case for all properties and titles, but in forms, we use title case. @andreasgeier told to use sentence case everywhere (please correct me if I'm wrong).

Could you add this story point here to the issue, and also the param to choose between white and gray background color mode (with respective field bg coloring), to avoid the white-on-white contrast in Camunda Forms editor?

**Comment by pinussilvestrus** [comment]
You mentioned a couple of things here, so to summarize:

> update the I18n of the properties panel

Translations are not part of the [properties panel framework](https://github.com/bpmn-io/properties-panel) but are part of the integrator (bpmn-js-properties-panel, dmn-js-properties-panel). Therefore I would say i18n is not part of the migration story.

>  we use sentence case for all properties and titles, but in forms, we use title case

I already covered this in the [draft PR](https://github.com/bpmn-io/form-js/pull/254). I will add it to the issue itself as well to keep it covered.

> also the param to choose between white and gray background color mode

I don't know about such a mode. Is this something we have in other libraries as well?

**Comment by MaxTru** [comment]
> > also the param to choose between white and gray background color mode
>
>I don't know about such a mode. Is this something we have in other libraries as well?

Sorry - that is on me. @christian-konrad already requested this 1 week ago or so and I wanted to discuss this with you @pinussilvestrus.

@christian-konrad do you want to brief @pinussilvestrus directly?

**Comment by pinussilvestrus** [comment]
> Sorry - that is on me. @christian-konrad already requested this 1 week ago or so and I wanted to discuss this with you @pinussilvestrus.
> 
> @christian-konrad do you want to brief @pinussilvestrus directly?

Some context after a quick chat with @christian-konrad:
* Given the current color scheme, the distinction between Form Editor and Form Properties Panel might be too low => both a forms with the same color scheme
* Whatever we build, should be themable => We already do this via CSS variables (e.g. `--color-properties-container-background`)

Screenshot[ from the draft](https://github.com/bpmn-io/form-js/pull/254)

![image](https://user-images.githubusercontent.com/9433996/168808376-42b4de36-7a61-4659-9d90-62b948fce3c4.png)
