### ISSUE TITLE
Templated sets of input fields to represent object collections (or Subforms name tbd)

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#251]
__Is your feature request related to a problem? Please describe__

Very often in form interaction, we want to supply multiple different sets of data that we might not know the number of. For example a restaurant bill is a set of menu items, quantities and prices. A shopping cart online is the same principle. [This new user](https://forum.camunda.io/t/option-to-add-a-new-field-in-camunda-form/37460) of our modeler displays interest in this feature and it has been brought up internally as well.

![image](https://user-images.githubusercontent.com/17801113/167628487-ff0d519f-3543-4646-ad1d-87aefa316b82.png)

This is currently a limitation of forms, we are just working on solutions for multi-select but we have not yet touched upon **multi-entry**. 

__Describe the solution you'd like__

Sub-forms should be another component in the toolkit no matter what IMO.

I see two ways of implementing this one:

A. The open variation: 
Allow sub-form building via drag and drop, this means we'll have to implement nested drag and drop which honestly was already on our plate with conditional rendering. This also means that we'll need to upgrade all our components to allow their variable mapping logic to be extended. I foresee some implementation challenges in that area and it will be disruptive in our codebase.

B. The closed variation: 
Adopt a simpler parameterized solution to this, where fields are instead configured in a collection in the properties panel, which would allow us to keep all the custom variable mapping within the one component. Might not be a very elegant solution and might take a bit more work to do from scratch, but it will have a much smaller impact on the codebase.

__Additional context__

Forum post: https://forum.camunda.io/t/option-to-add-a-new-field-in-camunda-form/37460
As revealed in weekly, @christian-konrad already had plans for this outlined here: https://github.com/camunda/product-hub/issues/99

**Comment by pinussilvestrus** [comment]
Is this related to the ["layout component"](https://github.com/bpmn-io/form-js/issues/47)? We already invested a bit into this (but didn't proceed in the past).

**Comment by Skaiir** [comment]
We would need a layout component to implement both solutions, kinda. It's mildly related.

**Comment by Skaiir** [comment]
Closing as dupe, current working issue is here: https://github.com/bpmn-io/form-js/issues/796
