### ISSUE TITLE
Support `Fieldset` to group form fields

### ISSUE THREAD

**Issue by 9n** [bpmn-io/form-js#252]
__Is your feature request related to a problem? Please describe__

Support `Fieldset` to group form fields, counterpart to html tag `fieldset`.

__Describe the solution you'd like__

Add a `Fieldset` field component with type `fieldset`. Suggested schema:
```json
{
      "type": "fieldset",
      "label": "Fieldset",
      "components": [
        {
          "key": "firstName",
          "label": "First Name",
          "type": "textfield",
          "validate": {
            "required": true
          }
        }, 
        {
          "key": "lastName",
          "label": "Last Name",
          "type": "textfield",
          "validate": {
            "required": true
          }
        }
      ]
    }
```

related to #47 

__Describe alternatives you've considered__

__Additional context__

![Screenshot_20220511_172022](https://user-images.githubusercontent.com/6767335/167815936-1527a65a-6c28-4831-8ccd-0aa79bffc02c.png)

**Comment by nikku** [comment]
Thanks. Would you value this one over a (no border) vertical stacking component?

**Comment by 9n** [comment]
This is visible group of fields, with label. It's helpful to group complex form, specially, with layout support.

**Comment by pinussilvestrus** [comment]
a11y wise, this would the most native approach we could take when grouping form fields (no custom grouping architecture where we would make it accessible on our own). 

Context: https://www.w3.org/WAI/tutorials/forms/grouping/

**Comment by christian-konrad** [comment]
@pinussilvestrus  @nikku  I already have an epic for this:

https://github.com/camunda/product-hub/issues/99

**Comment by christian-konrad** [comment]
@9n thanks for this request - we want to work on this, depending on our prioritities.
We also want to provide repeated fieldsets - which means  as someone filling in the form, you can add another instance of the fieldset with a single button click (and remove instances, too)

**Comment by nikku** [comment]
> you can add another instance of the fieldset with a single button click (and remove instances, too)

@christian-konrad What is this? Could you layout this use-case and document it in an issue?

**Comment by nikku** [comment]
As I see it "fieldset" is our solution for _vertical grouping_. That said, a future `columns` component will be our solution for _horizontal grouping_. Cf. https://github.com/bpmn-io/form-js/issues/47.

If we go this route this is a valid contribution; I'd love us to consider some basic requirements:

* The component _should_ not be visually verbose (border around it)
* The component _should_ be semantic (HTML `fieldset`), if possible
* The component _could_ have an optional label, but does not have to

**Comment by 9n** [comment]
Although similar, I think  `group` and `layout` have different concerns. 

When form get complex, eg more than 30 fields, I need `group` these fields by business relations to make them visually clear. In this situation, I think border and  label are both needed.

On other hand, `layout` is about vertically or horizontal align, which should not have order and label.

**Comment by nikku** [comment]
Moving this to backlog. We plan to provide a component for vertical stacking, however we don't know yet if it is going to be fieldset.

**Comment by Skaiir** [comment]
This is now handled via groups, thank you for the inspiration @9n
