### ISSUE TITLE
Allowing configuration of values (options) source via the properties panel for 'select-type' components

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#256]
__Is your feature request related to a problem? Please describe__

As part of our dynamic data loading initiative for our form components, we would want to enable users to drive their select-able data from sources other than the form schema.

To this end, we need to enable configuration within the form schema to set this external source somehow. This will be used to allow values to be passed in from `input data`, but may be extended in the future to apply to `functions`, and others.

__Describe the solution you'd like__

Sketch by @pinussilvestrus :

![image](https://user-images.githubusercontent.com/17801113/168276048-375b84aa-af17-4fd5-b260-d6ef913cb552.png)

This toggle should drive the form schema and define the data source on it. How exactly this will be done still needs to be defined as part of https://github.com/bpmn-io/form-js/issues/197. 

__Additional context__

Blocking tickets: 
Depends on https://github.com/bpmn-io/form-js/issues/197
Depends on https://github.com/bpmn-io/form-js/issues/249

Parent: 
Child of https://github.com/bpmn-io/form-js/issues/200

**Comment by Skaiir** [comment]
@christian-konrad pinging since you're the first to bring it up but I fully support this.

Currently we have so many different 'values', the underlying data of the form is called a value, the different choices of selects are called values, and then the value of one of these choices is called, a value again. This leads to really difficult to read code `if values.includes(value)` and I'd like to pitch for us to rename values to options within the code base as well as across our UI. 

I've already done this somewhat with my taglist code, by using name overrides with object deconstruction:

```js
const {
description,
id,
label,
values : options
} = field;
```

This would align with the html select tag: https://www.w3schools.com/tags/tag_select.asp, which uses the term option as well.

**Comment by pinussilvestrus** [comment]
@Skaiir I also experienced this (UI and code-wise, not the schema). Let's consider bringing this to the next Hour of Code 👍

**Comment by christian-konrad** [comment]
@Skaiir thanks for raising the options thing!

Would love to see this renaming in the UI. 

Furthermore, I am confused by this:

![Bildschirmfoto 2022-05-17 um 13 26 52](https://user-images.githubusercontent.com/56470362/168800499-c791737b-6add-4525-832a-15d12621d45c.png)

Why does it say "**can** map to a process variable"? Can it map to something else, too?
If not, we should just rename the whole source to "input variables" (so it works not only in Camunda context, but also standalone form.js context)

![SourceTypeForms](https://user-images.githubusercontent.com/56470362/168803047-879aab22-7b71-461c-852c-e781e5411c78.png)

**Comment by Skaiir** [comment]
There are just sketches so far, so I wouldn't be surprised if these weren't final / taken from somewhere in the UI already.

**Comment by nikku** [comment]
> If not, we should just rename the whole source to "input variables" (so it works not only in Camunda context, but also standalone form.js context)

Great point. I suggest to tackle the renaming to "input variables" as a follow up to this PR.

**Comment by nikku** [comment]
Related to https://github.com/bpmn-io/form-js/issues/256#issuecomment-1126095754 I can share a little bit of background on `Values` over `Options`: By using form-js users model the available / allowed data. They define which things are allowed to be submitted. What are the potential _values_. Hence we've started with values here in the first place.

We could decide to move closer to HTML and change that to options. But then again, are people that use form-js HTML experts? 

Also as we discuss this I'd love to separate our core (and the impact certain ambiguity has on understanding it) from the UI. "The code becomes more readable" should not be the only reason to change the UI.
