### ISSUE TITLE
Handle Unkown Form Fields

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#26]
__Is your feature request related to a problem? Please describe__

When importing a schema that contains unknown form fields (form fields that cannot be rendered) a fallback is rendered instead telling the user that the form field cannot be rendered. From an API point of view the user has no way of knowing whether the entire form was rendered successfully.

__Describe the solution you'd like__

This issue was discussed by @andreasgeier, @philippfromme and @volkergersabeck.

We should do two things:

#### 1. Adjust the API to separate instantiation and import (similar to bpmn-js and dmn-js)

The API would change from

```javascript
import { createForm, createFormEditor } from 'form-js';

...

const form = createForm({ container, schema, data });

// Was the form rendered successfully?!
```

to

```javascript
import Form, { FormEditor } from 'form-js'; // Viewer is the default export, editor is available, too

...

const form = new Form({ container }):

const { errors, warnings }  = await form.importSchema(schema, data); // data is optional

if (errors) {
  // Handle errors
}

if (warnings.length) {
  // Handle warnings
}
```

#### 2. Adjust the styling of the fallback

Doesn't need alignment with UX for now, reasonable default is okay.

__Additional context__

Code freeze of the Camunda Platform that would depend on these changes is March 25th 2021.

----

Related to https://github.com/bpmn-io/form-js/issues/10

**Comment by philippfromme** [comment]
@nikku Looking forward to hearing your thoughts about this.

**Comment by nikku** [comment]
As discussed we're going to adopt the most simple solution for now:

* Importing any unknown schema elements will result in the full form to not render
* An error is thrown that clearly indicates the problem to integrators

We may go back to the solution sketched :arrow_up: in the future.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/form-js/issues/27.
