### ISSUE TITLE
Investigate leaving behind a placeholder when drag&dropping 

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#263]
__Is your feature request related to a problem? Please describe__

When moving form elements around, the element becomes removed from the editor before it's been dropped somewhere else, which leads to some hard to predict movements of the form. This leads to often having to re-adjust your cursor and is a little disorientating IMO. I'd like for us to explore the idea of leaving behind a placeholder during drag and drop so that the form doesn't move and these dragging actions become more predictable and user friendly. This I believe will become especially relevant when we introduce more complex layouts. 

![Kapture 2022-06-03 at 09 20 28](https://user-images.githubusercontent.com/9433996/171807108-72dc1caa-a653-431c-a717-d3fd15cf8754.gif)

__Describe the solution you'd like__

Either leaving behind a low opacity version of the control we're moving, or a box matching the size of the dragged element until the cursor is released somewhere else, which would then clear the placeholder, somewhat in the way that `bpmn-js` does this. 

__Describe alternatives you've considered__

Assuming this doesn't end up being better

**Comment by pinussilvestrus** [comment]
We delivered a new placeholder that while implementing the new drag & drop behavior.



![Image](https://github.com/bpmn-io/form-js/assets/9433996/66205c56-58c9-4dd0-ba39-c1f730c118b0)
