### ISSUE TITLE
Subforms / Repeated Groups of Form Fields

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#264]
__Is your feature request related to a problem? Please describe__

With form.js, developers currently can not build repeated, flexible groups of fields. If they don't know the amount of repeated items on design time, they can not build forms for that. Currently, only a static set of field instances can be defined.

This is also related to https://github.com/bpmn-io/form-js/issues/252 which describes the layout part of (sub-)forms.

Internal epic to this topic: https://github.com/camunda/product-hub/issues/99

__Describe the solution you'd like__

By defining a schema like this,

![image](https://user-images.githubusercontent.com/56470362/169982177-62a55443-18ee-4455-a4e3-57ecc8cc1f28.png)

a subform is created and visible in the form. By setting `repeated` and `optional` accordingly, the subform can be created multiple times, exactly once or even cam be omitted (then, only a "Add <subform>" button appears.

![image](https://user-images.githubusercontent.com/56470362/169983116-30825745-4020-4714-b28b-2275c0868c5d.png)

Forward looking, a subform can of course contain a `column` or `fieldset` or any combination of those to layout and style the subform, the same way the top-level form can be managed.

(More to come in the future: This would enable form.js to reference other forms by ID (or just JSON path if forms are in a same directory root) and incorporate them into a parent form as subforms.)

__Describe alternatives you've considered__

__Additional context__

- Internal epic to this topic: https://github.com/camunda/product-hub/issues/99
- This is also related to https://github.com/bpmn-io/form-js/issues/252 which describes the layout part of (sub-)forms.
- https://github.com/bpmn-io/form-js/issues/251
- https://github.com/bpmn-io/form-js/issues/47

**Comment by pinussilvestrus** [comment]
Subforms are closed via https://github.com/bpmn-io/form-js/pull/768
Repeated subforms aka dynamic lists will be closed via https://github.com/bpmn-io/form-js/issues
