### ISSUE TITLE
Taglist dropdown overflows horizontally

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#271]
__Describe the Bug__

The taglist completion dropdown does overflow horizontally during wrong sizing:

As a result the form component is turned into a horizontally scrollable container:

![capture LALqxV_optimized](https://user-images.githubusercontent.com/58601/175247973-cc502eb7-cb8d-447a-a9a6-02cf5b95a0c8.gif)
 

__Steps to Reproduce__

1. Checkout form-js
2. `npm run start:playground`
3. Autocomplete tag list in form preview
4. __Notice form preview turns into horizontal scroll container__

__Expected Behavior__

Dropdown is as wide as form control, but not wider.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 101
- OS: Linux
- Library version: `develop`

**Comment by smbea** [comment]
Can reproduce, moving to backlog

Can be resolved by adding a simple `position: relative` to the taglist container (`.fjs-form-field-taglist`)
