### ISSUE TITLE
Shortcut format to define selectable data for rapid-prototyping purposes

### ISSUE THREAD

**Issue by tasso94** [bpmn-io/form-js#279]
__Is your feature request related to a problem? Please describe__

With bpmn-io/form-js/issues/197 it will be possible to define selectable data from other sources than the form schema.

The way how dynamic values are defined in JSON makes sense for real-world scenarios where you want to assign a proper label to an element. However, it stands a bit in the way of "quickly trying something out". For the "rapid prototyping" use case, we thought we could additionally offer a mapping that would shorten the whole thing a bit.

__Describe the solution you'd like__

For the rapid-prototyping use case, it might make sense to simplify the format as follows:

The following JSON array:

```json
["dynamicValue1", "dynamicValue2"]
```

Would be mapped to:

```json
[
  {
    "label": "dynamicValue1",
    "value": "dynamicValue1"
  },
  {
    "label": "dynamicValue2",
    "value": "dynamicValue2"
  }
]
```

Both `label` and `value` would be assigned the same value. That's not nice for real-world use cases. However, it might be just right if you want to "try something out quickly".

__Describe alternatives you've considered__

Don't add the shortcut format in the `form-js` library but make it available in C7.

__Additional context__

_Originally posted in https://github.com/bpmn-io/form-js/issues/197#issuecomment-1178041147_

**Comment by pinussilvestrus** [comment]
I'd like to hear your thoughts on this @christian-konrad @nikku

**Comment by nikku** [comment]
Sounds like a nice to have feature, some day, maybe.

But given it can be built trivially from "outside" form-js I'd not act on this right now.

**Comment by tasso94** [comment]
@nikku, we don't build any prototyping tools, but I think any proper project built with C7 starts small in a prototyping phase where you want to iterate quickly.

**Comment by christian-konrad** [comment]
@tasso94 @pinussilvestrus @nikku in general, I think this could be helpful for some of our onboarding use cases. It makes mapping response data into a form select field more easy if the label is optional. As this would require both schema and form.js adjustments, I would keep this in the backlog until we have this onboarding cases.

**Comment by pinussilvestrus** [comment]
This is possible now via form-js@0.13.0
