### ISSUE TITLE
common-js distro is broken for v0.0.8

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#29]
__Describe the Bug__
- Importing the library using common-js will result in an error:
![image](https://user-images.githubusercontent.com/21984219/111968838-e34e9580-8af9-11eb-9179-076cc249a5d5.png)

__Steps to Reproduce__

1. Install the latest version `npm i @bpmn-io/form-js@0.0.8`
2. Import the library using common-js notation `require("@bpmn-io/form-js").createForm`
3. Bundle and open in browser

__Expected Behavior__

- The library can be bundled using common-js

__Notes__

Loading works fine when including it as module: `import { createForm } from '@bpmn-io/form-js';`
Only importing the `form-js-viewer` also works `require('@bpmn-io/form-js-viewer').createForm`

This is **not** blocking our release, we just need the viewer, which works

__Environment__

- Host (Browser/Node version): Chrome 89, node v14.6.0 
- Bundler: Tested with Webpack and Browserify
- OS: Ubuntu
- Library version: 0.0.8

**Comment by vsgoulart** [comment]
As I mentioned on the meeting I have a similar issue, but for me it only happens on the test env.
What I used as a temporary solution was what Martin mentioned, I'm importing `createForm` directly from `@bpmn-io/form-js-viewer`
