### ISSUE TITLE
Explanatory tooltip for new dynamic input options

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#305]
__Is your feature request related to a problem? Please describe__

Users will not understand the new dynamic input options feature, even not when using the playground, since there is no explanation of how to define the input values.

__Describe the solution you'd like__

A tooltip explains how the schema of the input attribute looks like.

![explanation_tooltip_propertiespanel](https://user-images.githubusercontent.com/56470362/183469663-a4a7564f-54ab-4589-9f18-3c9f44dd1b33.png)

__Describe alternatives you've considered__

__Additional context__

**Comment by christian-konrad** [comment]
I could imagine having this as a generic feature for the properties panel.

**Comment by pinussilvestrus** [comment]
As a first step, would that also work by extending the description below the input field?

**Comment by christian-konrad** [comment]
Related to: https://github.com/bpmn-io/form-js/issues/303

**Comment by christian-konrad** [comment]
@pinussilvestrus @smbea having it in the description is totally fine for now.

**Comment by christian-konrad** [comment]
Related to https://github.com/camunda/team-hto/issues/57

**Comment by Skaiir** [comment]
https://github.com/bpmn-io/form-js/pull/316 was Bea's original description contribution, just going to post this here as I'm closing the original ticket (https://github.com/bpmn-io/form-js/issues/303).

**Comment by christian-konrad** [comment]
@Skaiir what's the progress here?

**Comment by pinussilvestrus** [comment]
This can be fixed once https://github.com/bpmn-io/properties-panel/pull/258 is merged and integrated.

**Comment by Skaiir** [comment]
Related: https://github.com/bpmn-io/form-js/issues/784
