### ISSUE TITLE
Make it possible to hide certain elements on the form

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#31]
__Is your feature request related to a problem? Please describe__

On Zeebe Tasklist we would like to hide the bpmn.io logo and submit button (in favor of our own button).
Currently I'm doing that programmatically selecting the classes, but every time the form rerenders the elements disappear and I have to remove them again, which causes them to be visible for a split second.

__Describe the solution you'd like__

```js
const form = createForm({
  properties: {
    hiddenElements: ['logo', 'submitButton'],
  },
});
```

__Describe alternatives you've considered__

Don't provide any API to hide the elements but prevent them from being added again on every rerender

**Comment by nikku** [comment]
As discussed we'll not implement something like this in the near future. 

The technique you mention is an interesting one though and we may follow up regarding it, one day, maybe.
