### ISSUE TITLE
Allow Objects Keys as Key Value [duplicate]

### ISSUE THREAD

**Issue by Asdoos** [bpmn-io/form-js#326]
__Is your feature request related to a problem? Please describe__

I wan't to pass an Object in the Data and use a key of those for a Form Key

__Describe the solution you'd like__

Set the Key of a component to Object key and this will be shown in the Form

__Describe alternatives you've considered__

Convert the Object in single variables

__Additional context__

Example:

Object: 
![image](https://user-images.githubusercontent.com/27813495/188584220-94919981-bc72-4fb0-a54f-d5648e0384d9.png)

Form:
![image](https://user-images.githubusercontent.com/27813495/188583869-b2a92ede-2777-4ea5-9e32-482c157049b2.png)

Maybe this is already doable. If yes - please update docs

**Comment by pinussilvestrus** [comment]
I believe that's not possible now, so a valid feature request. Thanks 👍

**Comment by Skaiir** [comment]
We want to consider options for this and track it in https://github.com/bpmn-io/form-js/issues/464, I'll close this one as duplicate but I've referenced it for context.
