### ISSUE TITLE
Make the playground more popular

### ISSUE THREAD

**Issue by jonathanlukas** [bpmn-io/form-js#328]
__Is your feature request related to a problem? Please describe__

The playground of form-js is super awesome! Also, it is not very known I guess. Beside integrating it in our favourite desktop and web modeler, we should include it into the demo.

__Describe the solution you'd like__

The demo offers a the playground view.

__Describe alternatives you've considered__

One can spin up the playground locally. This would require frontend programming knowledge or at least some research. As it would only be a static resource, this should not be very hard.

__Additional context__

I love the playground and would like to make it more popular.

**Comment by jonathanlukas** [comment]
This is great to hear 👍 Is the demo then out of scope or just delayed? Or is there another DRI for this?

**Comment by pinussilvestrus** [comment]
We have it on our list: https://github.com/bpmn-io/bpmn-io-demo/issues/107. It's definitely something we have on our follow-up list ([among other things](https://github.com/bpmn-io/internal-docs/issues/527)). 

Personally, I'd love to see this on https://demo.bpmn.io/form, but that's depending on the priorities we have. I know @christian-konrad was also thinking about bringing it into something like https://camunda.com/try-modeler/. 

Your interest/feedback helps to prioritize 👍

**Comment by nikku** [comment]
@pinussilvestrus This is something that we should pick up as part of our community worker duties. We did not get priority for such things in the past at least. Happy to be proven wrong, of course!

**Comment by christian-konrad** [comment]
Updating https://demo.bpmn.io/form once we have it settled should belong to our minimum duties :)

**Comment by pinussilvestrus** [comment]
I'm moving this to the backlog, and take care we handle this via https://github.com/bpmn-io/internal-docs/issues/527.

**Comment by nikku** [comment]
> we should include it into the demo.

We did not do this as part of https://github.com/bpmn-io/internal-docs/issues/527, unfortunately. But the need to have it is also shown by recent [form-js@0.10 blog](https://github.com/bpmn-io/bpmn.io/issues/153): 

![image](https://user-images.githubusercontent.com/58601/209661133-b2c9f1b3-a368-46d3-92b3-dadc38c383d5.png)

@pinussilvestrus @christian-konrad I suggest that we pick this up soon, as we don't have a demonstrable thing to showcase form-js from the bpmn.io perspective.

----

As a site-note the current playground (the thing users can use out of the box) is outdated, and actually using it may encourage us to keep it relevant: https://github.com/bpmn-io/form-js/pulls/nikku.

**Comment by pinussilvestrus** [comment]
Thanks @nikku for bringing this up and adding some bits to keep the core playground up-to-date ❤️ 

Let's discuss/prioritize this one once we are back from vacation mode. I'm adding it to `ready`.
