### ISSUE TITLE
Also use IBM Plex Sans for Inputs

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#330]
__What should we do?__

Also use the IBM Plex Sans font for inputs.

__Why should we do it?__

We use it everywhere (e.g. in labels), and should be consistent.

**Comment by pinussilvestrus** [comment]
I'm moving this to backlog and label it as `spring cleaning`. Feel free to give it a higher priority 👍

**Comment by pinussilvestrus** [comment]
Should be fixed via https://github.com/camunda/camunda-modeler/pull/3231.

**Comment by pinussilvestrus** [comment]
Actually found another quirk in the viewer: https://github.com/bpmn-io/form-js/pull/353.
