### ISSUE TITLE
Properties panel in forms-js is not updating on change

### ISSUE THREAD

**Issue by Hafflgav** [bpmn-io/form-js#332]
__Describe the Bug__
Radio buttons are not effectively configurable anymore.
I am having trouble to modify “value 2” of my radio button. 
It gets even more confusing when I am trying to change “Options Source” without deleting my static values upfront.
It seems that the properties panel is not updating - only if you force it to reload. 
There are some screenshots / gifs down below which exactly describe the behaviour. 

__Steps to Reproduce__
1. Open up Web Modeler 
2. Create a project 
3. Create a folder 
4. Create a form 
5. Add a Text
6. Add a Radio Button with two options

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/30292227/190348544-756c46ef-e60a-48db-9ff9-69b54cd81196.png">

https://user-images.githubusercontent.com/30292227/190348162-7c1ae613-b23b-465a-a837-12be206e30dd.mp4

<img width="1307" alt="image" src="https://user-images.githubusercontent.com/30292227/190348659-4cad5497-030f-4b84-8e13-884b3cc60ff2.png">

__Expected Behavior__
Properties panel is updated on change. 

__Environment__
- Chrome 105.0.5195.102 
- OS: MacOS 12.5.1
- Library version: Camunda 8 SaaS

**Comment by Skaiir** [comment]
@christian-konrad Picking this up right now :)
