### ISSUE TITLE
Build agnostic styling for the dateTimePicker

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#339]
__What should we do?__

Only after https://github.com/bpmn-io/form-js/issues/338.

We shall build a visually complete implementation of the new dateTimePicker component and refine it with design.

__Why should we do it?__

Once we're happy with the UX flow of the component, we want to polish it visually to achieve the look and feel that we expect out of our components in `form-js`. These steps will involve back and forth with design to achieve something homogeneous with the rest of our form fields. 

__Steps:__

- [x] Build initial visual implementation
- [x] Request first design feedback
- [x] If major reworks are needed, re-implement
- [x] Evaluate UX in relation to that of carbon, for simplicity in the future
- [x] Refine individually according to current form-js styling practices

**Comment by RomanKostka** [comment]
proposal for the native form-js date-time-picker:
<img width="793" alt="image" src="https://user-images.githubusercontent.com/114994124/197975496-dbb298a5-8f7e-430a-bd8d-668c329154f2.png">


Detached date & time - preparing for carbon + minimize cognitive load
Removed timezone - minimize cognitive load
Default date dropdown with slightly changed CSS - better readability 
Carbon Icons

**Comment by Skaiir** [comment]
The state as per the design sprint (barring some bugs) has been deemed acceptable for release. I'll hence close this issue.

![image](https://user-images.githubusercontent.com/17801113/201875204-ab787eaf-e641-4f7b-a191-370041b0207b.png)
