### ISSUE TITLE
Form builder is generating invalid schemas with text elements that have new lines

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#342]
__Describe the Bug__

When creating a form with a text element that has a new line, the form builder generates a JSON schema that makes the viewer break.

__Steps to Reproduce__

1. On any form builder add a text element
2. Edit the text and add a new line between the text
3. Copy the JSON schema generated by the builder and try to render it with the viewer (example below)
4. The form breaks when trying to import the schema

Schema example:
```json
{
  "components": [
    {
      "text": "# Run E2E test\n\nBuild an image for the release version if it doesn't already exists. Image should be already available if you have setup the benchmark.\n\nRun github action https://github.com/zeebe-io/zeebe-e2e-test/actions/workflows/runtest.yml to start a e2e test on the release branch\n with following parameters:\n- Zeebe docker image with version: gcr.io/zeebe-io/zeebe:release-MAJOR-MINOR-PATCH-ALPHA\n- Generation template: Zeebe SNAPSHOT\n- Test duration*: R1/P7D \n- A string to identify the run: E2E Tests : rc-MAJOR-MINOR-PATH-ALPHA\n\nThis will start an e2e test and run it for the given duration. If the test fails, you will get a notification in #zeebe-ci channel. \n\nEnsure the test is started by checking Operate of Testbench-prod cluster https://console.cloud.ultrawombat.com/org/f1155314-5031-4a84-9e29-58f69f8ab242/cluster/7b2cd3f5-cfcc-4a65-ab22-0ccaa071e68e ",
      "type": "text",
      "id": "Field_158j4g9"
    }
  ],
  "schemaVersion": 4,
  "exporter": {
    "name": "form-js (https://demo.bpmn.io)",
    "version": "0.7.2"
  },
  "type": "default",
  "id": "Form_06z84ew"
}
```

__Expected Behavior__

The viewer shouldn't break with schema generated by the builder

__Environment__

- Library version: from 0.7.0 onwards

**Comment by vsgoulart** [comment]
Additional info: If we replace `\n` with `\\n` it works

**Comment by barmac** [comment]
I tried to reproduce it with both `v0.7.0` and `master` viewer but failed. The form is rendered correctly:

![image](https://user-images.githubusercontent.com/28307541/192714176-2c4bf415-9472-4d64-ad19-aeaa8659c39f.png)

**Comment by barmac** [comment]
Check out also this codesandbox: https://codesandbox.io/s/divine-thunder-nelv2v?file=/src/index.js

**Comment by vsgoulart** [comment]
@barmac I just noticed it was was a problem with how we're parsing the the JSON string :man_facepalming:  I'll close this since it's a problem on Tasklist side.

Sorry for wasting your time
