### ISSUE TITLE
Different order of checklist items in form and properties panel

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#350]
__Describe the Bug__

The order of checklist items in the form and the properties panel is different. While they appear in the form in the order of how they've been added, they appear in reverse order in the properties panel, and when collapsing the section and reopening it, they appear in lexicographical order.

![static-forms-order](https://user-images.githubusercontent.com/56470362/194884106-b2655bb2-ab24-4fcf-8b9a-476282d9fa4e.png)

__Steps to Reproduce__

See video:

https://user-images.githubusercontent.com/56470362/194884814-6d8c9b79-45a2-408e-8958-b154395bdef7.mov

__Expected Behavior__

Order in the form and the panel is always the same.

__Environment__

- Camunda Modeler 5.4.1

**Comment by pinussilvestrus** [comment]
Seems like we accidentally activated alphabetical ordering during the properties panel migration. I will follow-up with a quick fix.

**Comment by pinussilvestrus** [comment]
This should be fixed via https://github.com/bpmn-io/form-js/issues/351.
