### ISSUE TITLE
Discourage the use of disabled fields

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#362]
__What should we do?__

The usage of disabled fields should not be encouraged (context, e.g. https://medium.com/@izzmo/anti-pattern-using-disabled-or-read-only-for-form-input-e2c24c669f5b). For displaying static values, rather [use read-only text to display that data](https://github.com/bpmn-io/form-js/issues/247).

Consider linting as one way to discourage the use.

__Why should we do it?__

The original use case of disabled form fields was to display static values in the form that should not be submitted. However, [with emerging use cases that are possible](https://github.com/bpmn-io/form-js/issues/273) with form-js, this workaround is not needed, and should not be needed anymore.

Disabled form fields are not recommended in HTML forms land, nor should they be recommended by our toolkits. We can not ditch them entirely without having a major breaking change in our forms schema.

Also important: [Our state about submitting](https://bpmn.io/blog/posts/2022-form-js-default-values-improved-submit.html) (blog post).

**Comment by Skaiir** [comment]
One thing to note with the linter is that it's reactive to users making a mistake (or upgrading an old version of a form). We should probably also discourage this some other way.

**Comment by Skaiir** [comment]
Closed via https://github.com/camunda/form-linting/pull/68
