### ISSUE TITLE
Cannot click the scrollbar on Taglist dropdown (dropdown component in general)

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#367]
__Describe the Bug__

It is currently impossible to scroll by dragging the bar in a Taglist dropdown, this leads to the dropdown being closed instantly. 

![image](https://user-images.githubusercontent.com/17801113/197101477-7c3b5227-a04b-496c-8685-0095c6d37170.png)

__Steps to Reproduce__

1. Add a Taglist to a form
2. Render the form (via the playground for example)
3. Try and drag the above pictured segment of the control (scrollbar)

__Expected Behavior__

This should instead drag like normal. 

__Environment__

- Found on Firefox and Chrome, most likely all browsers

**Comment by pinussilvestrus** [comment]
@Skaiir this is in ready for quite a while now. Do you think we will work on it soon, or should we move this back to the backlog?
