### ISSUE TITLE
Implement conditional rendering of forms

### ISSUE THREAD

**Issue by barmac** [bpmn-io/form-js#374]
__What should we do?__

* [x] As a form designer, I want to define a condition (FEEL unary test) under which field is displayed. 
* [x] As a form designer, I want to have editing support for the condition.
* [x] As a form designer, I want to use other fields' values as variables in the condition. 
* [x] As a user, I want to see only fields which have no condition or for which condition is met.
* [x] As a user, I want to submit only fields which have no condition or for which condition is met.

__Why should we do it?__

We want to allow users to decide whether field should be displayed based on given data.

**Comment by barmac** [comment]
I tackled the submission first. I still need to update this to take into account the data passed to the form. Unfortunately, I wasn't able to prepare a demo page. I should be working again on this on Thursday next week, and will setup the page next week.

**Comment by barmac** [comment]
Work is happening on https://github.com/bpmn-io/form-js/tree/374-conditional-rendering

**Comment by barmac** [comment]
Known issue: Condition field in the properties panel gets defocussed.

**Comment by barmac** [comment]
> Known issue: Condition field in the properties panel gets defocussed.

This is now fixed.

**Comment by barmac** [comment]
Although the submission data is filtered, the playground still shows even the removed variables. It seems this is due to playground using a private method of the form.

**Comment by Skaiir** [comment]
> Although the submission data is filtered, the playground still shows even the removed variables. It seems this is due to playground using a private method of the form.

Could you expand on that?

**Comment by Skaiir** [comment]
> As a form designer, I want to use any data given to form as variables in the condition. 

Some context to this, this will require changes to the `getSchemaVariables(schema)` method. C8 will only provide the bare minimum amount of data to the form, and this method is a way for us to tell them what data we rely on. This means that for all feel expressions, we need to somehow extract all the variable references as well. This is crucial for the feature.

I had a look at the WIP code and I noticed that you actually make use of that method to define the legal variables in the feel editor. Even though it wasn't the initial intention for it, it makes a lot of sense. But something which will be needed now is to actually complete the loop and extract variables from your feel expressions in the method. If you want to sync on this, just drop me a message on Monday.

**Comment by barmac** [comment]
> > Although the submission data is filtered, the playground still shows even the removed variables. It seems this is due to playground using a private method of the form.
> 
> Could you expand on that?

This:
https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-playground/src/components/PlaygroundRoot.js#L127

...while in my WIP implementation, I apply changes based on conditions in the `Form#submit` method. Gotta change that I guess.

**Comment by barmac** [comment]
> Although the submission data is filtered, the playground still shows even the removed variables. It seems this is due to playground using a private method of the form.

It's coming:

https://user-images.githubusercontent.com/28307541/201633558-876f75b4-0ec6-4d6b-af24-a1115414fef1.mov

**Comment by barmac** [comment]
I extracted https://github.com/bpmn-io/form-js/issues/402 because the solution will take more time but should not block the feature entirely.
