### ISSUE TITLE
Validate on blur

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#382]
__Is your feature request related to a problem? Please describe__

When users blur a required field, the validation does not start. It only starts after typing in something—and deleting the content again.

[IBM Carbon](https://carbondesignsystem.com/components/form/usage/#form-validation) describes to validate immediately after blur. This also helps to provide good a11y, since it allows screen readers and similar assistance devices to catch up with missing content before submission.

__Describe the solution you'd like__

Start field validation directly on blur.

**Comment by Skaiir** [comment]
This and https://github.com/bpmn-io/form-js/issues/323 need to be considered together.

**Comment by nikku** [comment]
Is this something that we apply properly in our properties panels? If not then I'd advocate to also improve the behavior there.
