### ISSUE TITLE
Allow conditional rendering / activation states

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#4]
__Is your feature request related to a problem? Please describe__

In my form I'd like to show, hide, enable or disable elements based on the state of other elements.

__Describe the solution you'd like__

* Conditional activation may be configured in the form description
* Example use-case described in context of interaction with [SUPPORT-12025](https://jira.camunda.com/browse/SUPPORT-12025):
  * If a tasklist / form-user selects a defined product-type (e.g., battery), then an additional part of the form is shown dynamically without re-load (e.g., form fields regarding environmental protection)

__Additional context__

Handled via a `conditional` section in `form.io`.

---

Related to [SUPPORT-12025](https://jira.camunda.com/browse/SUPPORT-12025)
Related to https://github.com/camunda/product-hub/issues/56

**Comment by Skaiir** [comment]
Closed, has been supported for a while now.
