### ISSUE TITLE
`getSchemaVariables` should include variables mentioned in conditions

### ISSUE THREAD

**Issue by barmac** [bpmn-io/form-js#401]
> As a form designer, I want to use any data given to form as variables in the condition. 

Some context to this, this will require changes to the `getSchemaVariables(schema)` method. C8 will only provide the bare minimum amount of data to the form, and this method is a way for us to tell them what data we rely on. This means that for all feel expressions, we need to somehow extract all the variable references as well. This is crucial for the feature.

I had a look at the WIP code and I noticed that you actually make use of that method to define the legal variables in the feel editor. Even though it wasn't the initial intention for it, it makes a lot of sense. But something which will be needed now is to actually complete the loop and extract variables from your feel expressions in the method. If you want to sync on this, just drop me a message on Monday.

_Originally posted by @Skaiir in https://github.com/bpmn-io/form-js/issues/374#issuecomment-1304045580_

**Comment by christian-konrad** [comment]
@barmac is this about exposing referenced input variables via the Tasklist API, so they are passed from Zeebe to Tasklist?

**Comment by Skaiir** [comment]
@christian-konrad Exactly that yeah.

**Comment by christian-konrad** [comment]
Perfect!

**Comment by pinussilvestrus** [comment]
@barmac we identified I have some capacity to tackle this one. Let's sync how I can support/take over the task from your plate 🙂

**Comment by pinussilvestrus** [comment]
A quick talk with @barmac:

* we need to update the [draft PR](https://github.com/bpmn-io/form-js/pull/423#issue-1459898699) to cover the latest condition schema
* we won't allow shadowing keywords (cf. https://github.com/bpmn-io/form-js/pull/423#issue-1459898699)
* we ignore the topic variables with spaces for now, potentially add a lint rule to discourage the use in expressions (once we see necessity)
* we saw one inconsistency in keys validation that we will handle separately: https://github.com/bpmn-io/form-js/pull/423#issue-1459898699 
* @barmac will cover the small changes regarding the schema and potentially merge the draft PR to the [overall conditional rendering PR](https://github.com/bpmn-io/form-js/pull/403)
