### ISSUE TITLE
Code in text view component overflows the editor/renderer and stops code rendering on paragraphs

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#411]
__Describe the Bug__

Code in text view component overflows the editor/renderer and stops code rendering on paragraphs.

__Steps to Reproduce__

See video:

https://user-images.githubusercontent.com/56470362/202215347-cdc2e0aa-8349-47c8-9186-cfec129ef22b.mov

__Expected Behavior__

Instead of overflowing, it should show a scrollbar:
![Bildschirmfoto 2022-11-16 um 16 00 04](https://user-images.githubusercontent.com/56470362/202215581-dff6741f-8c26-47b2-820f-3b1e8635c785.png)

Line breaks should be rendered properly:
![Bildschirmfoto 2022-11-16 um 16 00 51](https://user-images.githubusercontent.com/56470362/202215784-5d16d576-f705-4f8c-bcaa-067fc2640d2e.png)

__Environment__

- Recent forms playground

**Comment by nikku** [comment]
Could you share the form you used to reproduce this issue. You can append `.txt` to your `form.json` and upload it.

Regarding new-line handling we have to settle on a standard; common-mark vs. GitHub flavored markdown are two directions here. Common mark only mandates newlines (new paragraphs in fact) if two newlines are added, while GFM does explicitly allow you to break `<br/>` on single newlines.

What would you expect?

**Comment by nikku** [comment]
@pinussilvestrus Could you double check if this issue has all information you need / if this is still an issue? If not, let's close it.

**Comment by pinussilvestrus** [comment]
From what I can see, the overflow is not happening anymore.

![image](https://user-images.githubusercontent.com/9433996/220050428-cfaba68e-a823-4cd2-99be-79e5f335a3b7.png)

So I think we can close this one.
