### ISSUE TITLE
H6 header disappears in markdown text view

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#412]
__Describe the Bug__

We don't have the equivalent of an h6 with `######`—the header just disappears.

__Steps to Reproduce__

Create a text view with a h6 header—and it will disappear:

![Bildschirmfoto 2022-11-16 um 16 32 35](https://user-images.githubusercontent.com/56470362/202223587-27764814-6234-4d33-9013-a59bc630e3ce.png)

__Expected Behavior__

Show that header

__Environment__

- Latest playground as of Nov 16

**Comment by nikku** [comment]
Did not actually know `h6` is a thing. Needs to be whitelisted [here](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/render/components/Sanitizer.js#L10) :smile_cat:

**Comment by adrianmarinwork** [comment]
Hello coming from the issue #424 do you want me to take a look?

**Comment by pinussilvestrus** [comment]
@adrianmarinwork feel free to take a look and ask for help in case you need guidance 🙂 

We're happy to review any contribution you propose ❤️

**Comment by adrianmarinwork** [comment]
Hello, I've tried to run your repo locally but after using `npm install` any command that I run like `npm run all` breaks, the npm install it's indicating that 9 vulnerabilities are high and the other commands break.
Do you know something?

![image](https://user-images.githubusercontent.com/118568289/204060644-47839d2d-aa35-4056-8a71-fbbb42e59fe4.png)
![image](https://user-images.githubusercontent.com/118568289/204060656-65556566-160c-45a7-93f3-937d9d3e4189.png)

**Comment by christian-konrad** [comment]
@adrianmarinwork which version of npm do you use? It requires at least npm v7

**Comment by adrianmarinwork** [comment]
My version of npm is 8.19.2.
![image](https://user-images.githubusercontent.com/118568289/204137999-1846abe3-ccb6-419a-b57f-088a778f86d8.png)

**Comment by christian-konrad** [comment]
@pinussilvestrus this is interesting. Do you have any idea?

**Comment by pinussilvestrus** [comment]
The vulnerabilities come from dev dependencies. That's not uncommon for an npm project with such a number of deps. I also don't think that the build command is failing because of that reason.

@adrianmarinwork It rather seems like the `cp` is failing on your machine (given the logs you posted). Do you use Windows? Which shell are you operating on? `cp` should be available natively somewhere. Maybe @Skaiir also has some guidance here as a Windows user.

**Comment by Skaiir** [comment]
@adrianmarinwork Hey, thanks for starting to have a look. So the problem you're having is indeed what @pinussilvestrus was alluding to, the `cp` command is failing as it does not exist in windows CLIs. It looks like you're using Powershell, in general across our projects we use git bash, which should fix your issue.

**Comment by pinussilvestrus** [comment]
Also related: https://github.com/bpmn-io/form-js/issues/214

> We should simply use a node wrapper around cp and we are good. 

Maybe it's a good time to do that. I can follow up.

**Comment by adrianmarinwork** [comment]
@Skaiir You were right! Running the commands in the git bash fixed the problem.
But I'm sorry, I come back with another issue hehe.
When running for example the command `npm start` I get the error shown in the screenshots below, also the `npm run all` endups crashing. My computer does not want me to add the H6 header :P

![image](https://user-images.githubusercontent.com/118568289/204387158-5e2f3102-c87c-435c-bc9b-14a960534b45.png)
![image](https://user-images.githubusercontent.com/118568289/204387223-08c7f631-2163-41f6-82f2-37c6d47bbacd.png)

**Comment by Skaiir** [comment]
@adrianmarinwork My guess is that you're using node 17/18. We actually only recently upgraded our projects to node@16 but considering the current LTS version is 18 it makes sense that it should be supported. 

What I would advise here, would be to, using nvm, install node 16 and give it a go. We'll tackle the upgrade on our side eventually when there's capacity, but for now I'll raise a new issue for this. Hopefully this should sort things out for you :)

**Comment by nikku** [comment]
> @adrianmarinwork My guess is that you're using node 17/18. We actually only recently upgraded our projects to node@16 but considering the current LTS version is 18 it makes sense that it should be supported.

It is indeed Node 18 + Webpack 5 issue. There exists an ugly workaround (cf. https://github.com/jupyterlab/jupyterlab/issues/11248 or others), but I believe there is little value to jump onto the bleeding edge.

**Comment by adrianmarinwork** [comment]
After installing the node v16 as @Skaiir said, looks like I've managed to add the `h6` with markdown syntax, or atleast thats what some console log are showing me in the function `markdownToHTML` look:
![image](https://user-images.githubusercontent.com/118568289/204920939-bb536736-5151-48eb-b148-652ae18dd711.png)
Do you want me to create a pull request or I am missing something (probably)?

**Comment by Skaiir** [comment]
Maybe you are missing something but it'll be hard to tell until we see the PR. But from what I can see it works, so early congrats on your contribution 😄. 

What I'll say is that usually, for first-time contributors, the main problems are: 

- lack of test coverage
- messy formatting / not respecting our lint rules

If you aren't certain about how to respect these things, what I can suggest for visibility is to create a draft PR, so we can chat with the code under our eyes.

**Comment by adrianmarinwork** [comment]
Okay, I have created a pull request with the change, it's something pretty small. 
By the way your app looks pretty cool and this kind of code is something that I've never seen before, nice to see something new. :)
