### ISSUE TITLE
Inconsistent validation for `key` and `valuesKey`

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#428]
__Describe the Bug__

In the properties panel, we do not allow spaces in form field keys.

![image](https://user-images.githubusercontent.com/9433996/203754051-ec508c48-685e-4b96-ab66-d74496bcee0a.png)

We don't do the same for the "Input values key".

![image](https://user-images.githubusercontent.com/9433996/203754129-a13c5fb1-37f4-4779-9faa-41cd4ef9a896.png)

__Steps to Reproduce__

1. Open forms editor
2. Select a multi-select element (e.g. `taglist`)
3. Enter variable name with spaces in `Key` => spaces are not allowed
4. Enter variable name with spaces in `Input values key` => spaces are allowed

__Expected Behavior__

Be consistent when declaring variable keys in form fields.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 107.0.5304.110
- OS: macOS 11.7
- Library version: `develop`

**Comment by RomanKostka** [comment]
@pinussilvestrus - this should be definitely be consistent. 
I am no expert but i guess values should not contain any spaces due to readability?
What is our general advice when it comes to this?

**Comment by pinussilvestrus** [comment]
Variables with spaces are not supported in either C7 or C8 from what I know. As form-js should be agnostic, you could argue there should not be any restriction in the properties panel but rather be lint rules for the errors panel.

**Comment by RomanKostka** [comment]
thanks for clarification.
i would anyhow propose to let the user know if they made a mistake in the properties panel. 
With that you avoid users to become frustrated when entering a wrong value and noticing it too late
