### ISSUE TITLE
Allow specifying text view content via FEEL expression

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#436]
__Is your feature request related to a problem? Please describe__

With #385 we enable properties to be FEEL optional. This opens up several chances to make form fields more flexible via input data and expressions. 

One use case is the `text` component content, which can be static or dynamically filled via an expression.

![image](https://user-images.githubusercontent.com/9433996/204495390-c5122a54-3bdd-49f4-b390-b2f38a0d166b.png)

![image](https://user-images.githubusercontent.com/9433996/204495439-b4db77a9-8f82-468d-86e8-dad9837b90fa.png)

__Describe the solution you'd like__

Enable FEEL support for `Text`.

* [ ] replace Text properties panel entry with a FEEL optional textarea
* [ ] show editor placeholder if a FEEL expression is specified
* [ ] show editor placeholder if nothing is specified
* [ ] rename "Text" to "Text view" to be consistent with image views

__Describe alternatives you've considered__

/

__Additional context__

Child of https://github.com/camunda/team-hto/issues/79
Related (but not necessarily the same) to https://github.com/bpmn-io/form-js/issues/247

**Comment by pinussilvestrus** [comment]
**Kickoff Summary** @christian-konrad @Skaiir @RomanKostka @vsgoulart 

Find the board here: https://miro.com/app/board/uXjVP-uHh4o=/
* we will implement via the FEEL optional field as planned
* we will invest in proper placeholders
* we will not worry about mustache now

**Comment by pinussilvestrus** [comment]
> we will invest in proper placeholders

The most pragmatic solution for the editor, without any custom styling.

a) no text content at all

![image](https://user-images.githubusercontent.com/9433996/205258587-bf0fd724-c37c-42b5-a200-71cb7909617b.png)

b) expression specified

![image](https://user-images.githubusercontent.com/9433996/205258658-478fbc7b-2380-4fab-8354-581304582ca2.png)

c) static content (as before)

![image](https://user-images.githubusercontent.com/9433996/205258733-2783a4ce-f5ac-49c3-b30b-c7cd04802ec0.png)

Wdyt @RomanKostka @christian-konrad?

**Comment by pinussilvestrus** [comment]
> We could consider making this one italic to act as a proper placeholder.

![image](https://user-images.githubusercontent.com/9433996/205260460-4419a742-5a39-4e4d-8600-3475f8553c96.png)

**Comment by Skaiir** [comment]
![image](https://user-images.githubusercontent.com/17801113/205265581-3f7ecb08-402a-4414-94b6-e8b65648ea3e.png)

Or we can just do all of the above and more. 

I think what matters is that the text has enough visual identity that it can be easily recognized as an expression.

**Comment by Skaiir** [comment]
Oh, actually I just realized I just looked at the above examples and thought you were talking about labels.  Which is itself kind of an argument that this might not be enough visual identity.

**Comment by Skaiir** [comment]
I'll rewrite some thoughts because the previous ones were more chaotic than usual.

- We should define a visual identity for the concept of dynamic evaluation. That is to say, at a glance in the editor, we immediately see what is dynamically evaluated. I think color might be our best bet to convey this, as we already use it sparingly, but this is more of a design topic that @RomanKostka might be able to help with. 
- We also should make it obvious what component we're looking at in the editor. When I first had a look I thought it was a label honestly. My hunch is most expressions will be short like this, so I think in these cases we'll need to supplement with a kind of placeholder like that of the image view IMO.
- Just pre or just italics is a bit too subtle in my opinion which will make things harder on the eyes.

**Comment by Skaiir** [comment]
Also, before we commit to any particular approach, we should really try and model at least a mid-sized form with that approach. I think this topic is way more complex than it first seems from a UX standpoint, and has potential to look very messy if done wrong. So let's cut out assumptions and just see what the forms would look like before committing. 

It's important to note that whatever approach we chose here will have to be chosen with the future in mind. What if we have dynamically evaluated labels, how will that look like? What about dynamic adorners, that's pretty much going to be a requirement. Dynamic descriptions of fields... you get my point.

**Comment by pinussilvestrus** [comment]
Thanks for your feedback @Skaiir. 👍 I created a general issue to investigate a proper concept for this: https://github.com/camunda/team-hto/issues/84

On the same run, I believe we should not block ourselves. Let's start with a pragmatic first solution and continue on developing a general strategy for the editor placeholders.

**Comment by Skaiir** [comment]
Yeah since this isn't schema related, we can always release something pragmatic now and have something more generic in the future. 👍

**Comment by RomanKostka** [comment]
> On the same run, I believe we should not block ourselves. Let's start with a pragmatic first solution and continue on developing a general strategy for the editor placeholders.

Totally agree!

I was always in favor of the current situation ( static display ):
<img width="359" alt="image" src="https://user-images.githubusercontent.com/114994124/205279692-5bf37b0d-bf3a-43f9-9b44-548d295f6c4d.png">

I would propose that if the user enters an expression we should display that the text view will populated by an expression.
Something like this:
<img width="665" alt="image" src="https://user-images.githubusercontent.com/114994124/205280611-2bc34983-4e7f-48b9-a229-c56bb7fceac4.png">


That would do the job for now and we can work on creating an overall concept for the placeholders

**Comment by pinussilvestrus** [comment]
I created a draft for this via https://github.com/bpmn-io/form-js/pull/447. Feel free to [try the demo](https://demo-436-text-component-feel--camunda-form-playground.netlify.app/) for a quick look & feel.

**Comment by christian-konrad** [comment]
> We could consider making this one italic to act as a proper placeholder.
> We could also consider wrapping this into a pre tag.

Yes, that's super clear and looks good

**Comment by christian-konrad** [comment]
@pinussilvestrus lgtm, but let's consider in the separate issue:

Show the expression like initially proposed since this helps to convey the structure and information context of the form without the need to open the preview.

![Bildschirmfoto 2022-12-02 um 13 17 19](https://user-images.githubusercontent.com/56470362/205291208-9504e234-5229-4a03-9d8c-c85b6d74b8d0.png)

**Comment by Skaiir** [comment]
For now, I do like Roman's suggestion/demo

I would suggest this extra styling at the very least though:

![image](https://user-images.githubusercontent.com/17801113/205291510-26a2b13b-40ee-457c-851f-b3656c18eaa9.png)

```
.fjs-container .fjs-form-field-placeholder {
	padding: 8px 0;
	font-style: italic;
}
```

Later on, I think for the reasons mentioned by Christian this might not be enough. Although, I'm still not sure the expression is the way to go.

**Comment by christian-konrad** [comment]
@pinussilvestrus bug with interpreting results of explicit string casting that creates anchor tags that lead out of the form:

https://user-images.githubusercontent.com/56470362/205292599-98bd6b3f-3f07-42fe-9ecc-a55be9cbeffe.mov

**Comment by Skaiir** [comment]
What about iconography to solve our readability issue:

![image](https://user-images.githubusercontent.com/17801113/205293231-1132976a-8d28-4804-be3e-0a9a078aa7d5.png)

**Comment by pinussilvestrus** [comment]
> @pinussilvestrus bug with interpreting results of explicit string casting that creates anchor tags that lead out of the form:
> 
>  Bildschirmaufnahme.2022-12-02.um.13.25.00.mov

I'm not sure whether this is a bug but rather how it works (FEEL and markdown)

Note that [FEEL stringifies array to this form](https://nikku.github.io/feel-playground/?e=string%28vegetables%29&c=%7B%0A++%22vegetables%22%3A+%5B+%22garlic%22%2C+%22tomato%22+%5D%2C%0A++%22Mike%27s+age%22%3A+35%0A%7D&t=expression). As the result is `"['regional-manager', 'approval']"`, the text view renders it as markdown, which is a link indeed.

![image](https://user-images.githubusercontent.com/9433996/205294437-ed5ab820-cc41-4d92-bef0-60b078222315.png)

**Comment by pinussilvestrus** [comment]
> What about iconography to solve our readability issue:
> 
> ![image](https://user-images.githubusercontent.com/17801113/205293231-1132976a-8d28-4804-be3e-0a9a078aa7d5.png)

I like! Maybe a good time to make the type icons available in the viewer, [not only in the editor](https://github.com/bpmn-io/form-js/tree/develop/packages/form-js-editor/src/render/components/icons).

**Comment by pinussilvestrus** [comment]
I tried the approach from @Skaiir and deployed it[ to the demo](https://demo-436-text-component-feel--camunda-form-playground.netlify.app/).

![image](https://user-images.githubusercontent.com/9433996/205304059-cfa7aff0-7df6-4d65-b751-8dc482659bd4.png)

![image](https://user-images.githubusercontent.com/9433996/205304178-42e773c5-3d10-4f25-9c64-8e93df6f9be0.png)
