### ISSUE TITLE
Renaming of properties

### ISSUE THREAD

**Issue by RomanKostka** [bpmn-io/form-js#454]
__Is your feature request related to a problem? Please describe__
To help users understand the required input for properties we could change the naming of some properties

__Describe the solution you'd like__
Rename following properties:

1. Regular expression validation -> Regular expression pattern
![image](https://user-images.githubusercontent.com/114994124/205917478-d2713434-7b31-42ba-bf44-8bf392e2864f.png)

2. Regular expression pattern -> Custom regular expression
![image](https://user-images.githubusercontent.com/114994124/205917503-ec78960e-6dc9-41af-b88c-ab6723efa94e.png)

3. Serialize to string -> Output as string
![image](https://user-images.githubusercontent.com/114994124/205917542-d44c30c1-7482-4468-9b2b-b5cc4cb6f958.png)

__Describe alternatives you've considered__
Tooltips could users understand it also - but that would be only a workaround

**Comment by Skaiir** [comment]
We've decided to change regular expression pattern to simply 'Validation pattern', as we do not necessarily want to commit to regex as our only way of validating fields.
