### ISSUE TITLE
Expand drop target horizontally

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#461]
__What should we do?__

Expand the drop target horizontally (overflow the width limits of the form).

__Why should we do it?__

On larger screens, users might fail to add components since they don't know where the drop target in the center is, and might get the impression that components can't be dropped.

![image](https://user-images.githubusercontent.com/56470362/207259238-59af9662-eb8a-4607-923e-bea4a9855aca.png)

Cf. https://camunda.slack.com/archives/C6GBS7DKL/p1670872972975049

__Alternative__

When dragging, clearly highlight the drop area.

**Comment by pinussilvestrus** [comment]
@christian-konrad do you have any screenshot how the drop area is drawed in other tools?

**Comment by pinussilvestrus** [comment]
Observation: the drag/drop container is currently the root form children element. 

![image](https://user-images.githubusercontent.com/9433996/207294779-89a9a170-19cf-421b-8648-599cb97e5cad.png)

@christian-konrad We could change this by setting the drag/drop container to a parent and setting the max-width to the children itself. Note that this is a form-js core change then (not necessarily breaking).

![Bildschirmfoto 2022-12-13 um 11 33 03 (2)](https://user-images.githubusercontent.com/9433996/207294607-5d199471-4184-4edb-80d7-8d86f54adc3b.png)

Alternative: show a drop hint if you are not in the drop area, as we do in the Desktop Modeler in general.

![Bildschirmfoto 2022-12-13 um 11 36 17 (2)](https://user-images.githubusercontent.com/9433996/207295207-5f014b3a-cbf2-4e29-8203-e302b4cd4b74.png)

**Comment by pinussilvestrus** [comment]
> This way form-js could simply add a class to indicate this state and form-playground could add a certain border to indicate this drop area. Let us play around with this.

I created [a follow-up issue](https://github.com/bpmn-io/form-js/issues/462) for this, this could be a nice little improvement so, e.g. the playground could react on certain drag-and-drop events.

**Comment by pinussilvestrus** [comment]
> Alternative: show a drop hint if you are not in the drop area.

In the playground, do

```css
.gu-unselectable .cfp-root .fjs-children.fjs-drag-container {
  border: 2px dashed var(--color-blue-205-100-45);
}
```

![Kapture 2022-12-13 at 13 38 26](https://user-images.githubusercontent.com/9433996/207320419-ce76ce5c-3e2d-4fee-b997-df74a5fecd21.gif)

**Comment by christian-konrad** [comment]
@pinussilvestrus I like the media query; only showing this when it is helpful is a great experience

> do you have any screenshot how the drop area is drawed in other tools?

This is Retool:

https://user-images.githubusercontent.com/56470362/207557929-0dc1ff83-00ca-4756-b680-fa5db47f5f66.mov

Since it is way more complex then a single form, it draws drop area borders around any drop target container (indicating that it will result to be a child of this parent component)

**Comment by pinussilvestrus** [comment]
@christian-konrad should we close this issue? As I understood we won't expand the drop zone but rather make it more explicit via `camunda/form-playground`.

**Comment by pinussilvestrus** [comment]
I'll close this one as I think we won't follow up on this one anytime soon. Feel free to re-open.
