### ISSUE TITLE
Add possibility to hook into dragula events

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#462]
__Is your feature request related to a problem? Please describe__

Sometimes, it makes sense to listen to specific `dragula` events.

One use case for `@camunda/form-playground` is to add custom styling during drag operations, add certain behaviors once an element is dropped, etc. 

Currently, [the `drake` instance is for internal use only](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-editor/src/render/components/FormEditor.js#L177).

__Describe the solution you'd like__

Make it possible to listen for specific `drake` events, e.g.

```js
formEditor.on('dragula.drag', ...);
formEditor.on('dragula.dragend');
formEditor.on('dragula.over');
```

__Describe alternatives you've considered__

Expose the whole `drake` instance.

```js
const drake = formEditor.get('drake');

drake.on('drag', ...);
```

However, this would lock our used dragging library pretty much, as replacing it would mean a breaking change. Note that we already fire such events as

```js
eventBus.on('dragula.created');
eventBus.on('dragula.destroyed');
```

__Additional context__

Related to https://github.com/bpmn-io/form-js/issues/461#issuecomment-1348157790

**Comment by christian-konrad** [comment]
@pinussilvestrus now, we can better highlight the drop target in the editor when dragging a component, right?

**Comment by pinussilvestrus** [comment]
At least we can remove the hacky implementation in `form-playground` and build something more sophisticated on top of our own API 👍 Feel free to open an issue in `form-playground` 👍

**Comment by christian-konrad** [comment]
@pinussilvestrus what about documenting this in the repo's readme?

**Comment by pinussilvestrus** [comment]
As by now, there is no dedicated documentation on events that got thrown in the editor. I opened an issue to handle this one: https://github.com/camunda/team-hto/issues/134
