### ISSUE TITLE
Nested component keys

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#464]
__Is your feature request related to a problem? Please describe__

Users want to map a component to a nested value in their form context, which is currently not possible.

![image](https://user-images.githubusercontent.com/56470362/207553884-6dfb90ed-6c9b-40ac-af82-00683931e4a6.png)

__Describe the solution you'd like__

Multiple potential solutions:
* Allow to access nested properties using "." in a string notation
* Same, but as (optional) FEEL (with autocompletion)
    * But autocompletion will only work when key is already provided in input vars
    * Does it feel right to declare a key this way?
    * You could create dynamic keys this way using expressions, and this is tricky and we probably don't want this.
    * These are then more like "binding/assignment expressions" instead of keys

Overall, we need to think about if we need to take care (how?) that you can't override a full object by using the nested keys. Just checking for uniqueness doesn't work then. Example: you have `{ "foo": { "bar" : 1 } }` and assign both `foo` and `foo.bar` as keys. What will have precedence?

* A "nested context" container wrapping other components
    * It acts as a field group or even an invisible component
    * You map this container to a key, and every component inside of it can map to the properties inside the object of that key
    * Probably too complicated for the average form designer

__Describe alternatives you've considered__

* Don't allow this and show a tooltip on the key property to explain this limitation
* Allow to make the key optional, and use of assignment expressions (like above, but again, conflict resolution/object merge precedence is a challenge)

__Additional context__

* https://forum.camunda.io/t/camunda-8-forms-json-value-in-key/39736/4
* https://camunda.slack.com/archives/C01QYD808A3/p1670940398711989

**Comment by Skaiir** [comment]
Similar issue: https://github.com/bpmn-io/form-js/issues/326

**Comment by Skaiir** [comment]
The main issue with this is that '.' can be used in a string. Well this will need more consideration so let's leave it for now. Maybe something somewhat simple would be using an array of strings. 

Something like

`[ 'parentObject', 'childParameter.1' ]`

to target

```
{
  'parentObject': {
     'childParameter.1': value1
     'childParameter.2' : value2
  }
}

**Comment by upgradingdave** [comment]
For what it's worth, if at all possible, I vote to implement this feature using `dot` syntax. The `dot` syntax is already used 
 when mapping BPMN task input and output variables, for example: 

![Screen Shot 2023-08-14 at 4 13 44 PM](https://github.com/bpmn-io/form-js/assets/939229/456940e8-7047-43ff-bd55-0cbdb0a31c8e)

The `dot` syntax is also available in the form templating markdown syntax like `{{parentObject.childObject}}`.

So, people are already familiar with this syntax. 

I understand there might be technical challenges and I can see how implementing with array syntax might be cleaner from code perspective, but from a user's perspective I think it'll save a lot of confusion if folks can simply write keys with the `dot` syntax. 

I'm sure it's easier said than done! But if at all possible, I vote for `parentObject.childObject` 🙂

**Comment by Skaiir** [comment]
@upgradingdave Agreed, let's do it that way :)

**Comment by Skaiir** [comment]
Implemented via https://github.com/bpmn-io/form-js/pull/768
