### ISSUE TITLE
Add Basic Layout Component

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#47]
Introduce a new type of field that exists only for layout purposes.

This involves

* [ ] supporting layout-only fields that can be used to group fields
* [ ] supporting titles for layout-only fields
* [ ] supporting layout options (user can choose between horizontal or vertical layout)

----

Questions to answer: Is this going to be a single component, or are there dedicated components for horizontal ("columns") and vertical ("fieldset" #258) stacking?

**Comment by philippfromme** [comment]
### Initial Sketch by @philippfromme 

<img width="100%" alt="chrome_udDZBYtThl" src="https://user-images.githubusercontent.com/7633572/114020309-bf1be400-986f-11eb-9e50-4bf5f5928c26.png">

**Comment by christian-konrad** [comment]
@philippfromme @pinussilvestrus @Skaiir  @nikku 

This is not trivial: There are multiple ways to layout (Flexbox, Grid, Cols/Rows), and we need to find the appropriate one. We should not support all, but the most suitable solution. The approach of @philippfromme looks like Flexbox, which is in my opinion the easiest and best solution - it gives you both horizontal and vertical layouting, you can stack it, you can tell it to wrap on insufficient space, you can set the flex property to make one column larger then others...

We also need to consider how other components (that actually change the json output) can be corporated, where are the intersections between the properties set and so on (example: Should layout-only components have conditional rendering or only logical components?).

But additionally, we would also need to improve the editor navigation, as the bounding boxes of the layout components may overlap and we need to jump to the parent component easily via UI and keyboard (esc) (see the mockups and compare with other tools).

Also see the mockups to compare the different layouting approaches.

![FieldsetAsCard](https://user-images.githubusercontent.com/56470362/170003620-6770c804-7d30-4bf0-9911-425a8ebceae1.png)
![FieldsetAsCollapsible](https://user-images.githubusercontent.com/56470362/170003630-1d4ac942-8da8-4abd-a071-ace1ab3cc0f9.png)
![FieldsetClassic](https://user-images.githubusercontent.com/56470362/170003637-70b4d2e5-d973-4c9d-a5ad-f26d92b8a77e.png)
![FieldsetSelected](https://user-images.githubusercontent.com/56470362/170003641-df724e0c-ec3a-4407-9b32-9a68b9083156.png)
![FIeldsetUnselected](https://user-images.githubusercontent.com/56470362/170003646-9e5e6a51-b2da-467f-9572-6cc08787573a.png)
![Flexbox](https://user-images.githubusercontent.com/56470362/170003653-ebbe9131-1f2d-4f62-bc80-afa6339d7712.png)
![FlexRow](https://user-images.githubusercontent.com/56470362/170003657-44dc5b44-4de4-4248-907c-162084c05176.png)

**Comment by nikku** [comment]
Thanks for https://github.com/bpmn-io/form-js/issues/47#issuecomment-1135679921, @christian-konrad. I think given your input it is clear that we should not merge fieldsets (#258)  feature immediately, but rather discover what we want before continuing.

**Comment by christian-konrad** [comment]
After some discovery, we found that we should not introduce a layout component, but rather introduce an implicit layout.
See https://github.com/camunda/team-hto/issues/50 and this demo: https://christian-konrad.github.io/form-drag-layout/editor.html
