### ISSUE TITLE
Separator component to visually emphasize field groups

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#480]
__Is your feature request related to a problem? Please describe__

With the new components and text view features, it can get quite difficult to visually differentiate groups of fields/components, as shown in this example.

![Bildschirmfoto 2023-01-04 um 10 40 00](https://user-images.githubusercontent.com/56470362/210526503-a291d99c-a096-4ff2-ae29-fbc10d96a6b8.png)

__Describe the solution you'd like__

To visually emphasize separate groups/blocks of fields/components, a separator component (a horizontal line) is a simple, but helpful tool.

![Bildschirmfoto 2023-01-04 um 10 41 09](https://user-images.githubusercontent.com/56470362/210526687-140a5f21-f64a-46d0-8bb0-cf438bd4725a.png)

__Describe alternatives you've considered__

Support "---" in the text view markdown. But I advise against it, since it is hard to discover. A dedicated component is easier to find.

**Comment by Skaiir** [comment]
@RomanKostka Of interest

**Comment by volodymyr-melnykc** [comment]
As a part of this issue, we're introducing a horizontal separator component.
The component is named "Separator".

To help the user visually differentiate components, we're also updating the icon for the Spacer component that already exists.

Below are visual references.

![separator icon](https://github.com/bpmn-io/form-js/assets/143816833/cdc030af-237c-4e7b-a74a-90245390bb52)
![spacer icon](https://github.com/bpmn-io/form-js/assets/143816833/4e5df14c-ef1d-4446-a561-b75730395fd4)

<img width="778" alt="image" src="https://github.com/bpmn-io/form-js/assets/143816833/7237c256-646d-4632-8f57-b5c181cec800">
