### ISSUE TITLE
Number field validation minimum 1 allows 0

### ISSUE THREAD

**Issue by datakurre** [bpmn-io/form-js#486]
__Describe the Bug__

On form-js 0.10.1 (and earlier) minimum >= 1 validation on Number field allows 0 (zero).

![number-greater-than-zero](https://user-images.githubusercontent.com/160447/211189917-c4d86c16-b70d-44c2-a436-65aa5f311566.png)

__Steps to Reproduce__
```
{
  "components": [
    {
      "label": "Number",
      "type": "number",
      "id": "Field_1sc38wm",
      "key": "field_1qzvtjc",
      "validate": {
        "required": true,
        "min": 1,
        "max": 5
      }
    }
  ],
  "type": "default",
  "id": "Form_1k6ojko",
  "executionPlatform": "Camunda Cloud",
  "executionPlatformVersion": "8.1.0",
  "exporter": {
    "name": "Camunda Modeler",
    "version": "5.7.0-nightly.20230107"
  },
  "schemaVersion": 6
}
```

__Expected Behavior__

Validation error should be shown.

**Comment by Skaiir** [comment]
Thanks for raising, will look into this.

**Comment by Skaiir** [comment]
Will be available in the next release.
