### ISSUE TITLE
Disabled `taglist` fields do not show imported values

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#496]
__Describe the Bug__

When specifying input data for a disabled `taglist` field, the viewer does not show the values, but instead only the placeholder.

![image](https://user-images.githubusercontent.com/9433996/212069850-0fca4d0c-c578-4b99-8e2e-f27df7808222.png)

![image](https://user-images.githubusercontent.com/9433996/212069888-d43879a5-bb9d-4ffa-b89d-bad67be26a49.png)

This is inconsistent with other fields, where we still display the value while disabled. 

![image](https://user-images.githubusercontent.com/9433996/212070433-48359cc0-9ca0-4d37-83d0-8aa9e9314862.png)

__Steps to Reproduce__

1. Create a `taglist`
2. Specify input data for that `taglist`
3. Disable the `taglist`
4. See no values are shown

__Expected Behavior__

Like for other fields, the `taglist` values should be shown also in `disabled` mode.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 108
- OS: macOS
- Library version: 0.10.1

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/512
