### ISSUE TITLE
Add ability to display and edit list elements

### ISSUE THREAD

**Issue by nikku** [bpmn-io/form-js#5]
__Is your feature request related to a problem? Please describe__

In my form I'd like to have the ability to edit list elements. 

Example: A list of invoices that are uploaded, a list of items to be double checked.

__Describe the solution you'd like__

* Be able to define a list element container that can hold arbitrary child elements as contents.
* List element container should have the ability to add or remove elements from the list (configurable)

__Describe alternatives you've considered__

People need to contribute list elements as custom components.

__Additional context__

Supported by `form.io` via the `datagrid` component.

**Comment by Skaiir** [comment]
Finally being tackled and soon to be PRd, tracking is here: https://github.com/bpmn-io/form-js/issues/796

Closing as dupe.
