### ISSUE TITLE
Consider using semantic CSS variables/themes

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#515]
### What should we do?

In design systems like [Carbon](https://carbondesignsystem.com/) they make use of semantic themes/CSS variables like `var(cds--text-primary)` for text colors. This makes it easier to reuse colors, it simplifies customization (eg when implementing dark and light themes)

### Why should we do it?

- Avoid creation of multiple repeated CSS vars
- Speeds development by just reusing basic  vars
- Simplifies customization

**Comment by pinussilvestrus** [comment]
> Avoid creation of multiple repeated CSS va

Can you give some examples on this one? I'd assume it's about having a variable for text colors inside the palette/form/properties panel vs. having one for all.

I remember we have a variable `color-text` in the viewer scope that should (not sure whether this is a case already) be re-used in the more fine grained variables. This way as a customizer you can override all or only some of the text colors.

One another question: do you know how fine grained Carbon is doing that (as an inspiration)? Do they have variables also for borders, paddings and so on? Which rule should we follow?

**Comment by vsgoulart** [comment]
> Can you give some examples on this one? I'd assume it's about having a variable for text colors inside the palette/form/properties panel vs. having one for all.

I probably should have explained it a bit better, but I meant that we wouldn't have to keep defining vars like you did in [here](https://github.com/bpmn-io/form-js/pull/505/files#diff-eb0fd984b792ec0985e5ce3b41ef6e018adeef06b255b0e8e5fa6080945d251eR18-R38)
If we had defined semantic tokens like `text-primary` and `text-secondary`, we could just define rules to when to use them. For example, the inputs use `text-primary` for the input value color and the descriptions of the input use `text-secondary`. This way we wouldn't have to define new vars for each component.
Another example from your PR, you defined `color-palette-search-icon` in Carbon that would have been just `icon-primary` (`icon-disabled` if the icon was in a disabled state)

> One another question: do you know how fine grained Carbon is doing that (as an inspiration)? Do they have variables also for borders, paddings and so on? Which rule should we follow?

They do have variables for border colors. For paddings they have [spacing tokens](https://carbondesignsystem.com/guidelines/spacing/overview), that can be used for paddings and margins.

I think that for a starting point we could focus more on the colors, and then think of spacing vars. Since for colors we already use variables most of the time.

**Comment by vsgoulart** [comment]
[Here's the semantic color variables that Carbon uses](https://carbondesignsystem.com/guidelines/color/usage)

**Comment by pinussilvestrus** [comment]
Thanks for the explanations! I know get that we should continue the variables we already used in the [viewer styles](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/assets/form-js.css#L37), but consistently and to an higher extent.

What I'm still wondering: would we loose something if we still use color definitions as `--color-palette-search-icon: var(--color-icon-primary)` to also allow overriding styles in a more fine grained manner? You'd still have the choice then, use the system we provide, override everything or override just a specific one.

I agree on starting simple with the colors 👍 Context: we might need to adjust our colors scheme anyway slightly to be more consistent with other parts of our products, probably a good time to do this clean ups (/cc @RomanKostka).

**Comment by vsgoulart** [comment]
> What I'm still wondering: would we loose something if we still use color definitions as --color-palette-search-icon: var(--color-icon-primary) to also allow overriding styles in a more fine grained manner?

I'm not against it, but we would be giving the user the possibility of potentially shooting themselves in the foot by having inconsistent theming :sweat_smile:
This is something we would have to consider if we implement this. My take right now would be to have fine-grained vars, but maybe not encourage it (but I need to think a little bit more about it)
