### ISSUE TITLE
Adjust scalable component library search according to searching standards

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#532]
### What should we do?

We should look around at other tooling with similar and try to ascertain what the searching logic for the scalable component library should look like. The reason why I think this might be worth something is that at the present time it can still be a little rough:

![image](https://user-images.githubusercontent.com/17801113/216206868-624886e3-95ab-49d5-9b4f-8decfcc90835.png)
![image](https://user-images.githubusercontent.com/17801113/216206979-99baca75-3bfc-459b-b4cf-0985af244614.png)

**Ideas I think we could look at:**
- make the search spacing agnostic
- change the current 'space' behaviour of acting like a logical **AND**

### Why should we do it?

To provide intuitive UX out of the box.

**Comment by Skaiir** [comment]
@pinussilvestrus Just raised this, don't think it's a huge deal right now but I noticed this playing around with the scalable component library

**Comment by nikku** [comment]
Could be worth double checking if this works similar to create/append anything and/or the diagram-js built-in search. I think at some point we'd want to settle down on a standard behavior. What I could even imagine if that we pull out "search in collection" into a re-usable utility, where tokens must be provided by the integrator, but actual search (matching) is handled within the lib.

**Comment by Skaiir** [comment]
Woops missed this comment and already merged. Well, I'll keep the issue open to not forget and will check soon.

**Comment by pinussilvestrus** [comment]
> Could be worth double checking if this works similar to create/append anything and/or the diagram-js built-in search. I think at some point we'd want to settle down on a standard behavior. What I could even imagine if that we pull out "search in collection" into a re-usable utility, where tokens must be provided by the integrator, but actual search (matching) is handled within the lib.

I believe on the first version we simply mirrored the behavior of create/append anything once we implemented the new palette.

That might change though. Having a standardized behavior somewhere would be really nice!

**Comment by Skaiir** [comment]
I'm going to close this issue as it no longer represents what it initially was opened up for, a small follow-up for the homogenization of the searching algorithms can be found here: https://github.com/bpmn-io/form-js/issues/730
