### ISSUE TITLE
In the forms viewer, I cannot submit empty fields

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#54]
__Describe the Bug__
When the content of an pre-filled textbox was deleted, the submit event does not contain the form field in `data`.

Background: In Platform Tasklist, the Process Variable will not be updated in this scenario. Because we pass all process variables into the form, we cannot reliably check whether a variable was deleted by the absence of it.

__Steps to Reproduce__

1. Use a form with pre-filled data
2. Delete all content in the form (it is now empty)
3. Submit the form
4. The result object is empty

Example:
```js
const schema = {
  "type": "default",
  "components": [
    {
      "key": "creditor",
      "label": "Creditor",
      "type": "textfield"
    },
    {
      "key": "button1",
      "label": "Submit",
      "type": "button"
    }
  ]
};

const data = {creditor: "foobar"};
const form = createForm({
  schema,
  data,
  container: document.querySelector('#form')
});
form.on('submit', (event) => {
  console.log(event.data, event.errors);
});
```

__Expected Behavior__

The result should include the field with an empty string.

```
{creditor: ""}
```

More generally speaking, every displayed field should yield a result in the submitted form, cf. https://github.com/bpmn-io/form-js/issues/54#issuecomment-818654075.

__Environment__

- Host (Browser/Node version), if applicable: Chrome 89
- OS: Ubuntu 18.04
- Library version: 0.0.12

**Comment by nikku** [comment]
Thanks for opening this issue. An interesting case, indeed.

Does it make sense to do the diffing outside the form library? Or is this something that should strictly be handled inside the form library?

**Comment by marstamm** [comment]
I think it would make more sense to have the diffing inside the form library. Would it make sense to always include enabled fields, even when they are untouched and empty? This way, it is clear what fields are present in the form.

For the diffing to work outside of the library, we would also need a utility function to know which keys/variables are used in the form. Currently, we sometimes pass data into the form that is not used by the form. These unrelated variables should not be cleared as a side effect.

**Comment by nikku** [comment]
If we do it inside the form library, we need to be 100% sure on the semantics. Let us consider the following scenarios:


| Input data | Action | Output (submitted value) |
|:---|:---|:---|
| `{}` | submit | `{ creditor: '' }` |
| `{ creditor, foo }`|  | `{ creditor }` |
|  `{ creditor }` | creditor field cleared | `{ creditor: '' }` |
| `{ creditor }` | creditor not renderered, i.e. due to a conditional rendering rule | `{ }` |

Future work in this area is expected, cf. https://github.com/bpmn-io/form-js/issues/6, too.

**Comment by nikku** [comment]
One further thing to consider: How to handle fields that do not have a natural string based default value, e.g. dates or number inputs? It likely makes sense to have mandatory either a default value _or_ that the field is required.

Alternatively we'd need to re-consider https://github.com/bpmn-io/form-js/issues/54#issuecomment-818654075.
