### ISSUE TITLE
Date Time button when you drag it render wrongly here is an exemple

### ISSUE THREAD

**Issue by shadouuw** [bpmn-io/form-js#540]
![image](https://user-images.githubusercontent.com/48031371/217778622-5275e37f-7190-4047-a861-0bf3e674d72a.png)

**Comment by Skaiir** [comment]
There is a [separate stylesheet](https://github.com/bpmn-io/form-js/tree/develop/packages/form-js-viewer#styling) required for the date-time component, which you are probably missing in your application.

@pinussilvestrus Maybe it would just make sense to merge them during bundling, no?

**Comment by shadouuw** [comment]
Thank you yes that css fixed the issue thank you so much

**Comment by Skaiir** [comment]
You're welcome, good luck on your project :)
