### ISSUE TITLE
Rendered height of multiline text components with default values is broken in Web Modeler

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#546]
### Describe the Bug

The rendered height of multiline text components with default values is broken on Camunda Web Modeler.

<img width="1993" alt="image" src="https://user-images.githubusercontent.com/56470362/219023008-7fca961d-b10d-4a06-b6d1-3729feb1c46e.png">

<img width="601" alt="image" src="https://user-images.githubusercontent.com/56470362/219023771-ce3e43af-0ade-4030-95cb-d0ea9191e1b6.png">

### Steps to Reproduce

1. Add a multiline text
2. Add a default value
3. Save + leave the editor
4. Open the form again
--> The component height is too small to contain the text

### Expected Behavior

The component height should contain the whole text

### Environment

- Form Editor on recent Web Modeler as of February 15th. Does not happen on Desktop Modeler

**Comment by slolatte** [comment]
This bug also occurred for me when generating the following form with the AI Form Generator: 
<img width="1498" alt="Screenshot 2023-06-07 at 11 35 40" src="https://github.com/bpmn-io/form-js/assets/132344616/f8833ca6-ba4e-4159-92af-ba61c2ca602d">
