### ISSUE TITLE
Are there plans to move the rendering module to a different project ?

### ISSUE THREAD

**Issue by juja0** [bpmn-io/form-js#57]
__Is your feature request related to a problem? Please describe__

Not a problem or a feature request but more of a general question. Are there any plans to support non-web based rendering platforms (like react-native) while still using the core module from form-js ? I think that would be quite useful for people wanting to embed camunda forms in native mobile apps.

__Describe the solution you'd like__

Looking at the code, it seems 'core' and 'rendering' are already separate modules and definitely looks like a step in the right direction. I feet it would be even better if we moved the 'rendering' module to a separate project and called it something like 'form-js-renderer-web'. That will allow creating other projects like 'form-js-renderer-react', 'form-js-renderer-react-native', 'form-js-renderer-vuejs' etc. It will also avoid accidental web/dom related code seeping into the core module.

__Describe alternatives you've considered__

Too early to think of alternatives but if I have to, I would probably expose the web based form-js UI on some website and render in my react-native app via webview. This is what we're planning to do in the interim with another library ([formiojs](https://formio.github.io/formio.js/)) till form-js is ready for adoption.

__Additional context__

N/A

**Comment by nikku** [comment]
We don't have such plans yet and our mid-term focus is to support moderately complex forms. However, as you already observed we may end up in a structure that support decomposition and plug-able rendering. No promises though.

I hope this clarified your question sufficiently.
