### ISSUE TITLE
Redesign of delete field icon

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#572]
### What should we do?

We should redesign the delete field icon. Sketches: https://www.figma.com/file/CiTSN1vNETjIAy6W9jUIFp/Form-Editor?node-id=851%3A133246&t=gaz84Ucgk2SC1AX8-1

### Why should we do it?

Context: https://github.com/bpmn-io/form-js/pull/553#issuecomment-1483133111

**Comment by CoffeeGeek101** [comment]
Hey, @pinussilvestrus I would love to help with redesigning the delete button.

**Comment by pinussilvestrus** [comment]
Hi @CoffeeGeek101, thanks for your interest! We also have some mockups in place (cf. issue description), the SVG is not accessible for non-members though.

![Screenshot_2023-03-26-12-58-15-864-edit_com android chrome](https://user-images.githubusercontent.com/9433996/227771337-4014a043-39b8-4147-a17d-80bbbd6a7748.jpg)

If @RomanKostka agrees and you still have interest in working on this issue, I can export them to you or course!
