### ISSUE TITLE
Add ability to merge rows

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#577]
### Is your feature request related to a problem? Please describe.

Currently, it's possible to move complete rows. It's not possible to drop this row into another one and merge their content , in case there is enough space.

![Kapture 2023-03-28 at 13 30 57](https://user-images.githubusercontent.com/9433996/228222747-bbb7fc9b-c88d-4692-94be-6bd1db6cd8df.gif)

### Describe the solution you'd like

Open up the dropping behavior to drop rows inside existing rows, and merge their content.

### Describe alternatives you've considered

Keep everything as is.

### Additional context

Follow up of #560

**Comment by Skaiir** [comment]
Personal opinion, it's not that useful and is only going to overload people mentally. 

Right now we're limited to 4 element, but even if it was more than that (say 6), that means at most you need  2 (3) drag operation to merge two rows. If the dragging feels nice, this shouldn't be effort, I think creating the feature to merge rows will most likely make people lose more time by either doing it by accident if it's easy to do, or taking forever to do it if it's hard.

**Comment by vsgoulart** [comment]
I think the idea is interesting, but we should get some user feedback and not just implement it for the sack of having features

**Comment by Skaiir** [comment]
In the interest of keeping the issues list clean, I think we should close this one. We haven't had any feedback that this is required and arguably there's downsides as it makes dragging rows around more complicated. 

@volodymyr-melnykc @christian-konrad Any objections?

**Comment by volodymyr-melnykc** [comment]
@Skaiir I agree. It's an interesting idea, though I can't think of a strong use case. 
It seems that there was a need to group together related content quickly, and now it is possible with the Group component.

I don't have objections to closing this issue.
