### ISSUE TITLE
Prevent invalid `key` from being entered

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#58]
The properties panel has no built-in validation. It should prevent any invalid key (duplicates as well as empty ones).

![yLvF9xLRjA](https://user-images.githubusercontent.com/7633572/118238760-42e17580-b499-11eb-911b-db281a27de10.gif)

### Reproduce

1. Set the `key` of a field
2. Set the `key` of another field to the same value

### Expected Behavior

1. Duplicate `key`s are prevented
2. Empty `key`s are prevented
3. :arrow_right: All diagrams that are configurable via the `form-js` editor shall be valid, i.e. importable again in editor and viewer instances.

**Comment by nikku** [comment]
Given the fact that this can easily result in someone breaking her forms in a way that is impossible to recover from I'd love to give this some priority.
