### ISSUE TITLE
`@bpmn-io/form-js-viewer` doesn't have all dependecies necessary to work

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#581]
### Describe the Bug

Since #567 `@bpmn-io/form-js-viewer` doesn't work without installing `feelers`

### Steps to Reproduce

1. Install `@bpmn-io/form-js-viewer`
2. Try to build your app (wit Create React App for example)
3. You get the following error message: `Module not found: Error: Can't resolve 'feelers' in '/home/user/repos/tasklist/client/node_modules/@bpmn-io/form-js-viewer/dist'`

### Expected Behavior

`@bpmn-io/form-js-viewer` should have all it's dependencies automatically installed or `feelers` should be considered a peer dependency

**Comment by pinussilvestrus** [comment]
Nice catch. I think having a peer dependency makes much sense here, as it will anyway covered once you use `form-js` directly. 

I will follow up with a patch tomorrow.

**Comment by Skaiir** [comment]
Oh wow that's new, I've never so far managed to forget a core dependency entirely while developing a feature.
It's meant to be there..., I guess we deleted it by accident at some point and never had a clean re-install so it could always find it?

Strange 😅

**Comment by Skaiir** [comment]
@pinussilvestrus

Taking care of this one, we want a pure dependency because form-js-viewer should be a standalone project.
