### ISSUE TITLE
Horizontally center the form in the editor view

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#582]
### What should we do?

Horizontally center the form in the editor view.

### Why should we do it?

Since the row drag handles only appear on hover, the form looks "off" in the edit view (different margins).

![image](https://user-images.githubusercontent.com/56470362/228617411-c986004d-8070-474d-b474-d90be44e7c33.png)

Cf feedback here:
* https://github.com/camunda/camunda-modeler/pull/3523#issuecomment-1488285775

**Comment by pinussilvestrus** [comment]
Related: https://github.com/camunda/form-playground/issues/63. Let's find out whether this is a problem in form-playground or here.
