### ISSUE TITLE
Adorners of text inputs can not show more then one character

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#584]
### Describe the Bug

Adorners of text inputs can not show more then one character, maybe due to the new form layout.

### Steps to Reproduce

1. Create a form
2. Add a text input
3. Add a suffix or prefix adorner

<img width="508" alt="Bildschirmfoto 2023-03-29 um 20 38 47" src="https://user-images.githubusercontent.com/56470362/228635985-41bf3b8b-2587-499a-b8a2-46b4ff292f54.png">

### Expected Behavior

The adorners have sufficient space to display multiple characters (as before, or compare with the number field which still works)

### Environment

- Built of develop branch of March 29

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/586
