### ISSUE TITLE
dropdown shows default values 'x' without having a default value

### ISSUE THREAD

**Issue by RomanKostka** [bpmn-io/form-js#589]
### Describe the Bug

This bug is about the form-js dropdowns.
In the screenshot (from preview mode) both components are 100% identical (besides the copy and options)
One acts like having a default value and the other does not.
![image](https://user-images.githubusercontent.com/114994124/228896262-9278788e-51de-4378-830c-62fe1ace645b.png)

here is the JSON of the shown dropdowns:

```  
{
      "values": [
        {
          "label": "Sales",
          "value": "sales"
        },
        {
          "label": "Marketing",
          "value": "marketing"
        },
        {
          "label": "Finance",
          "value": "finance"
        },
        {
          "label": "IT",
          "value": "it"
        }
      ],
      "label": "Department",
      "type": "select",
      "id": "Field_1dqcnae",
      "key": "department",
      "searchable": false,
      "description": "Select your department",
      "defaultValue": "<none>",
      "validate": {
        "required": true
      }
    },
    {
      "values": [
        {
          "label": "Flexible time off",
          "value": "flexibleTimeOff"
        },
        {
          "label": "Sickness",
          "value": "sickness"
        },
        {
          "label": "Parental Leave",
          "value": "parentalLeave"
        },
        {
          "label": "Public Holiday",
          "value": "publicHoliday"
        },
        {
          "label": "Business Travel",
          "value": "businessTravel"
        }
      ],
      "label": "Policy",
      "type": "select",
      "id": "Field_0xwaxu5",
      "key": "policy",
      "description": "Select the policy your request is based on",
      "validate": {
        "required": true
      }
    }  
 ```

### Steps to Reproduce

1. add a dropdown component
2. select a default value
3. select <none> as a default value

### Expected Behavior

I expect as soon as i select <none> as a default value the dropdown should behave like there is no default value and do not show the 'x' to clear input.

### Environment

- Host: Chrome - latest official build
- OS: MacOS Monterey
- "schemaVersion": 7,
  "exporter": {
    "name": "Camunda Web Modeler",
    "version": "d315f5d"

**Comment by Skaiir** [comment]
Couldn't replicate, but then noticed this was already handled [here](https://github.com/bpmn-io/form-js/issues/562).

Sooo.. closed as duplicate, my bad for not noticing Roman.
