### ISSUE TITLE
Drag preview icon should display under cursor (or at least close to it)

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#596]
### Describe the Bug

Currently, the drag preview does not appear under the cursor, but displays offset relative to where it was grabbed from, which makes it a little clunky to drag around (it becomes uncertain whether to use the mouse or the preview as the drop target). 

*Where the preview appears when grabbed at the rightmost point (red star)*
![image](https://user-images.githubusercontent.com/17801113/229985058-ae6f7702-8a17-451a-8c89-bd7d17a8b2b8.png)

### Steps to Reproduce

1. add any field
2. start dragging it from its rightmost point
3. preview isn't under cursor, and remains offset until drop

### Expected Behavior

3. preview should remain under the mouse cursor

**Comment by Skaiir** [comment]
Seems there some discussion around this topic:
- https://github.com/bevacqua/dragula/issues/285
- https://github.com/bevacqua/dragula/issues/144

I think they key thing here is that the offset isn't configurable (yet). Something we could bring into our own dragula fork, and the dragula 2 in the future.

**Comment by pinussilvestrus** [comment]
The maintainer of dragula@2 is currently working on exactly that: https://github.com/bpmn-io/form-js/pull/588#issuecomment-1495188547 🎉

**Comment by Skaiir** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/1267
