### ISSUE TITLE
Focus Newly Created Properties Panel Entries

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#61]
When creating a new properties panel the new entry (respectively its first input) should be focused.

![118965106-973c9780-b968-11eb-874a-b5cf1c503971](https://user-images.githubusercontent.com/7633572/119005948-36c15080-b990-11eb-9676-8fde299e7742.gif)

This feature might be available once we refactor the properties panel to use the [new properties panel](https://github.com/bpmn-io/properties-panel-next) as a basis.

Related to https://github.com/bpmn-io/form-js/pull/56.

**Comment by pinussilvestrus** [comment]
That will likely be fixed via #249.

**Comment by pinussilvestrus** [comment]
Fixed with the new properties panel!
