### ISSUE TITLE
Adding custom properties doesn't work when certain keys are set

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#614]
### Describe the Bug

![image](https://user-images.githubusercontent.com/17801113/233171515-e6ab2ef1-2ba0-42b8-8ce7-5df9de22ac32.png)

In the above scenario, we cannot add any new custom keys, this is due to the fact that we generate the key name based on the number of existing keys, so in the example we keep overriding key2 with a new key2.

A similar problem exists with static values, but in this case, we get duplicate labels and values.

![image](https://user-images.githubusercontent.com/17801113/233172340-c1397c22-5186-4d4d-820e-8160be9b8305.png)

The different behavior here is due to the fact that we store these as array, and not maps. 

### Steps to Reproduce

1. add on custom property
2. rename the key to key2
3. try to add more
4. nothing happens

### Expected Behavior

4. a new key should be added, most likely with the number incremented by 1 (or however many times needed to get a new key name)

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/form-js/commit/0365a5df36c92a9e7f2eee90c65d339e408679f9
