### ISSUE TITLE
Add Hint to Text/Markdown Editor in Properties Panel

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#62]
There is currently no way for the user to discover that the static text form field supports Markdown, other than simply trying it out.

We should either

* add a hint using the placeholder attribute of the text area

![image](https://user-images.githubusercontent.com/7633572/119007107-3e352980-b991-11eb-97ce-96f1a567e08b.png)

or

* add a description to the text area

![image](https://user-images.githubusercontent.com/7633572/119007202-4f7e3600-b991-11eb-80f4-c7355eb507b1.png)

Related to https://github.com/bpmn-io/form-js/pull/56.

**Comment by nikku** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/63.
