### ISSUE TITLE
Carbon: Investigate an alternative for `styled-components`

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#633]
### What should we do?

For the `form-js-carbon-styles`, we started to use `styled-components`. This speeds up development as we simply mirrored the styles from Tasklist, the only use case we currently have for these styles (cf. https://github.com/camunda/team-hto/issues/143).

We should invest in an alternative to not tight these style to React applications. 

### Why should we do it?

Follow up of #557 

We should not rely on such a specific library, but cf. to a more basic approach, e.g. CSS or SCSS.

**Comment by nikku** [comment]
> For the form-js-carbon-styles, we started to use styled-components. 

I'd apprechiate if we'd not tie to styled components :+1:
