### ISSUE TITLE
Mark `styled-components` as a peer dependency

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#643]
### What should we do?

Recently we added `styled-components` on `@bpmn-io/form-js-carbon-styles` in order to provide a Carbonised view of `form-js`. Because we bundled our own instance of `styled-components` we get the warning in the screenshot below:
![image](https://user-images.githubusercontent.com/1022916/236264744-4f043d96-4553-4927-bced-36e0578e0a6a.png)

Because of this we need to mark `styled-components` as a peer dependency

**Comment by pinussilvestrus** [comment]
Makes sense, additionally we should also add `carbon/elements` as peer dependency as well.
