### ISSUE TITLE
Define and implement UI extension strategy.

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#649]
### What should we do?

We want to allow the UI to be extensible, either through modals or insertion points. This would allow implementations of form-js to truly extend the form editor.

This story is however not well defined at the moment, so treat this issue as a mild placeholder for now.

### Why should we do it?

To enable library users a greater degree of customization for their form editors.

**Comment by nikku** [comment]
@Skaiir Let's chat regarding this issue once you have something tangible.
