### ISSUE TITLE
Text View Overflows with long content

### ISSUE THREAD

**Issue by marstamm** [bpmn-io/form-js#651]
### Describe the Bug

When I accidentally have a very long value without spaces in my Form Text (e.g. data URLs), The text overflows the container 
![Recording 2023-05-10 at 16 42 21](https://github.com/bpmn-io/form-js/assets/21984219/da08d602-fb04-4032-8a16-e95704cae06c)

### Steps to Reproduce

1. Open this File: [form.json.txt](https://github.com/bpmn-io/form-js/files/11443051/form.json.txt)
2. try to delete the text view
3. I need to scroll

### Expected Behavior

Line-breaks are inserted even if there is no space in the content

### Environment

- Host (Browser/Node version), if applicable: Camunda modeler 5.11, https://demo.bpmn.io/form/new
- OS: [e.g. Windows 7]
- Library version: 0.14.1
Originally Reported on Slack: https://camunda.slack.com/archives/CKGH9LR40/p1683728821791789

**Comment by Skaiir** [comment]
This is resolved in 1.1.0 :)
