### ISSUE TITLE
tab and section control

### ISSUE THREAD

**Issue by chenshuichao** [bpmn-io/form-js#68]
Through tab and section control, we can layout many fields in the form,

**Comment by philippfromme** [comment]
Please provide more information about the features you're requesting. Otherwise, I have to close this issue.

**Comment by nikku** [comment]
@chenshuichao As an example you can also provide us with some UI mock-ups to showcase what you mean.

**Comment by chenshuichao** [comment]
I have a form, this form is made of 30 fields.
I can divide three tab, one tab include 10 fields.

**Comment by nikku** [comment]
With tabs you refer to [this UI element](https://getbootstrap.com/docs/5.0/components/navs-tabs/#tabs)?

**Comment by chenshuichao** [comment]
@nikku thank you!
<img width="198" alt="Screen Shot 2021-05-31 at 8 56 35 PM" src="https://user-images.githubusercontent.com/77186544/120195975-e7153b80-c251-11eb-893d-60887f9a5baf.png">
![Uploading Screen Shot 2021-05-31 at 8.56.35 PM.png…]()

**Comment by chenshuichao** [comment]
Summary,Details,Related are tabs.
contact information is section.

**Comment by chenshuichao** [comment]
https://docs.microsoft.com/en-us/powerapps/maker/model-driven-apps/form-designer-overview
we can ref this form designer.

**Comment by nikku** [comment]
Thanks for providing these additional details. We'll likely not support tabbing any time soon.

Our goal for now is _moderately complex forms._ This one is a fairly advanced construct.

**Comment by chenshuichao** [comment]
I think Section is need feature.
Through section we can group the fields.

**Comment by philippfromme** [comment]
I think the upcoming static text form field will help a lot with structuring forms.

**Comment by nikku** [comment]
Closing this issue as we do not intend to support it in the near future. May be something to consider at a later point in time.
