### ISSUE TITLE
Implement spacer component

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#731]
### Is your feature request related to a problem? Please describe.

In some of the usages we've observed, people are using the text view to add spacing to the form. This isn't ideal, so let's simplify this and have a component that simply serves this purpose. 

### Describe the solution you'd like

Vertical spacing should be handled via the grid, so no need to do anything there.
Horizontal sizing will be set via the properties panel for now, might make sense to allow drag resizing there as well in the future.

Reqs:
- [x] Component
- [x] Properties panel configuration
- [x] New Icon

### Describe alternatives you've considered

Keep using the text components for now, but eh it's a low hanging fruit let's just set this one up.

**Comment by RomanKostka** [comment]
i created an icon for this component:
<img width="160" alt="image" src="https://github.com/bpmn-io/form-js/assets/114994124/e81b44da-ff9a-4d86-8073-411538cb7424">


![spacer](https://github.com/bpmn-io/form-js/assets/114994124/e970899d-e72b-45be-a303-45cce846715d)
