### ISSUE TITLE
export { default } from "diagram-js/lib/core/EventBus";

### ISSUE THREAD

**Issue by jay67nie** [bpmn-io/form-js#739]
I installed the latest version 1.0.0 but I get this error. export { default } from "diagram-js/lib/core/EventBus";

How do I get past it?

**Comment by Skaiir** [comment]
Hi @jay67nie, could you give us a bit more context? This looks like an export statement, what is the full error and in which circumstances do you get it? I'll try and investigate this today :).

**Comment by jay67nie** [comment]
√ Browser application bundle generation complete.

Initial Chunk Files | Names   | Raw Size
runtime.js          | runtime |  8.01 kB | 

5 unchanged chunks

Build at: 2023-07-24T09:14:26.023Z - Hash: a33877936c1f2a5a - Time: 971ms

Warning: C:\Users\jerom\IdeaProjects\mis-core\miscore_frontend\src\app\services\core\import.service.ts depends on 'xlsx'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



Error: node_modules/@bpmn-io/form-js-viewer/dist/types/core/EventBus.d.ts:1:25 - error TS2307: Cannot find module 'diagram-js/lib/core/EventBus' or its corresponding type declarations.

1 export { default } from "diagram-js/lib/core/EventBus";
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This is the error I get while compiling my angular application that uses the library.
