### ISSUE TITLE
Editing field with readonly property, v1.0.0

### ISSUE THREAD

**Issue by jay67nie** [bpmn-io/form-js#740]
<img width="477" alt="image" src="https://github.com/bpmn-io/form-js/assets/109383033/ed372123-e333-4321-83a8-48149defeb7c">

![image](https://github.com/bpmn-io/form-js/assets/109383033/c52c1a1e-0b38-49de-a5d3-d728b3d92c2e)

The above files are used to manipulate the value of a readonly field dynamically using events. The focus here is on the manipulation of the defaultValue attribute to a readonly component such that it can change. But when I do so, the value doesn't change. However, if I use the attribute disabled, it changes. I'd like to know what the problem is. I need the field values of the readonly so I cannot use disabled.

**Comment by Skaiir** [comment]
Setting values directly like this won't normally work. Otherwise we'd need observers everywhere which would be very inefficient. 

There's a method in the modeling module called `editFormField` which should do what you want.

**Comment by jay67nie** [comment]
Alright. Could you please explain also what these functions do in the Form.d.ts file?

 _update(update: {
        add?: boolean;
        field: any;
        remove?: number;
        value?: any;
    }): void;
    
    _getState(): State;
    /**
     * @internal
     */
    _setState(state: any): void;
    
    What states are captured in the above methods.

    Then also this below:
    setProperty(property: FormProperty, value: any): void;

**Comment by pinussilvestrus** [comment]
@jay67nie `_update` and `_setState` are internals, so I would not encourage to use these directly. They are basically manipulating the internal state of the Form.


`setProperty` is an API to manipulate global Form properties, such as `readOnly` or `disabled`. There is currently no complete documentation about all such properties. Note that these are not the same as custom properties in the form schema. Form properties are rather to control the behavior of a rendered form, e.g. via

```js
const form = new Form({ 
  container, 
  properties: { readOnly: true }
});

// or

form.setProperty('readOnly', true);
```

**Comment by pinussilvestrus** [comment]
@jay67nie is there anything else you need? If not, let's close this issue. Feel free to also reach out to the [bpmn-io forum](https://forum.bpmn.io/) in case you have any question.

**Comment by pinussilvestrus** [comment]
I'm closing this one. Feel free to re-open in case something is unclear.
