### ISSUE TITLE
Implement a way to update playwright screenshots via GHA

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#743]
### What should we do?

We should be able to trigger a playwright screenshot overwrite via GHA. 

### Why should we do it?

We only upload visual regression tests for mac, but this also means non-mac users can't overwrite the playwright tests. Which obviously is a bottleneck in dev experience. Allowing us to trigger an overwrite would circumvent this need to have a mac user on hand every time we change something visual :D

**Comment by Skaiir** [comment]
A good way we could do this is automatically overwrite the screenshots when we're on develop or master. That way, we get to check if we broke something when we're not in one of the main branches, but we don't have to do extra work to merge it back into the main branches. This also adds the benefit that we don't end up with screenshot conflicts (like two visual changes being done in two branches, but then conflicting when merged back into develop.

**Comment by vsgoulart** [comment]
The problem with this approach is that our CI doesn't block merging with a failed check, so a broken PR could be merged and update the baseline. I would just expect that if your PR makes any visual changes that it would include the updated screenshot on it

> This also adds the benefit that we don't end up with screenshot conflicts (like two visual changes being done in two branches, but then conflicting when merged back into develop.

Has this ever happened?

**Comment by Skaiir** [comment]
@vsgoulart 

> Has this ever happened?
Twice to me. 

> The problem with this approach is that our CI doesn't block merging with a failed check
Our CI is never blocking anyways on form-js, the responsibility of checking the PR is valid lies on the person merging the PR.
