### ISSUE TITLE
show syntaxError when use single backquotes/backticks

### ISSUE THREAD

**Issue by Oleksiivanov** [bpmn-io/form-js#745]
### Describe the Bug

When I try to use single backquotes/backticks in feel expression, as described here https://docs.camunda.io/docs/next/components/modeler/feel/language-guide/feel-variables/#escape-variable-names, I see an error message : `syntaxError: expression expected`

<img width="408" alt="Screenshot 2023-07-25 at 18 39 33" src="https://github.com/bpmn-io/form-js/assets/108869886/0ef2330d-03ec-45af-8194-b0f9e47887a5">

### Steps to Reproduce

1. open web or desktop modeler
2. create a new diagram with any connector, for example, webhook connector
3. enter feel expression, that contains single backquotes/backticks

### Expected Behavior

I can use single backquotes/backticks, and I don't see exception when I use it,  as described in the documentation: https://docs.camunda.io/docs/next/components/modeler/feel/language-guide/feel-variables/#escape-variable-names

### Environment
desktop modeler -> Version: 5.13.0
webmodeler -> https://modeler.cloud.dev.ultrawombat.com/

**Comment by marstamm** [comment]
Hi @Oleksiivanov , thank you for opening this issue. We already have know about this limitation and have an open ticket for it here: https://github.com/camunda/camunda-modeler/issues/3338

A bit of background on this: the backticks are a Camunda extension to the FEEL language and are not part of the FEEL standard. In the first iteration of the FEEL editor, we only support syntax highlighting of the standard FEEL features.

Thank you for notifying us about this, the Feedback helps us understand what language features the users use and if it makes sense to invest in the language extension support in the Modeler
