### ISSUE TITLE
CDN way to bring library in

### ISSUE THREAD

**Issue by ericxin1982** [bpmn-io/form-js#747]
Hi,

Just wondering whether it supports CDN way to bring library in, I do not mean to have a CDN Url, just I can download the source code and place in server and use in CDN that traditional way.

Thanks
Eric Xin

**Comment by pinussilvestrus** [comment]
Hi @ericxin1982!

You can check out our examples, there is a starter example that shows how to embed the distros via `unpkg`: https://github.com/bpmn-io/form-js-examples/tree/master/starter.

As we release our packages via npm, there are multiple vendors that offer a CDN service for the bundles. If you are interested in the unbundled source files in particular, you can have a look at [jsdelivr](https://github.com/jsdelivr/jsdelivr).

Does this answer your question?

**Comment by pinussilvestrus** [comment]
I'm closing this one. Feel free to re-open in case something is unclear.
