### ISSUE TITLE
Check if the Form is valid

### ISSUE THREAD

**Issue by felipentconsult** [bpmn-io/form-js#750]
### Is your feature request related to a problem? Please describe.

I can't enable a submit button from outside the FormJs, without  calling a function to validate it or touching a required field, when I use the form.validate() It turns all red, the errors are updated only when those events happen, it always starts empty, but the form is not valid.

I cannot see if the form is invalid without
### Describe the solution you'd like

A way to see if the form is valid, not if it has errors.

### Additional context

![image](https://github.com/bpmn-io/form-js/assets/132404314/55edb26a-c5d9-432f-a874-f9921fa9816d)
![image](https://github.com/bpmn-io/form-js/assets/132404314/f033b591-e8e0-47c8-87bc-68b5805b463e)

**Comment by Skaiir** [comment]
@felipentconsult 

Hi, if I am understanding what you're trying to achieve, you want to disable the submit button until every value is set properly, so essentially eagerly validate.

So firstly, I'll recommend an alternative. Handle the errors in `form.on('submit')`, it's pretty standard for forms to let you click the submit button even when the form is not complete. This usually highlights the fields that are invalid and is the standard behavior we decided to go with. For this library. 

If you still, for some reason, want to proceed with your way of doing things, then you'll want to have a look at the [validator module](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/core/Validator.js).
