### ISSUE TITLE
select Dynamic Options

### ISSUE THREAD

**Issue by ericxin1982** [bpmn-io/form-js#752]
Hi,

I am reading the starter link, and reviewed each element type, and they all look good.
I am not so clear about the select element, I get a term from starter link, custom property, and also get a term like Dynamic Options, and if I want to bring an external key/value source for select, and how to do?

And custom property, which just is a value setup only? And if I want to bring data in from outside, I still do something like for example to invoke in JS after I assembly schema and table?

And If I have an input field, and input field value would be the input parameter for next select element dynamic source API, how to do?

For example, input field if I put "North America", then select dynamic key/value would be like 1/USA, 2/Canada, 3/Mexico rendering from API, and this API needs an input parameter, "North America"

Thanks
Eric Xin

**Comment by Skaiir** [comment]
Hi @ericxin1982, so custom properties are mostly for the purpose of building on top of our framework. They are not specific to a component.

Selects can be configured via static data, dynamic key (which is basically just a reference to a value in the form data), and expression recently, which allow you to define how the content is defined programmatically using DMN FEEL. I recommend running our playground locally `npm run start:playground` it really helps with understanding individual settings.

When you create your form, you can supply a `data` object which is how you bring in initial state ([example](https://github.com/bpmn-io/form-js#create-and-simulate-a-form-with-input-and-output-data-)).

> For example, input field if I put "North America", then select dynamic key/value would be like 1/USA, 2/Canada, 3/Mexico rendering from API, and this API needs an input parameter, "North America"

So for this case, if I understand correctly, you want to have some options which update live while the form is executing based on an API call, right? This is in our pipeline, but it's currently not implemented. This can probably be achieved using some extensions on your side, but you'll have to dig into the code a little more yourself. If you do develop a solution for this, could you share it here? 

All the best,
Val.

**Comment by ericxin1982** [comment]
Sure.
By the way, I saw viewer has anAPI, setproperty, is there any example somewhere, and where the full properties list is?

Thanks
Eric Xin

**Comment by Skaiir** [comment]
At the moment we don't have a form-js specific documentation, but form-js is pretty much integrated 1-to-1 in Camunda Modeler and we do document it here: https://docs.camunda.io/docs/components/modeler/forms/form-element-library/forms-element-library/. 

Or again, you may run the form playground locally and just look at the properties visually in the properties panel, or download the JSON schemas if you prefer looking at them in text format (this shows a few more properties, like internal properties we don't usually allow to configure).

We also have a JSON schema definition, but it is currently a work in progress.

**Comment by ericxin1982** [comment]
OK, I see.
I saw the camunda link, and if they are almost all property here, then I do not need to dig deeper. Thanks
