### ISSUE TITLE
Select Drop Down `Options Source` resets to `Static` each time form is opened

### ISSUE THREAD

**Issue by upgradingdave** [bpmn-io/form-js#764]
### Describe the Bug

Each time I open to edit a form, the `Options Source` field in the properties panel for a select drop down field is reset to `Static`

### Steps to Reproduce

1. Create a form with a select drop down.
2. Set Options Source to Expression. Enter FEEL expression.
3. Browse away from form, then navigate back to form
4. The Options Source is reset to Static

### Expected Behavior

The form editor should remember that the select drop down was previously configured to use an `Expression` for `Options Source`. I shouldn't have to reset `Static` to `Expression` and re-enter the FEEL expression every time I open to edit the form. 

### Environment

- Host (Browser/Node version): Version 115.0.5790.114 (Official Build) (arm64)
- OS: Mac OS v12.6.3, "Monterey"
- Library version: latest code running in Camunda SaaS as of Mon, Aug 7. 

https://github.com/bpmn-io/form-js/assets/939229/5a94b3e6-be5f-495e-a533-a60e794b8b2e

**Comment by pinussilvestrus** [comment]
Thanks for the detailed steps! I was also able to reproduce it on import in the latest [form-playground demo](https://camunda-form-playground.netlify.app/) with the following schema

```json
{
  "components": [
    {
      "key": "mailto",
      "label": "Email data to",
      "type": "checklist",
      "valuesExpression": "foo"
    }
  ],
  "type": "default"
}
```

**Comment by pinussilvestrus** [comment]
Fixed via https://github.com/bpmn-io/form-js/pull/765 and will be included in the next release cycle 👍 Thanks again @upgradingdave !
