### ISSUE TITLE
Implement `Group` component (also referred to as subform/fieldset)

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#767]
** Implementation epic: https://github.com/camunda/product-hub/issues/1443 **

### Is your feature request related to a problem? Please describe.

There are multiple topics we want to cover with an implementation of such a component.
- A group would assist with the visual and logical separation of components in the form field. 
- Such a component assists with applying rendering conditions at scale, without having to define them for every child field
- Such a component would assist in the mapping (in and out) of data objects, defining a mapping path in a centralized place.

**Prototype:**
![grafik](https://github.com/bpmn-io/form-js/assets/17801113/8607baef-0b5d-4160-ad71-e17ff3121bf4)

#### Requirements:
- [x] I can optionally define a path on a group which will map children of the group to the appropriate data
- [x] I can compose nested paths (user.name)
	- [x] For groups
	- [x] For fields
- [x] I can set a hide-if condition on a group, this:
	- [x] Hide the field when the condition is valid 
	- [x] Does not publish the data associated with those fields, following the behavior of the previous fields
- [x] ~Layouting works well with groups~ (removed from scope)
	- [x] I can still use layouting withing groups
	- [x] ~Children of groups still follow the sizing restrictions of the full form, this means that if a group is 8 wide, children can only sum up to 8 wide as well~
	- [x] ~Resizing of the main group should collapse children down to their "minimum" size at most (need to provide a preview of the feel for this)~
- [x] I cannot set fields and paths which conflict
	- [x] Through the properties panel
	- [x] Through dragging
- [x] Fields should remain aligned in and outside of first order groups
- [x] UX wire-frames must be matched

#### Prototype:
Deployed here: https://github.com/bpmn-io/form-js/pull/768

#### Implement:
- [x] Features 
	- [x] Support properties panel configuration of groups
		- [x] Binding path
		    - [x] Value
			- [x] Validate conflicts with other paths / keys
		- [x] Conditional rendering
		- [x] Show outline of group
		- [x] Label
	- [x] Group component to the components list
	- [x] Group component rendering
		- [x] Outlines as part of the editor selection 
		- [x] Outlines as part of rendering
		- [x] First order groups should keep child fields aligned with root
		- [x] Low fidelity implementation
		- [x] Design review of low fidelity implementation
		- [x] Carbonization layer
			- [x] Evaluate the current look (aimed at carbon in the first place)
			- [x] If necessary, add carbonization layer
		- [x] Full design specs + changes implemented [here](https://github.com/camunda/product-hub/issues/1443)
	- [x] Drag and drop
		- [x] Check for path collision
		- [x] Ensure it's intuitive with groups
	- [x] ~Flexible layout~ (removed from scope)
		- [x] ~Restrict sub-grids to that of upper grids~
		- [x] ~Try out multiple resizing behaviors~
			- [x] ~Blocking~
			- [x] ~Collapsing~
	- [x] Variable mapping
		- [x] Paths
			- [x] Empty paths
			- [x] Simple paths (like keys)
			- [x] Composed paths (. operator)
		- [x] Keys
			- [x] Composed keys
		- [x] Data filtering based on hidden fields
		- [x] Ensure `getSchemaVariables` still works as it should
- [x] Bugs
	- [x] Group header is wrong
	- [x] Dragging out of a group causes a crash
	- [x] Dragging into empty path group doesn't work (allow self-conflicts) 
	- [x] Dragging in general is a little janky
	- [x] Groups eat into eachother when placed in the same row (css fixable)
	- [x] Nested groups create empty object variables even when no field is within them
	- [x] It is possible to use array indexes in keys/paths, we should restrict that, or support it fully (which is quite challenging)
	- [x] Can't delete button due to key?
	- [x] Self-conflicting is back
	- [x] From smoke testing
		- [x] Three nested groups with paths a > empty > c with checkbox d inside, hide if won't trigger on a.c.d
		- [x] Resizing groups isn't working properly on chrome / edge, but fine on firefox (alignment issue maybe)? 	
- [ ] Testing
	- [x] Smoke testing via QA 
	- [x] Unit tests
	- [x] UI regression tests
		- [x] basic
		- [x] carbon
	- [ ] Integration testing
- [x] [Linting](https://github.com/camunda/form-linting/pull/73/commits)
	- [x] Disallow group component prior to 1.3
	- [x] Disallow path accessors in keys prior to 1.3
- [x] [Documentation](https://github.com/camunda/camunda-platform-docs/pull/2504)
	- [x] Document group component
	- [x] Document path inheritance
- [ ] Integrate
	- [ ] Release group feature in form-js
	- [x] Release new linting rules
	- [ ] Integrate where needed
	- [ ] smoke test integrations
- [ ] Finish
	- [ ] Raise all follow-ups as tickets
	- [ ] Publish documentation

### Questions
- [x] Should we sacrifice row dragging in favour of more similarity between editor and preview?  - No, we can investigate this further later.

### Follow-ups
- use feel rendering for paths and keys
- only maintain one global grid for sizing
- Disallow self-referential hide-ifs (linting)

### Additional context

- A11y without using a fieldset proper as an underlyling component ([here](https://www.w3.org/WAI/tutorials/forms/grouping/))
- https://github.com/bpmn-io/form-js/issues/252
- https://github.com/bpmn-io/form-js/issues/464

**Comment by vsgoulart** [comment]
> @vsgoulart I believe the designs are "carbon-like" from the start, but maybe it's worth discovering what that really means. I'll add a step for this. And also a regression test.

@Skaiir Even though the styles might be already Carbon we still need to `@bpmn-io/form-js-carbon-styles` because we need to make sure the component uses the Carbon variables, specially the color ones<sup>1</sup> since we need to able to switch the color between dark and light mode

1: The spacing ones could be nice also, but it's mandatory since spaces don't change very often
