### ISSUE TITLE
Implement Dynamic Lists

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#796]
** Product epic: https://github.com/camunda/product-hub/issues/1444 **

### Is your feature request related to a problem? Please describe.

The main feature we're trying to deliver here is the ability to handle an array or collection of entries, in a semi / read-only fashion at first (but eventually allowing for manipulation via add, remove and reorder). 

#### Prototype:
- [x] Implement prototype
- [x] Conduct kickoff

#### Implement:
- [ ] Features
	- [x] Implement repeating rendering manager class
	- [x] Subform component
		- [x] Core implementation
		- [x] Properties panel configuration
			- [x] Basic group functionality
			- [x] Default group size when no input data is given
			- [x] Disallow empty paths
			- [x] Base number of non-collapsed elements in appearance group
			- [x] Alignment option, top / bottom / centered
	- [x] Implement styles
		- [x] Copy demo styles straight from groups
		- [x] [Implement HFWs](https://github.com/camunda/product-design/issues/827)
		- [x] Verify visuals with Volodymyr
	- [x] Wire components together
		- [x] Hook up indexing to the update cycle
		- [x] Hook up indexing to the render cycle
	- [x] Repeater collapsible state
	- [x] Implement alignment option (groups included)
	- [x] Empty state
	- [x] Visual distinguisher for repeated subform
	- [x] Adjust naming dynamic list
    - [x] Adjust path tooltip
	- [x] Adjust existing infrastructure
		- [x] Path manager
			- [x] Expand the path manager to support array accessors
			- [x] Adjust path conflict logic
		- [x] Submit Data Logic
		- [x] Data Initialization Logic
		- [x] Validation framework
	- [x] Scope creep
		- [x] Add / Remove elements
		- [x] Feel context variables
		- [x] Fixed list
- [x] Bugs
	- [x] Rerenders happening on component hover (partially due to the new hover state management from groups)
	- [x] Renderer defaulting to 1 instance, even in cases where it should be zero ?
	- [x] Input binding breaks with arrays of non-objects
- [ ] Testing
	- [x] Smoke testing
	- [x] Unit tests
	- [x] UI regression tests
		- [x] add array example to basic
		- [x] add array example to carbon
	- [ ] QA
- [x] Linting
	- [x] Disallow new features prior to 1.6, as simple component filter should do here
	- [x] Dynamic list cannot be empty
	- [x] Group alignment not available prior to 1.6
- [ ] Raise follow-ups
- [ ] Documentation
	- [ ] Document new component|
	- [ ] Document array behaviors

### Follow-ups
- Hide empty text state when dragging item in
- Increase the spacing between toggles in the properties panel
- Reduce the spacing between rendered items (needs discussion)
- Track form component usage
- Don't validate fields on adding a new row

### Additional context
- ...

**Comment by DK-2013** [comment]
about Group component.
Is any way restrict accepted field type in Group component?
Saw [validateDrop](https://github.com/bpmn-io/form-js/blob/ce79151d3a3e6b72188b510ac019843c8a2ce711/packages/form-js-editor/src/features/dragging/Dragging.js#L75), but it not apply to node adding from pallete.
And don't see way define such rule by  [validateField](https://github.com/bpmn-io/form-js/blob/ce79151d3a3e6b72188b510ac019843c8a2ce711/packages/form-js-editor/src/features/dragging/Dragging.js#L90C52-L90C65) - it is other area of responsibility, by logic.

**Comment by pinussilvestrus** [comment]
Hi @DK-2013, this is not possible via configuation by now. 

What could work is to create a custom [Group](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/render/components/form-fields/Group.js#L8) component via extension that overrides the registered `group` type and filter out the children before rendering them inside. 

In any case [a separate issue](https://github.com/bpmn-io/form-js/issues/new/choose) would be helpful to discuss this one in an orderly manner.

**Comment by esraagamal6** [comment]
Tested OK with some minor comments:

- Error should be displayed  on the default number field when user type a value greater than 20
- When dynamic list is inserted to another UI gets corrupted
- When having a required field  validation should not be applied on adding a new record because it makes sense to have it empty when it's added
- When hide condition set on the dynamic list with feel expression using a value inside the list  is true, dynamic list is hidden from the preview but not from the UI

https://github.com/bpmn-io/form-js/assets/129334285/a358bca1-3a8d-45c5-90d8-184342e50c2d


https://github.com/bpmn-io/form-js/assets/129334285/a3aff5c6-5d4c-4ca3-a3ed-6b0d952cb6e2


https://github.com/bpmn-io/form-js/assets/129334285/a06f2f88-f62f-4775-9494-884161809149

**Comment by nikku** [comment]
This is super cool :star_struck:
