### ISSUE TITLE
Options defined through feel expressions aren't dynamic

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#809]
### Describe the Bug

![firefox_H4t38wCPEc](https://github.com/bpmn-io/form-js/assets/17801113/0f718cf2-3d8e-4438-b647-d86e7f5ef6fa)

As seen above, changing the isGood variable does not affect the select's values, which is unexpected

### Steps to Reproduce

1. add a checkbox with key `isGood`
2. add a select with options expression `if isGood then [ "good"] else ["bad"]`
3. toggle the checkbox and check the select values
4. nothing changes

### Expected Behavior

The select's values should be dynamically evaluated. 

### Environment

- Host Web modeler saas

**Comment by Skaiir** [comment]
My guess is that we don't recalculate the options every time we open the dropdown.

I see two ways of fixing this:

1. We don't consider performance and recalculate every time
2. We somehow make our feel hook clever enough to recalculate every time a variable changes. This is probably scary to implement.

**Comment by pinussilvestrus** [comment]
> We don't consider performance and recalculate every time

Verified this works via https://github.com/bpmn-io/form-js/commit/fb055ad6108f4b54001554fc8269dfcc7ea2db6c

I will add more test coverage for this one and check whether it works sufficiently.

**Comment by Skaiir** [comment]
While this is not release breaking IMO, there is kind of a nuance with this new options case. Since we can now modify the options at runtime, we should reset the fields when the proper values are not available. Otherwise we get this:

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/c96d41bd-a92a-4462-953e-d1ea3611c327)

**Comment by Skaiir** [comment]
Raised it here: https://github.com/bpmn-io/form-js/issues/817
