### ISSUE TITLE
Readonly number fields should not show controls.

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#810]
### Describe the Bug

There is no reason for number fields to have controls when they are readonly. 

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/bba02da6-ee73-483a-870d-7135ef3cdca3)

### Steps to Reproduce

1. add a number field
2. make it readonly

### Expected Behavior

We should hide the controls in this case

### Environment

Everywhere

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/829
