### ISSUE TITLE
Properly cleanup select-like components values when options change at form runtime

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#817]
### Describe the Bug

Currently, when the options of a field change at form runtime, but a value has already been set for them, the value is kept in the form state despite now not being valid anymore, see below. 

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/154566c2-a68f-4398-a1fb-b34a9c1a9784)

This is particularly obvious with taglists which have a failsafe in place for when that happens, but occurs with every option consuming field.

### Steps to Reproduce

1. Create a checklist/taglist/select or radio component
2. Create a checkbox with key isChecked
3. Set the expression options for the first component to something like `if isChecked then someArray else someOtherArray`, both arrays should have no overlap in values
4. Set a value on the first component
5. Check the checkbox
6. See the value is still present in the output data. In the case of taglist components this is very obvious.

### Expected Behavior

6. The value should be cleaned up, as we shouldn't allow a user to get in such an unsupported data state

If the value is not present in options, then the value is reset to null. Or on the case of multiselects, it should be filtered out and the state should be refreshed.

We should probably get rid of that failsafe as well, ideally by making it impossible for that failsafe state to be reached in the first place.

**Comment by marcosgvieira** [comment]
@Skaiir can you please check if there is any pending review for this one as it's on the "Needs Review" column? Thanks!

**Comment by Skaiir** [comment]
Hey, so this one is in review, I need to close it it's been sitting for a while. Adding it on my queue to handle this week.
