### ISSUE TITLE
Rename the Checklist component as it's not clear to users what use cases it can cover

### ISSUE THREAD

**Issue by volodymyr-melnykc** [bpmn-io/form-js#846]
### Is your feature request related to a problem? Please describe.

A customer wasn't aware that the Checklist component could be used to select multiple list items. 

<img width="76" alt="image" src="https://github.com/bpmn-io/form-js/assets/143816833/c9368f56-e8ba-4bc3-b6b1-afd9dec9e087">

### Describe the solution you'd like

Rename the component to "Multi-select," implying the component's functionality and not a specific use case.

### Describe alternatives you've considered

Alternatively, we can consider other names, e.g. "Checkbox group" - this is how Retool names it.

### Additional

Update the component icon to the one attached below to better align with other components.

![checkbox group](https://github.com/bpmn-io/form-js/assets/143816833/5c969d6d-12d0-4ba1-963a-57033effe273)

**Comment by Skaiir** [comment]
@volodymyr-melnykc I would be in favor of checkbox group, because multi-select is a generic term we use to also describe taglist.

**Comment by volodymyr-melnykc** [comment]
@Skaiir Okay, makes sense. Let's name it "Checkbox group". 
The only downside is that the name is long and won't fit in one line.

We also have a Radio component that functionally makes sense when there is more than one item. So I suggest unifying naming and calling it "Radio group".

Wdyt?

<img width="455" alt="image" src="https://github.com/bpmn-io/form-js/assets/143816833/0fb1865c-5559-4bb9-9230-c780a5027481">
