### ISSUE TITLE
FEEL date functions do not work in forms 

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#853]
### Describe the Bug

FEEL date functions do not work in forms. They just throw an error (in text views), or do not evaluate (in boolean properties).

### Steps to Reproduce

1. Create date objects using the `date()` method out of strings (e.g. from date picker)
2. Run any comparison or date operation (e.g. < or duration)
3. No useful effect

![image](https://github.com/bpmn-io/form-js/assets/56470362/d4c32365-ae02-449a-867f-15ddb29b4019)

### Expected Behavior

The expressions evaluate (like they do in feelers). If I cast them to a string, I can output the result value in text views.

### Environment

- Form.js in Web Modeler as of Oct 18th 2023

**Comment by Skaiir** [comment]
Okay so, we bumped feelin and this sorted it out. Will be available in the next release.
