### ISSUE TITLE
The default value of a select field with static options stays when you switch to expression input

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#859]
### Describe the Bug

The default value of a select field with static options stays when you switch to expression input.
This leads to confusing behavior, and to remove the default value, one has to turn back to static values, remove the default, and return to expression input again.
* If the default value isn't part of the expression input options, it is not visible, but still returned as output
* If the default value is part of the expression input options, it is also visible
### Steps to Reproduce

1. Add select field, add a static option, and pick it as default
2. Switch input source to expression
3. Add any expression as input
4. --> The default is still in the output data, or even visible if it is represented in the new input options

https://github.com/bpmn-io/form-js/assets/56470362/8319c113-020c-4031-8a69-3d2145419794

### Expected Behavior

The default value should be cleared when switching to other input sources (expressions or key).

Either no value is preselected (preferred to avoid bias - only when default is set!), or the serialization is fixed

### Environment

Form editor in Web Modeler SaaS as of Oct 21 2023

**Comment by pinussilvestrus** [comment]
As we do not support default values for values key and expressions, we should clean them up once we change the values type - as [we already do with other properties](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-editor/src/features/properties-panel/entries/ValuesSourceSelectEntry.js#L48).

We could consider adding a [modeling behavior](https://github.com/bpmn-io/form-js/tree/develop/packages/form-js-editor/src/features/modeling/behavior) for this.
