### ISSUE TITLE
Markdown textarea loses focus when form view is refreshed

### ISSUE THREAD

**Issue by andreasgeier** [bpmn-io/form-js#86]
__Describe the Bug__

Using the text component: Every time the form view is refreshed, the textarea loses focus so I can't continue typing my text/markdown and need to click the textarea again and again.

__Steps to Reproduce__

1. Open the [form-js demo](https://demo.bpmn.io/form/)
2. Create a form file
3. Add the text component
4. Enter markdown in textarea on properties panel
5. Stop typing for a moment, then the form view is refreshed and the textarea lost the focus

__Expected Behavior__

Textarea should keep the focus and text cursor position while refreshing the form view so that I can continue typing text.

__Environment__

- Host: Chrome latest
- OS: Mac OS latest

**Comment by andreasgeier** [comment]
It turned out that the issue was caused by the Grammarly Chrome Extension. So it is not an Issue in the Modeler but a potential issue when using the library in the cloud or in other browser applications.

**Comment by philippfromme** [comment]
The reason why the [Grammarly Chrome Extension](https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen) causes the `<textarea>` to lose focus is that it inserts DOM elements. These DOM elements cause the reconciliation to assume the DOM has changed. The `<textarea>` is re-rendered and focus is lost. This only affects the `<textarea>` element of which there is only one instance at the moment (`text` property of text form fields).

**Comment by nikku** [comment]
Closing this as won't fix. 

Let's wait for more users to report this before we investigate potential workarounds.
