### ISSUE TITLE
Dragging rows in a group creates rows without IDs and causes issues

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#861]
### Describe the Bug

Dragging rows in a group creates rows without IDs and causes issues.
* On drag, it behaves strange, sometimes cloning the row
* It results in rows without IDs
* Moving the component out of the group and deleting the group, the component is deleted as well
    * Still visible in the editor, but already removed in the preview

### Steps to Reproduce

See:

https://github.com/bpmn-io/form-js/assets/56470362/98be721e-ef51-4c41-8a3d-1214c2919dff

<img width="1903" alt="Bildschirmfoto 2023-10-21 um 10 21 42" src="https://github.com/bpmn-io/form-js/assets/56470362/bd837cb0-8424-46f4-bd40-626f5039162d">

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by pinussilvestrus** [comment]
Thanks for reporting, that is really cumbersome! Moving this to ready so we follow up, soon!

**Comment by pinussilvestrus** [comment]
Thanks for reporting. Seems like our [layout updater](https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-editor/src/features/modeling/FormLayoutUpdater.js#L45) is not working properly (missing rows set). I will investigate.

**Comment by pinussilvestrus** [comment]
I looked a bit deeper and found out that rendering issues only (or mostly?) occur for text views. The layout is rendered correctly, but the groups containing the dragged row with a text view disappear for some reason.

**Comment by pinussilvestrus** [comment]
Interestingly wise, the fields are still visible in the `preact` tree, but, for some reason, not rendered in the demo.

Also, the broken behavior is not visible in the Dynamic Lists branch (https://github.com/bpmn-io/form-js/pull/808).

**Comment by pinussilvestrus** [comment]
We pick up this again to prevent `row: null` from happening in the first place (cf. https://github.com/camunda/tasklist/issues/3752). 

While moving fields, there might be no `targetRow` as we are on to create a new one. We should avoid that by creating a new row id already on move, similar we do that on create:

```js
 row: targetRow ? targetRow.id : this._formLayouter.nextRowId()
```
