### ISSUE TITLE
Improve the default table styles

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#869]
### Describe the Bug

Currently when rendering a table both in standard styling and with the carbonization layer, it looks pretty bland. With carbon it's a lot worse as we the paddings to zero, which is an actual rendering issue as there is no spacing at all. 

### Steps to Reproduce

1. create a text view
2. add the following text to the view

```
|*test*|test2| 
|---| --- |
|**test222**|**test2**|
|test|test2|
|test|test2|
|test|test2|
```

3. witness the bland styles

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/354ebe40-c480-484d-b92d-864989d5512b)

### Expected Behavior

3. Tables should look nice :)

### Extra context

Here's how it looks carbonized, different data but worse rendering, the table elements are touching. 

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/44c58bd8-bab3-48a4-a850-b0d43221c61c)

**Comment by Skaiir** [comment]
@volodymyr-melnykc 

Would love to hear thoughts and any proposals if you think there's a quick win there.

**Comment by volodymyr-melnykc** [comment]
@Skaiir The solution that Github has is a good reference to follow for this use case.
Video recording:

https://github.com/bpmn-io/form-js/assets/143816833/1274e0a5-4e1a-4778-835c-ec8a946dbd15

- Add a border for the table
- A column should have a width of the item with the longest text
- Headline text is displayed in the bold font-weight

We don't have to have background coloring for items with even / odd ordering.
