### ISSUE TITLE
When I open a select dropdown, other open dropdowns don't close 

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#878]
### Describe the Bug

When I open a select dropdown, other open dropdowns don't close 

![image](https://github.com/bpmn-io/form-js/assets/56470362/aefe2159-76f0-47a6-89b5-0ede7b6d4bc4)

### Expected Behavior

Opening another dropdown, existing ones should close.

### Environment

- Form Editor in Web Modeler as of Nov 2nd 2023

**Comment by pinussilvestrus** [comment]
It seems like `focus` and `blur` don't get really fired when clicking the select: https://github.com/bpmn-io/form-js/blob/develop/packages/form-js-viewer/src/render/components/form-fields/parts/SimpleSelect.js#L65

This leads that the handlers for closing and opening do not get fired correctly, vice-versa.

**Comment by pinussilvestrus** [comment]
Closed via https://github.com/bpmn-io/form-js/pull/885
