### ISSUE TITLE
[Implement] Support iFrame component

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#887]
> This is the implementation epic for https://github.com/camunda/product-hub/issues/1897

### What should we do?

We want to create an `iFrame` component that allows users to specify an external website to be rendered in a form (first iteration). We consider expanding that by providing raw HTML to render into an iFrame, but this is part of a second iteration - and considered as part of another component (cf. https://github.com/camunda/product-hub/issues/1897).

This includes
- [x] Support `iFrame` component that renders a given URL
- [x] Add placeholders for editor
- [x] Allow to specify `iFrame` attributes
  - [x] Url: FEEL and Template support
  - [x] Label: FEEL and Template support
  - [x] Height
  - [x] <del>Sandbox attributes</del>
- [x] Ensure schema version is updated
- [x] Ensure carbon styles are updated
- [x] Ensure JSON schema is updated
- [x] https://github.com/camunda/form-linting/issues/94
- [x] https://github.com/camunda/team-hto/issues/414
- [ ] Integrate updates into products
  - [ ] Tasklist
  - [ ] Desktop Modeler
  - [ ] Web Modeler
  - [ ] Zeebe Play

### Why should we do it?

Reduce the feature gap for special use cases. Examples: Render a Google Doc, render a PDF, etc.

An iFrame component also opens up a lot of potential form fields that we can't deliver on our own.

Cf. to the [product hub](https://github.com/camunda/product-hub/issues/1897) to gather the full rationale.

### Additional context

Related to https://github.com/camunda/product-hub/issues/1897
Related to https://github.com/camunda/team-hto/issues/393
Related to [custom components roadmap](https://miro.com/app/board/uXjVNWfBoyE=/)
Design: https://www.figma.com/file/J78Djf3PgCEAPxFD86floX/Form-Editor-Components?type=design&node-id=465-18970&mode=design&t=uDfUcnzmaWQKvUwz-0
Miro: https://miro.com/app/board/uXjVNQg-WL4=/
Context: https://www.w3schools.com/html/html_iframe.asp
Context: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by pinussilvestrus** [comment]
Cf. the kick off notes in the product hub epic: https://github.com/camunda/product-hub/issues/1897#issuecomment-1814124601

**Comment by pinussilvestrus** [comment]
Regarding QA: We consider testing this on form-js stage already when the PR is open to test.

**Comment by marcosgvieira** [comment]
@pinussilvestrus will you have time to finish this tasks this week? Just checking if we need a handover for @Skaiir @vsgoulart

**Comment by pinussilvestrus** [comment]
@marcosgvieira everything is prepared for the iFrame, PRs for linting and docs are opened and @vsgoulart is aware of them.

From my side everything should be clear for the release.

**Comment by vsgoulart** [comment]
We released this today with `form-js@1.5.0` and merged the docs

**Comment by dfulgham** [comment]
Q: How will this "An iFrame component also opens up a lot of potential form fields that we can't deliver on our own."  does the iFrame component allow interaction with the form schema, and form data to a form field in the iFrame?  Is this planned?

**Comment by vsgoulart** [comment]
> Q: How will this "An iFrame component also opens up a lot of potential form fields that we can't deliver on our own." does the iFrame component allow interaction with the form schema, and form data to a form field in the iFrame? Is this planned?

Hi @dfulgham 

it doesn't allow interaction with form schema and we have no plans to support. What we meant by that is that a form can have external data or interact with external system without needing to to expose it to the form context.

For example, a form could have an embedded PDF. Or could have a Google Sheets document which has critical data necessary to complete this form
