### ISSUE TITLE
[Implement] Support table component

### ISSUE THREAD

**Issue by vsgoulart** [bpmn-io/form-js#888]
> This is the implementation epic for https://github.com/camunda/product-hub/issues/1894

### What should we do?
We want to create a table component to render tabular data in a user friendly way

### Issues

- [x] #889
- [x] #890
- [x] #891
- [x] #892
- [x] #936
- [x] #939
- [x] #940

### Test cases:
- [x]  [Table component](https://camunda.testrail.com/index.php?/cases/view/227637)
- [x] [Table component in Modeler and Tasklist](https://camunda.testrail.com/index.php?/cases/view/228503)

**Comment by esraagamal6** [comment]
@vsgoulart Tested Ok on form JS
