### ISSUE TITLE
iFrame component: Support security attributes

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/form-js#901]
### Is your feature request related to a problem? Please describe.

Related to https://github.com/camunda/product-hub/issues/1897
Follow up of #898 

We support the `iFrame` component as sandbox per default without any possibility of providing [security related attributes ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy#iframe_syntax)(example allow same origin, camera access, microphone access and so on).

This is to do our best to secure the embedded content from causing harm to our users (https://www.reflectiz.com/blog/iframe-security/). 

However, we would like to gather feedback on whether and what of these attributes are still relevant and safe to support. Some web content does not work without such permissions, so we reduce the possible use cases we support. 

### Describe the solution you'd like

Allow iFrame security attributes to be configured. Cf. to the design of the iFrame component.

https://www.figma.com/file/J78Djf3PgCEAPxFD86floX/Form-Editor-Components?type=design&node-id=439%3A7751&mode=design&t=Y6Hr0ZInixtUSMYF-1

![image](https://github.com/bpmn-io/form-js/assets/9433996/3102a02b-7e4c-42ab-a8a0-fcb87addf0e5)

```json
{
  "type": "iframe",
  "label": "The bpmn-io web page",
  "url": "https://bpmn.io/",
  "height": 400,
  "security": {
    "allowSameOrigin": true,
    "fullscreen": true,
    "geolocation": true,
    "camera": true,
    "microphone": true,
    "allowForms": true,
    "allowModals": true,
    "allowPopups": true,
    "allowTopNavigation": true
  }
}
```

### Describe alternatives you've considered

We say that we do not support such use cases.

**Comment by pinussilvestrus** [comment]
I added the removed attributes from the original branch to this one: https://github.com/bpmn-io/form-js/tree/901-iframe-security

**Comment by pinussilvestrus** [comment]
Cf. this security assessment via Slack: https://camunda.slack.com/archives/CKWSYH1S4/p1700492687319809?thread_ts=1700129353.262419&cid=CKWSYH1S4

**Recommendations**
* no allow-same-origin allow-scripts
* only use strictly necessary allow- (i.e. motivated by actual use-cases from users)
* clearly warn users of the risks associated with misconfiguration of iframe (injection, ...). The user controls the URL
 and must ensure that the embedded sites are safe and secure.
* check https://caniuse.com/iframe-sandbox

**Comment by volodymyr-melnykc** [comment]
Latest design for the iFrame component:
https://www.figma.com/file/J78Djf3PgCEAPxFD86floX/Form-Editor-Components?type=design&node-id=439%3A7751&mode=design&t=Y6Hr0ZInixtUSMYF-1

**Comment by marcosgvieira** [comment]
@Skaiir do we already have a task for documentation? As we are introducing those new toggles, would be great to have it documented, so customers understand what they mean (they may look self-explanatory, but is always good to document)
