### ISSUE TITLE
Convert defaults to named exports where possible.

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#918]
### What should we do?

Move to using named exports by default.

### Why should we do it?

To ensure consistent naming and reduce reassignments.

**Comment by pinussilvestrus** [comment]
I have the feeling this one will be in backlog forever, as the benefits are not that high. Do you think it makes sense to keep it or rather to our well-known refactor-as-you-go strategy?

**Comment by Skaiir** [comment]
This is now enforced via linting rules.
