### ISSUE TITLE
iFrame height scales beyond the maximum of the page

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#925]
### Describe the Bug

If you define an iFrame of size 5000, it actually forces it to be 5000 and hence leads to a lot of empty content at the end. Do we want this behavior? Or should it behave as a max height instead, which feels more use-case appropriate.

![grafik](https://github.com/bpmn-io/form-js/assets/17801113/aeec86db-4ef9-4867-acf8-b915889b1837)

### Steps to Reproduce

1. add an iframe
2. make it real big
3. lots of empty space at the bottom

### Expected Behavior

? unsure yet

**Comment by Skaiir** [comment]
@volodymyr-melnykc Opinions?

**Comment by volodymyr-melnykc** [comment]
@Skaiir Are we able to identify the actual height of the content inside the iframe?

**Comment by Skaiir** [comment]
@volodymyr-melnykc We can yeah, but actually I believe with just CSS you don't actually have to worry about this. Simply changing the height parameter to max-height instead should fix this.

**Comment by Skaiir** [comment]
Okay after some exploration and deliberation I will close this one. It is possible to implement, but a little weird and when we start dealing with webpages that grow and shrink, the behavior we want isn't clearly defined, there's no happy path. We can't assume at page load time that the page won't be bigger and hence make use the space, and we also can't have the iframe grow and shrink within the form, so fixed height it is.
