### ISSUE TITLE
Group and Dynamic list components have double borders when placed on the canvas on demo.bpmn.io

### ISSUE THREAD

**Issue by volodymyr-melnykc** [bpmn-io/form-js#947]
### Describe the Bug

When placed on the Form editor canvas, the Dynamic list and Group components display a double border.

### Steps to Reproduce

1. Create a new form.
2. Place the Group or Dynamic list component on the canvas.
3. The placed component displays double borders instead of a single border.

![image](https://github.com/bpmn-io/form-js/assets/143816833/0c6276b9-5e8d-4723-a49e-953275cc12ee)

### Expected Behavior

The Group and Dynamic list components should have a single border displayed when placed on the canvas.

### Environment

- Host: Chromium Engine Version 119.0.6045.199
- OS: MacOS 14.1.2

**Comment by Skaiir** [comment]
There seems to be some issues with the demo here: https://demo.bpmn.io/form/new

Will have to try and see what the problem is, most likely an issue with styles not updating properly.

**Comment by Skaiir** [comment]
Looks like the issue specifically is that the editor styles are being imported before the viewer styles, and so one's overriding the other. Although I guess we could also change the styles over here to be more specific.
