### ISSUE TITLE
Debounce input fields in form-js-viewer

### ISSUE THREAD

**Issue by Skaiir** [bpmn-io/form-js#958]
### Is your feature request related to a problem? Please describe.

At the moment, we do not debounce text entry in any capacity in form-js. This isn't ideal, especially when working with really big forms, as the latency can be felt on the text entry. 

### Describe the solution you'd like

We should most likely be debouncing textfields, textareas and numberfields. We can follow the configuration method to doing debouncing, as is already implemented for the properties panel / editor. 

### Describe alternatives you've considered

n/a

**Comment by Skaiir** [comment]
We found an issue with number field debouncing and have to re-open this one for now.

**Comment by marcosgvieira** [comment]
@Skaiir I see that we have a merged PR, is there anything missing to close this one?
