### ISSUE TITLE
Do Not Delete Form Field Properties That Might Be Required

### ISSUE THREAD

**Issue by philippfromme** [bpmn-io/form-js#96]
__Is your feature request related to a problem? Please describe__

Currently, when editing form field properties using the properties panel empty text/number inputs and textareas will lead to the respective property being removed from the form field. This might lead to problems (cf. https://github.com/bpmn-io/form-js/issues/94). Therefore, we should think about the cases in which this is the desired behavior (e.g. removing min and max length) and the cases in which this behavior is not desired (e.g. there is no good reason to remove the `key` property of a form field).

**Comment by nikku** [comment]
Not sure if this is still an issue. If so, could you provide additional rationale and tag this one with `editor` or `viewer` accordingly?

**Comment by nikku** [comment]
Closing this as outdated. Let us re-open it if it becomes an issue again.
