### ISSUE TITLE
Table row text is not vertically centered

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/form-js#970]
### Describe the Bug

Table row text is not vertically centered
<img width="923" alt="image" src="https://github.com/bpmn-io/form-js/assets/56470362/3a2295ef-926c-4403-8664-f05bd03295b0">

### Steps to Reproduce

1. Add a table to a form
2. The default content is shown
3. It is aligned to the top, not to the center

### Environment

- Host: Chrome, form-js 1.6.2
- OS: MacOS

**Comment by Skaiir** [comment]
@christian-konrad  Yeah I noticed this as well. 
It's a web modeler only problem, carbon css files are causing some problems over there.

**Comment by christian-konrad** [comment]
Sounds Web Modeler should have rules to cover it. It shouldn't be a problem of form-js. @Skaiir are you able to provide them a PR to add a rule to fix it?

**Comment by Skaiir** [comment]
@christian-konrad I could also enforce it here, to have a higher specificity rule that force centering, even if it causes no actual changes to how it would render within the library.
